### ISSUE TITLE
Not working pip instal!

### ISSUE THREAD

**Issue by SergeyPy** [theOehrly/Fast-F1#10]
I'm trying to install a package, but I get this **pip install git+https://github.com/theOehrly/Fast-F1.git**

> ERROR: Command errored out with exit status 1: git clone -q https://github.com/theOehrly/Fast-F1.git /private/var/folders/18/hx8cytt13191h5qsp2gfp9100000gn/T/pip-req-build-ehpkyp7m Check the logs for full command output.

if I do so **pip install https://github.com/theOehrly/Fast-F1.git**

> Collecting https://github.com/theOehrly/Fast-F1.git
>   Downloading https://github.com/theOehrly/Fast-F1.git
>      - 140 kB 423 kB/s
>   ERROR: Cannot unpack file /private/var/folders/18/hx8cytt13191h5qsp2gfp9100000gn/T/pip-unpack-35yll40n/Fast-F1.git (downloaded from /private/var/folders/18/hx8cytt13191h5qsp2gfp9100000gn/T/pip-req-build-att_ycjf, content-type: text/html; charset=utf-8); cannot detect archive format
> ERROR: Cannot determine archive format of /private/var/folders/18/hx8cytt13191h5qsp2gfp9100000gn/T/pip-req-build-att_ycjf

**Comment by theOehrly** [comment]
I cannot reproduce this problem either on Windows 10 or on Debian 10. The second command cannot work, it has to fail. The first one should work though.
As the error is caused during the git clone operation, it is not related to the Fast-F1 code. The repositiory is accessible, so I don't know where the problem is. I don't know what to tell you. Is git, python, pip up to date on your system?

As an alternative, you can download the master branch as a zip file and install with `pip install Fast-F1-master.zip`

**Comment by SergeyPy** [comment]
I work on a mac os, other packages are installed well, the versions are up-to-date

**Comment by theOehrly** [comment]
Does the installation from zip file work?

Also, if you directly run `git clone https://github.com/theOehrly/Fast-F1.git` does this produce an error too?

**Comment by SergeyPy** [comment]
Yes,thanks the installation from the zip file works, but as for the git clone, I'll try later, there is a feeling that need to install the "Xcode Command-line Tools"

**Comment by SergeyPy** [comment]
there was another problem when I execute this code

```
import fastf1 as ff1
import pandas as pd
ff1.utils.enable_cache('path/to/folder/for/cache')  # optional but recommended

monza_quali = ff1.get_session(2018, 'Monza', 'Q')

vettel = monza_quali.get_driver('VET')
print(f"Pronto {vettel.name}?")
# Pronto Se🅱️astian?

from matplotlib import pyplot as plt
from fastf1 import plotting

laps = monza_quali.load_laps()
fast_leclerc = laps.pick_driver('LEC').pick_fastest()
t = fast_leclerc.telemetry['Time']
vCar = fast_leclerc.telemetry['Speed']

# The rest is just plotting
fig, ax = plt.subplots()
ax.plot(t, vCar, label='Fast')
ax.set_xlabel('Time')
ax.set_ylabel('Speed [Km/h]')
ax.set_title('Leclerc is')
ax.legend()
plt.show()

```

an error occurs

```
core           INFO 	Loading Italian Grand Prix Qualifying
core           INFO 	Getting summary...
Pronto Sebastian?
core           INFO 	Formatting summary...
core           INFO 	Getting telemetry data...
api            INFO 	Fetching car data
api            INFO 	Parsing car data
 TypeError: 'NoneType' object is not iterable 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-8333769ef15e> in <module>
     12 from fastf1 import plotting
     13 
---> 14 laps = monza_quali.load_laps()
     15 fast_leclerc = laps.pick_driver('LEC').pick_fastest()
     16 t = fast_leclerc.telemetry['Time']
```

**Comment by theOehrly** [comment]
This is a problem which occurs since this weekend. See Issue #9 

There's currently no workaround for this. I'm basically still hoping that the problem will resolve itself within the next few days. We will see...
