### ISSUE TITLE
Error with Livetiming Module in Debug mode

### ISSUE THREAD

**Issue by TerminatorPlati** [theOehrly/Fast-F1#12]
If I use the debug mode this exception comes up.

![image](https://user-images.githubusercontent.com/69049717/110920462-b5a96580-831d-11eb-8010-e23c49d7a495.png)

**Comment by TerminatorPlati** [comment]
![image](https://user-images.githubusercontent.com/69049717/110970026-9f20ff80-8359-11eb-92d9-b5c089604a7e.png)

Ok, now there is this error with Day One of Test

**Comment by theOehrly** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/69049717/110970026-9f20ff80-8359-11eb-92d9-b5c089604a7e.png)
> 
> Ok, now there is this error with Day One of Test

That's the same problem as for all the old sessions... Telemetry data is not available. Seems like they haven't fixed that over the winter sadly.
Also, I can't find the telemetry replay in the app to check for sure.

Guess it will be necessary then to record live timing data if one wants to have telemetry data and not just timing data.

**Comment by theOehrly** [comment]
New release is out. Including support for actually using the live timing data.
Hopefully everything works well
