### ISSUE TITLE
Installed but not really able to do anything

### ISSUE THREAD

**Issue by FMPete** [theOehrly/Fast-F1#13]
Hello,

sorry for being a complete beginner to programming. But I'm not able to really do anything. just tried the example provided: 

_"import fastf1 as ff1
from fastf1 import plotting
from matplotlib import pyplot as plt
plotting.setup_mpl()
ff1.Cache.enable_cache('path/to/folder/for/cache')  # optional but recommended
race = ff1.get_session(2020, 'Turkish Grand Prix', 'R')
laps = race.load_laps()
lec = laps.pick_driver('LEC')
ham = laps.pick_driver('HAM')"_

So I'm getting an error code of:

_"File "C:\***\***\***\***\F1\F1FastTest.py", line 12, in <module> plotting.setup_mpl()
AttributeError: module 'fastf1.plotting' has no attribute 'setup_mpl'"_

and if I comment it out it gets stuck at:

_"File "C:\***\***\anaconda3\envs\spyder\lib\site-packages\requests_cache\backends\storage\dbdict.py", line 74, in connection
    con = sqlite.connect(self.filename)
OperationalError: unable to open database file"_

I tried several Python versions but didn't seem to fix the issue. Is it because ther eis a live session going on? Or am I just too stupid to operate this :)

Peter

**Comment by theOehrly** [comment]
Hi, that very much looks like you do not have the newest version installed?
Did you install using ``pip install fastf1``? If yes, did you have  a previous version installed? Try to do a clean installation of the fastf1 package.

Also, the string 'path/to/folder/for/cache' needs to be replaced with a valid path to an existing folder. But that should raise a different error.

**Comment by FMPete** [comment]
Thanks, sorry for late answer but that solved my issues!
