### ISSUE TITLE
[BUG] Live Timing client throws RuntimeError on Python 3.9.12

### ISSUE THREAD

**Issue by eXhumer** [theOehrly/Fast-F1#132]
### Describe the issue:

![image](https://user-images.githubusercontent.com/62310242/160243217-5f5e0dce-f6d0-42d9-a70a-1cc21dfcdd0d.png)

I am using Python 3.9.12 which is supposed to support live timing, yet I am still getting this error regarding Python version. Is like 3.9.0 the only supported version 3.9 branch of Python?

### Reproduce the code example:

```python
python -m fastf1.livetiming save saved_data.txt
```

### Error message:

RuntimeError: The live timing client does only support Python 3.8 and 3.9 but you are using version 3.9.12

**Comment by eXhumer** [comment]
So update, I commented out that RuntimeError in the script and it appears to work fine,

**Comment by Ozsqhbj** [comment]
I had the same problem. This worked for me
if (ver := sys.version_info) >= (3, 10):

**Comment by theOehrly** [comment]
Yes, 3.9.x should be fine. I guess I messed up the version check there. Need to fix that.
