### ISSUE TITLE
[BUG] Error getting telemetry for any driver in Aus GP 2022

### ISSUE THREAD

**Issue by Sn4k3ss** [theOehrly/Fast-F1#146]
### Describe the issue:

While trying to retrieve the telemetry (using get_telemetry() or get_car_data() on an instance of `Lap`) an exception is thrown with message: _"20"_
This happens for any session at Aus GP

Digging deeper i found out that the line of code giving the error is the following

`814` in `fastf1.core`, function: `def calculate_driver_ahead(self)`

The error is thrown when trying to acces the car_data for Magnussen, due to the fact that `session.car_data` doesn't contain the key `"20"`

Maybe it's something related to the ergast api?

### Reproduce the code example:

```python
session = ff1.get_session(2022, 3, "FP2")
session.load()
driver1_lap = session.laps.pick_driver(driver1).pick_fastest()
driver1_tel = driver1_lap.get_telemetry().add_distance()
```

### Error message:

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '20'
```

**Comment by markste-in** [comment]
It seems there is no telemetry data for MAG in FP2
<img width="715" alt="image" src="https://user-images.githubusercontent.com/33337590/162431623-d09df60b-bd34-42aa-a175-fba320c47e87.png">

**Comment by Sn4k3ss** [comment]
Fp1 neither, but the problem is that the error comes up when trying to get the telemetry for any other driver, I don't know why the `calculate_driver_ahead()` is needed, maybe the code can be more robust to ignore if data is unavailable for certain driver? Or is needed further? Just suggesting

**Comment by markste-in** [comment]
It calculates the distance to the driver ahead and is part of the get_telemetry function. Unfortunately this function fails without car / telemetry data

**Comment by Sn4k3ss** [comment]
The problem just go away checking if the `driver` is in `self.session.car_data` at line `787` in `fastf1.core`, function: `def calculate_driver_ahead(self)`

```
for drv in self.session.drivers:       
    if drv in self.session.car_data:
        ...
```

I'm not sure whether this solution can affect some other lines of code

**Comment by theOehrly** [comment]
@Sn4k3ss thanks for figuring out the problem and how to fix it. I've updated the code and made a new release just now.

Just a note, in general I do not recommend using `.get_telemetry`. Rather, use `.get_car_data` if you don't need car data and position data merged. It returns slightly cleaner data as no resampling and interpolation  is necessary.

**Comment by Sn4k3ss** [comment]
If i may ask, why `.get_telemetry` needs to get other driver's infos? I didn't look too deep into the code to find that out, better precision?

And by the way I've been seeing a lot of coments from your side in other issues on why using `.get_car_data` instaed of `.get_telemetry`, but I was looking for both car e pos data so don't worry👌

**Comment by theOehrly** [comment]
@Sn4k3ss because `.get_telemetry` also adds the computed telemetry channels like 'Distance' and 'DistanceToDriverAhead'. This was done for convenience reasons. In hindsight, it maybe wasn't the best design decision, but changing this would be a major braking change now.
The calculation of the distance to the driver ahead needs to evaluate the position of all cars on track at the same time. Therefore, data of all cars needs to be accessed to calculate this value for one driver.

**Comment by Sn4k3ss** [comment]
Okay, thanks for the explanation👍
