### ISSUE TITLE
Information and Features

### ISSUE THREAD

**Issue by TerminatorPlati** [theOehrly/Fast-F1#15]
Is it possible to have a similar feature in Fast-F1 or another program that allows you to have a live telemetry graph (instead of that shit F1 graph in the app)?

 I open this issue because I saw that now we need to register the live packages, so (non-programmer hypothesis) the work is halfway.

 Thank you

**Comment by theOehrly** [comment]
You can create something like that yourself as a replay but not as a live graph, for multiple reasons. 

The structure of the code is not setup to do this. Parsing a data stream live is not really possible and would mean a rather big refactoring effort. I'm not willing to invest that time. Some of the validation, accuracy checks and calculations (e.g. LapStartTime and others) can only be done once all the data is available. A live version of the api parser would need to skip those steps.
At that point I could also write a separate parser for live data only... Not going to happen. More time, two things to maintain.
Or I would need to rewrite everything from the ground up. And I do not have time for that.

And another important point: Visualizing live data is what the official app is for. I _**really**_ do not want to compete against them using their own data. That's likely a bad idea.

**Comment by Blas47** [comment]
I was trying to get the Data of the free practices of todays session's 2021 Bahrein Gran prix with this code 
FP2_BAH = ff1.get_session(2021,'Bahrain Grand Prix','FP2')
and it gives me an error saying that the data is not available yet. I was wondering if you know how much does it takes from the end of a session to the data to be accesible?
Thank you for your time!!

**Comment by theOehrly** [comment]
> I was trying to get the Data of the free practices of todays session's 2021 Bahrein Gran prix with this code
> FP2_BAH = ff1.get_session(2021,'Bahrain Grand Prix','FP2')
> and it gives me an error saying that the data is not available yet. I was wondering if you know how much does it takes from the end of a session to the data to be accesible?
> Thank you for your time!!

This error message only concerns data which is loaded from the ergast api. Only little data is requested from there. Things like full driver names, finishing position at the end of the race, points received, whether the race was finished, ... stuff like that.
This data is only available after a race weekend I think. 

But, lap timing data which is requested from F1's api is still available. Usually you don't need the data from ergast. Therefore you likely won't have any problems even if the data from ergast is not yet available.

**Comment by Blas47** [comment]
Thank you very much for your clarification!!!
