### ISSUE TITLE
Unable to parse timings from 2021 testing

### ISSUE THREAD

**Issue by RahulJois** [theOehrly/Fast-F1#16]
>>> race = ff1.get_session('2021',gp = 'testing')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rahul/Library/Python/3.9/lib/python/site-packages/fastf1/core.py", line 132, in get_session
    pre_season_week, event = _get_testing_week_event(year, event)
  File "/Users/rahul/Library/Python/3.9/lib/python/site-packages/fastf1/core.py", line 196, in _get_testing_week_event
    raise InvalidSessionError
fastf1.core.InvalidSessionError: No matching session can be found

I get this error when I try to load data from this season's testing

**Comment by theOehrly** [comment]
Your code is wrong there. See https://theoehrly.github.io/Fast-F1/fastf1.html#package-functions

`.get_session` requires three arguments for testing. Also, year needs to be an integer.

A correct function call would be `ff1.get_session(2021, 'testing', 1)` for the first day of this year's pre-season testing.

**Comment by TerminatorPlati** [comment]
Hi, there is a problem with the parse of live timing test. Here a screen of error. I think there is a mistake with the formart of JSON and with decode

![image](https://user-images.githubusercontent.com/69049717/111076380-66fdf600-84ec-11eb-99ef-4427e8a073d7.png)

**Comment by theOehrly** [comment]
I can reproduce the problem with my data. 2 out of > 29000 lines of data contain invalid json.
I'm working on a fix with additional errorhandling

**Comment by theOehrly** [comment]
Please update and try again. It now works with my recorded data.

It should log an error count while loading the data. Please let me know the error count you get with you data.

**Comment by TerminatorPlati** [comment]
> Please update and try again. It now works with my recorded data.
> 
> It should log an error count while loading the data. Please let me know the error count you get with your data.

OK, I tried it and this is the result. In my data is missing about 1 hour of recording, since I started the script later

![image](https://user-images.githubusercontent.com/69049717/111080934-2c528880-8501-11eb-9441-d4f711befe3f.png)

**Comment by TerminatorPlati** [comment]
Also if I try to graph with speed (Distance-Velocity) it throws me this exception. I do not know if it is a problem of my data or of FastF1

![image](https://user-images.githubusercontent.com/69049717/111081117-011c6900-8502-11eb-92da-782276d59e38.png)

**Comment by theOehrly** [comment]
Ok, data loading looks good. Or rather, as expected.

Can you share the code which causes that error? Plotting Speed and Distance works for me.

**Comment by TerminatorPlati** [comment]
> Ok, data loading looks good. Or rather, as expected.
> 
> Can you share the code which causes that error? Plotting Speed and Distance works for me.

Okay, I did another test with other drivers and it works. With Leclerc and Hamilton, I get the error above. Maybe it's due to my data where the first hour of testing is missing. For example with Sainz and Verstappen I have no problem. The script is the one from the documentation with the delta time

**Comment by theOehrly** [comment]
I just saw I should actually update that delta time example. I missed that. The example code does not adhere to the stuff I recommend in the documentation right next to it.
The delta time function returns telemetry data, and you should actually use that telemetry data if you want the best accuracy. Although the differences are marginal.

Attached: Data from the first ~2 hours this morning
[d3_m_1_data.txt](https://github.com/theOehrly/Fast-F1/files/6137632/d3_m_1_data.txt)
You can test with this and see if it works

**Comment by RahulJois** [comment]
> Your code is wrong there. See https://theoehrly.github.io/Fast-F1/fastf1.html#package-functions
> 
> `.get_session` requires three arguments for testing. Also, year needs to be an integer.
> 
> A correct function call would be `ff1.get_session(2021, 'testing', 1)` for the first day of this year's pre-season testing.

Tried with the session number. Unable to load telemetry or lap timings

>>> race = ff1.get_session(2021, 'testing',3)
core        WARNING 	The Ergast API is not supported for testing
>>> race
<fastf1.core.Session object at 0x7f85d775d970>
>>> race.load_telemetry()
api            INFO 	Fetching car data...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastf1/core.py", line 1310, in load_telemetry
    car_data = api.car_data(self.api_path, livedata=livedata)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastf1/api.py", line 193, in cached_api_request
    return func(api_path, response=response, livedata=livedata)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastf1/api.py", line 727, in car_data
    raise SessionNotAvailableError("No data for this session! Are you sure this session wasn't cancelled?")
fastf1.api.SessionNotAvailableError: No data for this session! Are you sure this session wasn't cancelled?
>>> race.load_laps()
core           INFO 	Loading Pre-Season Test 1 - Practice 3
api            INFO 	Fetching timing data...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastf1/core.py", line 1133, in load_laps
    data, _ = api.timing_data(self.api_path, livedata=livedata)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastf1/api.py", line 193, in cached_api_request
    return func(api_path, response=response, livedata=livedata)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastf1/api.py", line 289, in timing_data
    raise SessionNotAvailableError("No data for this session! Are you sure this session wasn't cancelled?")
fastf1.api.SessionNotAvailableError: No data for this session! Are you sure this session wasn't cancelled?

The load_telemetry and load_laps functions work for old races, though

**Comment by RahulJois** [comment]
load_laps() function seems to have a problem with v2.1.3. When I downgraded to 2.1.2 it is working fine

**Comment by theOehrly** [comment]
> 
> 
> load_laps() function seems to have a problem with v2.1.3. When I downgraded to 2.1.2 it is working fine

Yes, you're right. Use v2.1.2 then as a workaround. I won't put out another quick release to fix this. 
I'll aim for a more well-rounded release before the first race. These very fast changes are not good because there's not enough time to actually test the changes properly.

**Comment by RahulJois** [comment]
> > load_laps() function seems to have a problem with v2.1.3. When I downgraded to 2.1.2 it is working fine
> 
> Yes, you're right. Use v2.1.2 then as a workaround. I won't put out another quick release to fix this.
> I'll aim for a more well-rounded release before the first race. These very fast changes are not good because there's not enough time to actually test the changes properly.

Yeah no issues. I downgraded. Just wanted to let you know about the issue

**Comment by ricky732** [comment]
@RahulJois I am new and this software looks amazing! Could you share with me the files of recording you have done for pre-season testing? I need to try with a record file to learn the program better... If you don't want to share it here, my email is: riccardoferro1234@gmail.com

**Comment by ricky732** [comment]
@TerminatorPlati ho visto che sei italiano dalle foto. Ho scoperto oggi questa repository ed è fantastica. Potresti mandarmi le registrazioni dei Pre-Season Testing che hai fatto? I file txt intendo... Così posso imparare il programma bene prima dell'inizio della stagione!! Se non vuoi mandarli qua, ti posso dare la mia mail che è riccardoferro1234@gmail.com. Grazie mille!!

**Comment by ricky732** [comment]
@theOehrly do you have some recording files to share with me as I can learn the program better before the start of the season? Thank youuu!! :) If you don't want to share them here, my e-mail il riccardoferro1234@gmail.com :)

**Comment by theOehrly** [comment]
Cached data for one of last year's races is available for download next to the v2.1rc release here on github. You can install v2.1.2 using pip and then use the cache files you have downloaded from here with that.

**Comment by ricky732** [comment]
@theOehrly Oh, it is true!!!! And it works perfectly. It's really really good... But is there a way to get it more precise? I have a very powerful PC, I can push it on the limit if there's a way. In the guide if I am not wrong I read something about precision... It is already good like this, but i want the maximum if it is possible. Thank you for replying!! :)

**Comment by ricky732** [comment]
[
![Errore](https://user-images.githubusercontent.com/46622560/112152585-bb872c80-8be2-11eb-94f1-153c65af0f01.jpg)
](url)

I wrote this script following the giude and I have this error that I am not able to solve... I need help! :) @theOehrly

**Comment by theOehrly** [comment]
The function returns three values now, and I haven't properly updated the example code. Check the description of the return values just below the examples.
(I've already fixed the example actually but that version of the documentation isn't published yet)

**Comment by ricky732** [comment]
![codice](https://user-images.githubusercontent.com/46622560/112287310-86371900-8c8c-11eb-8579-e779b3542f77.png)

 @theOehrly Solved it!!! But is this the right code for taking data by a txt recording? I read it on the guide, but I find strange (livedata=livedata). But maybe it's right :)

**Comment by theOehrly** [comment]
> 
> 
> ![codice](https://user-images.githubusercontent.com/46622560/112287310-86371900-8c8c-11eb-8579-e779b3542f77.png)
> 
> @theOehrly Solved it!!! But is this the right code for taking data by a txt recording? I read it on the guide, but I find strange (livedata=livedata). But maybe it's right :)

That's correct. The keyword argument has the same name as the variable that is passed to it. You could also change the name of the variable of course.

**Comment by TerminatorPlati** [comment]
@theOehrly  Hi, why am i getting this error? I used today's FP1 live data

![image](https://user-images.githubusercontent.com/69049717/112640693-d9060180-8e41-11eb-9960-e861dfbeee51.png)

**Comment by theOehrly** [comment]
I could not record any data from FP1 (my own fault). Therefore, I cannot check whether the same error occurs for me. But I have recorded FP2 and after a quick check everything seems fine there.
Was there anything of note or any error messages? Do you have recorded the full session?

The most likely cause is, that you have no telemetry data at all. Or that telemetry data and timing data are not synchronized properly. I cannot tell from the error above if it is any of the two and why that would be.
If you want, you can send me your recording (oehrly@mailbox.org or post it here). Then I can check if there's a bug. Also, you could send me the script that caused the error. But I don't know how soon I have time for that.

**Comment by TerminatorPlati** [comment]
> I could not record any data from FP1 (my own fault). Therefore, I cannot check whether the same error occurs for me. But I have recorded FP2 and after a quick check everything seems fine there.
> Was there anything of note or any error messages? Do you have recorded the full session?
> 
> The most likely cause is, that you have no telemetry data at all. Or that telemetry data and timing data are not synchronized properly. I cannot tell from the error above if it is any of the two and why that would be.
> If you want, you can send me your recording ([oehrly@mailbox.org](mailto:oehrly@mailbox.org) or post it here). Then I can check if there's a bug. Also, you could send me the script that caused the error. But I don't know how soon I have time for that.

Hi, thanks for the reply. I still fixed clears of the cache. rereading the documentation I read that after each update it must be cleaned. after doing this step it works

**Comment by theOehrly** [comment]
> Hi, thanks for the reply. I still fixed clears of the cache. rereading the documentation I read that after each update it must be cleaned. after doing this step it works

Ok, great that it works now. But, just for clarification, did you load the data with an older version first before updating?
Also, I did not expect any problems with the cache for this update. I'll have to think about what likely caused this.

**Comment by nicZox** [comment]
Hi @theOehrly, why trying to use the livedata of the qualifications do I get this error?

![image](https://user-images.githubusercontent.com/76594617/112727451-d6c7a400-8f22-11eb-86eb-0d94bd941ed1.png)

**Comment by theOehrly** [comment]
@nicZox for now, use a manual workaround. Delete all the lines that start with `['SessionData'` but do not contain an entry named `'StatusSeries'`. There will likely be four lines that should be deleted.

I'll see that I get this fixed properly soon.

Also, I do get notifications from github on new messages in issues!
