### ISSUE TITLE
[BUG] <Missing Laps from 2020 Austrian Grand Prix>

### ISSUE THREAD

**Issue by Ethelom** [theOehrly/Fast-F1#169]
### Describe the issue:

When loading laps for the 2020 Austrian Grand Prix there is no driver with 71 laps. For example, Bottas has 67 laps and Leclerc has 66 laps, when in fact the Austrian Grand Prix consists of 71 laps as far as I know. Am I missing something?

### Reproduce the code example:

```python
session = fastf1.get_session(2020, 'Austrian Grand Prix', 'R')
session.load()
session.laps.DriverNumber.value_counts()
```

### Error message:

```shell
session.laps.DriverNumber.value_counts()

77    67
10    66
16    66
5     66
99    66
31    66
6     66
11    66
55    66
44    66
4     66
26    64
23    62
7     48
63    44
8     44
20    19
18    15
3     12
33    10
```
As seen above none of the drivers has a total of 71 laps.

**Comment by theOehrly** [comment]
There were some weird things going on at the beginning of the 2020 season. It looked like there were some changes on the server backend stuff of the API and it wasn't working properly. My first guess is that this'd be related. But I haven't had time to look at this yet.

**Comment by theOehrly** [comment]
So, as expected, there are some laps missing in the source data between lap 9 and lap 14 approximately. There's nothing I can do about that.
