### ISSUE TITLE
[BUG] No lap information for Zhou in 2022 Imola sprint race

### ISSUE THREAD

**Issue by d-henness** [theOehrly/Fast-F1#175]
### Describe the issue:

As per the documentation regarding DNFs:
"First lap in a race: A single lap with minimal information will be added in race sessions if a driver does not complete at least one timed lap. The LapStartTime for this lap will be set to the start time of the session as with all other laps in a race. The Time at which this lap was “set” will be set to the time at which the first driver completes their first lap."

Zhou went out in the first lap but has no lap information for this session. I am using version 2.2.5 of fastf1

### Reproduce the code example:

```python
import os
import fastf1


cashe_dir = "./cashe"
if not os.path.isdir(cashe_dir):
    os.mkdir(cashe_dir)
fastf1.Cache.enable_cache(cashe_dir)

year = 2022
weekend = 4

qualifying_session = fastf1.get_session(year, weekend, 4)
qualifying_session.load()


print(qualifying_session.laps.pick_driver('ZHO'))
```

### Error message:

```shell
Empty Laps
Columns: [Time, DriverNumber, LapTime, LapNumber, Stint, PitOutTime, PitInTime, Sector1Time, Sector2Time, Sector3Time, Sector1SessionTime, Sector2SessionTime, Sector3SessionTime, SpeedI1, SpeedI2, SpeedFL, SpeedST, IsPersonalBest, Compound, TyreLife, FreshTyre, LapStartTime, Team, Driver, TrackStatus, IsAccurate, LapStartDate]
Index: []
```

**Comment by theOehrly** [comment]
Probably this is just the sprint race not being treated like a race. Therefore, no lap is added. If that's the case, then it is a simple fix. I'll check.
