### ISSUE TITLE
StatusSeries error

### ISSUE THREAD

**Issue by FMPete** [theOehrly/Fast-F1#18]
**So I downloaded the live data from qualifying yesterday and trying to load it into python I'm getting this error. Is it really supposed to download api data when I have the live-data downloaded? Or is it for meta data?**

"runfile('C:/Users/peter/OneDrive/Dokument/F1/Live.py', wdir='C:/Users/peter/OneDrive/Dokument/F1')
core           INFO 	Loading Bahrain Grand Prix - Qualifying
api            INFO 	No cached data found. Downloading...
data           INFO 	Loading live timing data. This may take a bit.
Traceback (most recent call last):

  File "C:\Users\peter\OneDrive\Dokument\F1\Live.py", line 15, in <module>
    quali.load_laps(with_telemetry=True, livedata=livedata)

  File "C:\Users\peter\anaconda3\envs\spyder\lib\site-packages\fastf1\core.py", line 1141, in load_laps
    data, _ = api.timing_data(self.api_path, livedata=livedata)

  File "C:\Users\peter\anaconda3\envs\spyder\lib\site-packages\fastf1\api.py", line 178, in cached_api_request
    data = func(api_path, response=response, livedata=livedata)

  File "C:\Users\peter\anaconda3\envs\spyder\lib\site-packages\fastf1\api.py", line 290, in timing_data
    if livedata is not None and livedata.has('TimingData'):

  File "C:\Users\peter\anaconda3\envs\spyder\lib\site-packages\fastf1\livetiming\data.py", line 215, in has
    self.load()

  File "C:\Users\peter\anaconda3\envs\spyder\lib\site-packages\fastf1\livetiming\data.py", line 74, in load
    self._load_single_file(fname)

  File "C:\Users\peter\anaconda3\envs\spyder\lib\site-packages\fastf1\livetiming\data.py", line 112, in _load_single_file
    self._parse_session_data(msg)

  File "C:\Users\peter\anaconda3\envs\spyder\lib\site-packages\fastf1\livetiming\data.py", line 139, in _parse_session_data
    if isinstance(msg['StatusSeries'], dict):

KeyError: 'StatusSeries'"

**Comment by theOehrly** [comment]
For now, use a manual workaround. Delete all the lines that start with `['SessionData'` but do not contain an entry named `'StatusSeries'` from the recorded text file. There will likely be four lines that should be deleted.
Make a copy of the recording before, just to be sure.

I'll see that I get this fixed properly soon.

When you use recorded live timing data, no more data is downloaded from the F1 api. The log messages says "downloading" but the data is not actually downloaded anymore. This message is generated by the cache. But the cache has no idea that pre-recorded live timing data is used. This is just a result of the fact that I had very little time to implement this during pre-season testing. My time is limited, fixing this message was and is not a high priority.

**Comment by theOehrly** [comment]
This error occurs again for the race. Here's a snippet of code you can use to preprocess the recorded data. After that it should load just fine.

    with open('2021_1_R.txt', 'r') as infile:
        with open('2021_1_R_stripped.txt', 'w') as outfile:
            for line in infile.readlines():
                if 'SessionData' in line and 'StatusSeries' not in line:
                    continue
                outfile.write(line+'\n')

**Comment by FMPete** [comment]
You are absolutely amazing! How much time you must be putting down right now! The little preprocessing above isn't much or difficult and I had almost already done it (race interrupted my efforts) but just shows your passion. Thank you! I'm happy to help, though not a programmer really. Just my weird interest for F1 and Football has made me learn some essentials.
