### ISSUE TITLE
[BUG] <pip installation error>

### ISSUE THREAD

**Issue by ElectronicsDr** [theOehrly/Fast-F1#187]
### Describe the issue:

First, thanks team for developing such a Formula 1 API. Then I tried installing it using the pip technique but there seems to be an error as attached. "Could not find matching distributions"

![image](https://user-images.githubusercontent.com/61284769/172045630-589c2d5e-a0fa-4542-86e6-91f7df4ea8f0.png)

### Reproduce the code example:

```python
python -m pip install fastf1
```

### Error message:

```shell
ERROR: Could not find a version that satisfies the requirement fastf1 (from versions: none)
ERROR: No matching distribution found for fastf1
```

**Comment by theOehrly** [comment]
Which python version are you using? You can use the command `python --version` to check.
