### ISSUE TITLE
[BUG] Pick_Fastest() not picking full lap Verstappen Canada Q

### ISSUE THREAD

**Issue by foxyskippy** [theOehrly/Fast-F1#195]
### Describe the issue:

Hi,

Trying to see how much Sainz lost comparing to Verstappen in Qualify of the Canadian GP, but somehow the fastest lap of Verstappen isn't complete
![Compare VER with SAI](https://user-images.githubusercontent.com/20426173/174486172-435854cc-1efc-4b76-9e4e-45b2fd0ebb4e.png)

What could be done to get the correct fastest lap?

### Reproduce the code example:

```python
import fastf1 as ff1
from fastf1 import plotting
from fastf1 import utils
from matplotlib import pyplot as plt
import pandas as pd

plotting.setup_mpl()

session = ff1.get_session(2022, 9, 'Q')
session.load_laps(with_telemetry=True)
drv1 = session.laps.pick_driver('VER').pick_fastest()
drv2 = session.laps.pick_driver('SAI').pick_fastest()

delta_time, ref_tel, compare_tel = utils.delta_time(drv2, drv1)

fig, ax = plt.subplots()

ax.plot(ref_tel['Distance'], ref_tel['Speed'],
        color=plotting.team_color(drv2['Team']))
ax.plot(compare_tel['Distance'], compare_tel['Speed'],
        color=plotting.team_color(drv1['Team']))

twin = ax.twinx()
twin.plot(ref_tel['Distance'], delta_time, '--', color='white')
twin.set_ylabel("<-- VER ahead | SAI ahead -->")
plt.show()
```

**Comment by rajuptvs** [comment]
Hi @foxyskippy , I tried to replicate the issue thee above mentioned error using the given code. Everything ran fine on my end. Can you please check again and let me know if you still face the issue.

Please find my plot below

![session](https://user-images.githubusercontent.com/48201939/174947826-5aae6754-95fe-4a6a-a56a-ec090d99850c.jpg)

**Comment by foxyskippy** [comment]
Hi @rajuptvs thanks for coming back to me. Still the same issue... This is the feedback I got.

`api         WARNING 	

NO CACHE! Api caching has not been enabled! 
	It is highly recommended to enable this feature for much faster data loading!
	Use `fastf1.Cache.enable_cache('path/to/cache/')`


Warning (from warnings module):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fastf1\core.py", line 1093
    warnings.warn("`Session.load_laps` is deprecated and will be"
FutureWarning: `Session.load_laps` is deprecated and will beremoved in a future version.
Use `Session.load` instead.
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v2.2.0-alpha1]
api            INFO 	Fetching driver list...
api            INFO 	Fetching timing data...
api            INFO 	Parsing timing data...
api            INFO 	Fetching timing app data...
core           INFO 	Processing timing data...
api            INFO 	Fetching session status data...
api            INFO 	Fetching track status data...
api            INFO 	Fetching car data...
api            INFO 	Parsing car data...
api            INFO 	Fetching position data...
api            INFO 	Parsing position data...
api            INFO 	Fetching weather data...
core           INFO 	Finished loading data for 20 drivers: ['14', '55', '44', '20', '47', '31', '63', '3', '24', '77', '23', '11', '4', '16', '10', '5', '18', '6', '22', '1']`

**Comment by rajuptvs** [comment]
@foxyskippy  the above is just a warning and as you said is a feedback, but the only thing that I noticed from my system to yours is the version of "fastf1" as shown below


Loading data for Canadian Grand Prix - Qualifying **[v2.2.0-alpha1]**
Loading data for Canadian Grand Prix - Qualifying **[v2.2.8]**

Can you please try to upgrade the package to the latest version and see if the code works and let me know.

**Comment by foxyskippy** [comment]
Thanks for your help @rajuptvs
