### ISSUE TITLE
[BUG] get_session gets data for an event that did not happen.

### ISSUE THREAD

**Issue by Pferdow30** [theOehrly/Fast-F1#196]
### Describe the issue:

Retrieve an event even if it does not exist. The issue seems to be due to the fuzzy match. The race in Montreal/Canada did not hold in 2021 (it was cancelled), however, the api pulls the data instead for the race in Montmeló/Spain.

### Reproduce the code example:

```python
import fastf1

session = fastf1.get_session(2021, 'Montreal', 'R')
session.load()
print(sess.event)
```

### Error message:

```shell
RoundNumber                                                    4
Country                                                    Spain
Location                                                Montmeló
OfficialEventName    FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2021
EventDate                                    2021-05-09 00:00:00
EventName                                     Spanish Grand Prix
EventFormat                                         conventional
Session1                                              Practice 1
Session1Date                                 2021-05-07 00:00:00
Session2                                              Practice 2
Session2Date                                 2021-05-07 00:00:00
Session3                                              Practice 3
Session3Date                                 2021-05-08 00:00:00
Session4                                              Qualifying
Session4Date                                 2021-05-08 00:00:00
Session5                                                    Race
Session5Date                                 2021-05-09 00:00:00
F1ApiSupport                                                True
Name: Spanish Grand Prix, dtype: object
```

**Comment by harish5p** [comment]
In the API, they use a fuzzy search to match the Race. 'Montreal' is probably closer to 'Montmeló' in that search ranking. You could user Race Number instead. For example, if you want to get the Bahrain GP race data for 2022

`import fastf1

session = fastf1.get_session(2022, 1, 'R')
session.load()
print(sess.event)`

**Comment by theOehrly** [comment]
Yeah, that's a bit of an issue with the Fuzzy matching. There's a few parameters that can be tuned here, but if I set them too strict, you might get no match when you should have a match. This is one of the reasons why FastF1 always prints the event name of the event that is actually loaded.

Would you have expected to get an error?

**Comment by theOehrly** [comment]
@Neron-png has added an optional strict search parameter in #285. I think this is the closes that we will get to a solution for this problem. It requires you to know the exact race name, but it will only return exact matches then. I'll consider this fixed and will close this issue.
