### ISSUE TITLE
FP1 British 2020 don't work

### ISSUE THREAD

**Issue by TerminatorPlati** [theOehrly/Fast-F1#2]
`Traceback (most recent call last):
  File "main.py", line 22, in <module>
    giri = sess.load_laps()
  File "/home/**/.local/lib/python3.8/site-packages/fastf1/utils.py", line 61, in decorator
    return func(*args, **kwargs)
  File "/home/**/.local/lib/python3.8/site-packages/fastf1/core.py", line 252, in load_laps
    self.laps = Laps(self._load_summary())
  File "/home/**/.local/lib/python3.8/site-packages/fastf1/core.py", line 324, in _load_summary
    t_map = {r['number']: r['Constructor']['name'] for r in self.results}
AttributeError: 'Session' object has no attribute 'results'
`

**Comment by Bettiol** [comment]
Also FP2. Same erros

**Comment by TerminatorPlati** [comment]
Also FP2. Same Error

**Comment by theOehrly** [comment]
Should be fixed. 

This was nothing specific to these sessions. There's just another api call (to ergast) but that one will fail if you're asking for a session too soon after it ended. (seems the data there is only available after the weekend). The missing data was not handled correctly.

**Comment by TerminatorPlati** [comment]
Top. All work fine.

I have a question. how do I make a Box Plot with the lapTime of a race?
