### ISSUE TITLE
Unable to get telemetry data from quali and race of Bahrain GP. (Worked well in Free practice sessions)

### ISSUE THREAD

**Issue by ricky732** [theOehrly/Fast-F1#20]
![code](https://user-images.githubusercontent.com/46622560/114041237-a669f900-9884-11eb-8566-932c4f462494.png)
![error](https://user-images.githubusercontent.com/46622560/114041258-abc74380-9884-11eb-9837-352d79f9783e.png)

The library worked well in FP1, FP2 and FP3 recording sessions and than analyzing them. In Quali and race I got this error, but the code and the method I used are the same!! So strange. I updated to 2.1.4 today but I still have the same problem...

**Comment by theOehrly** [comment]
This is know. See #18 for a workaround.

This will be fixed with the next release

**Comment by ricky732** [comment]
Aaaah true!!!! Didn't notice it, sorry. Should I close this issue?

**Comment by theOehrly** [comment]
No worries. And I'll close this issue once it's actually fixed in a release.
