### ISSUE TITLE
Questions and Answers about Imola friday

### ISSUE THREAD

**Issue by ricky732** [theOehrly/Fast-F1#21]
For 3 times every 3 minutes, when I am recording fp1 data, cmd tells me 'received no data for more than 60 seconds, exiting'. I don't know, my connection seems stable, but maybe this is the problem and I am wrong... Anyway the file it saved is not txt but it's a file that windows doesn't recognize. Is it normal? And HOW to downgrade to 2.1.4 if I get the same problem in FP2????

**Comment by theOehrly** [comment]
I cannot reproduce this problem currently. The recording is running just fine for me. Is there any more information in the log?

The file type is always a text file. If windows doesn't recognize it, you haven't added .txt to the file name you provided in the command.

    python -m fastf1.livetiming save test.txt



If you still think that downgrading may help (I can't see how it would, there were no notable changes to the client):

    pip uninstall fastf1
    pip install fastf1==2.1.4

**Comment by ricky732** [comment]
Now it's working, but I didn't add .txt... Will it read the file or should I restart record?

**Comment by theOehrly** [comment]
You don't need to add it. That's just so windows would recognize it automatically. Python doesn't care. And you can still open it with a text editor.
Renaming it to .txt after the recording has finished is also possible if you want that for convenience.

**Comment by ricky732** [comment]
Anyway for tomorrow I need to modify the 60 seconds to more. What is the code to do it?

**Comment by ricky732** [comment]
It seems working fine now, I think the problem was my connection, sorry... If for today it works, than you can close the issue.

**Comment by ricky732** [comment]
![errore](https://user-images.githubusercontent.com/46622560/115011304-c87c0080-9eae-11eb-87b7-8cf1a9a647c0.jpg)

Now trying to see the speed graphic it gives me this error...

**Comment by theOehrly** [comment]
You can look up how to increase the timeout in the documentation. The command line tool also shows you usage information.

In the image above you are loading some sort of Brazilian GP?! Is that intentional?

Apart from that, there is currently no live timing data available for download. The live timing replay in the official app is not (yet) working either. So it's something with their servers. Meaning you currently can't get data for this session if you don't have it recorded.

**Comment by ricky732** [comment]
No it's not intentional... What am I doing wrong in the code?? I recorded live timing from fp1 of Imola, it should work...
![imola](https://user-images.githubusercontent.com/46622560/115015270-af298300-9eb3-11eb-990b-28c51e5ab491.png)

**Comment by ricky732** [comment]
I started recording after about 20 minutes that the session started for that problem.. Is that the error??

**Comment by theOehrly** [comment]
No, I see the problem. The official name is "Emilia Romagna Grand Prix". Your "Emilian Grand Prix" is closer to "Brazilian Grand Prix" when the code is doing a fuzzy string match. 

You might want to use the event number instead of the name, i.e.

    ff1.get_session(2021, 2, 'FP2')

**Comment by ricky732** [comment]
Did it, this time the folder created in cache is correct (Emilia Romagna Grand Prix), but the error is the same... It saves only these 3 files and than gives me error. I think for some reasons the recording could be corrupted. Do you have the recording of FP1 of this morning?
![Immagine](https://user-images.githubusercontent.com/46622560/115016350-36c3c180-9eb5-11eb-9b50-e2fcbb833b26.png)

**Comment by JM-Monteiro** [comment]
I've also encountered an error while trying to load the telemetry for this session. I was trying to use the load_telemetry function with data that i recorded. I also tried the load_laps function and the same error mentioned above showed up. 
Below is the error for load_telemetry. 

![Screenshot 2021-04-16 at 12 29 57](https://user-images.githubusercontent.com/22205561/115018528-dda55f00-9eaf-11eb-86a4-70afe48804c8.png)

**Comment by theOehrly** [comment]
@ricky732 No, it's not your recording that's the problem here. There's some missing data (mainly tire information) which apparently wasn't available for this session. (I read some comments about how this data was also missing in the official app)
The code is not capable to deal with this. Let's just hope it works in FP2.

@JM-Monteiro Telemetry data cannot be loaded if the lap data hasn't been loaded yet. That's probably not entirely obvious from the documentation. Sorry for that. 
Because of the the problem with the missing data above, you will not be able to load this data.

**Comment by JM-Monteiro** [comment]
Thanks for the quick reply! 😀

**Comment by harningle** [comment]
Same error here. Will try FP2 later

**Comment by ricky732** [comment]
Question: If for example instead of taking fastest lap of a driver I would like to take a lap that was deleted due to track-limits, what should I do in the code?

**Comment by ricky732** [comment]
Anyway for me FP2 works fine. What a pity I can't know what Leclerc lap it considers as fastest. That one which was deleted or that official one?

**Comment by JM-Monteiro** [comment]
Hey @ricky732, my data for some reason got corrupted. Could you post the file you have recorded for FP2?
Thanks in advance!

**Comment by ricky732** [comment]
[im_fp2.txt](https://github.com/theOehrly/Fast-F1/files/6326330/im_fp2.txt)
here it is. @JM-Monteiro

**Comment by ricky732** [comment]
![Immagine](https://user-images.githubusercontent.com/46622560/115060086-ba96a180-9ee7-11eb-804d-584be0e1542f.png)
So guys, I just made this unic script for all the data. @theOehrly , it works very well and I am very happy with that, but the different graphics are showed everytime I close one. Is there a way to show all of them in the same time??

**Comment by theOehrly** [comment]
Ok, so some more general info about FP1 again. The recordings from FP1 are missing everything but lap times as far as I can tell now. As there were major technical issues at the track in FP1 (TV feed not working properly, radios not working, driver tracker not working) I'll attribute the problems to this. I won't try to work around this to make whatever remains of the data usable with this package.


Deleted laps are most likely included in the data. So if the fastest lap is a deleted lap it will be returned as the result of `.get_fastest()`. I'm not even sure if the raw api data provides information on deleted laps. 
You'll have to manually compare the lap time to the official session results to be sure. I'll see what can be done about this in the future.
Methods like `.pick_driver()` return an instance of the `Laps` object. This is a subclass of pandas `DataFrame`. This means you can just use the usual pandas methods to sort the data by lap time and get the second fastest lap then (or do some other sorting/slicing/filtering/...).


@ricky732 regarding your code above, you only need to call `plt.show` once at the end. But that a generic matplotlib question tbh.

**Comment by ricky732** [comment]
Fantastic, thank you!! I know I could make stupid questions sometimes, I am good at pc but I don't have much experience in programmating. I'll read the guide for lap times because I have not clear how should I see all the lap times of a driver and than tell the program what to chose for telemetry data. If it's an easy code and you could explain me, it would be very appreciated and good ❤️ Thanks for everything @theOehrly

**Comment by theOehrly** [comment]
Ok, some very quick examples here. I'd say, just play around with it in an interactive session for a bit. 
And take a look a some basic examples on how to work with pandas.

```
print(laps)
                      Time DriverNumber  ... TrackStatus  IsAccurate
0   0 days 00:33:33.656000            3  ...           1       False
1   0 days 00:34:51.559000            3  ...           1        True
2   0 days 00:36:26.232000            3  ...           1        True
3   0 days 00:37:43.530000            3  ...           1        True
4   0 days 00:39:28.246000            3  ...           1        True
..                     ...          ...  ...         ...         ...
389 0 days 01:13:19.737000           99  ...           1        True
390 0 days 01:14:39.536000           99  ...           1        True
391 0 days 01:15:58.973000           99  ...           1        True
392 0 days 01:17:57.772000           99  ...           1        True
393 0 days 01:20:04.437000           99  ...           1       False
[394 rows x 25 columns]


lec = laps.pick_driver('LEC')
print(lec)
                      Time DriverNumber  ... TrackStatus  IsAccurate
174 0 days 00:30:44.600000           16  ...           1       False
175 0 days 00:32:01.921000           16  ...           1        True
176 0 days 00:33:43.753000           16  ...           1        True
177 0 days 00:35:00.548000           16  ...           1        True
178 0 days 00:36:42.589000           16  ...           1        True
179 0 days 00:38:15.489000           16  ...           1        True
180 0 days 00:39:31.821000           16  ...           1        True
181 0 days 00:53:00.277000           16  ...          25       False
182 0 days 00:54:35.776000           16  ...           1       False
183 0 days 00:55:51.514000           16  ...           1        True
184 0 days 00:57:57.001000           16  ...           1        True
185 0 days 00:59:22.528000           16  ...           1        True
186 0 days 01:00:38.372000           16  ...           1        True
187 0 days 01:02:28.154000           16  ...           1       False
188 0 days 01:04:51.418000           16  ...           2       False
189 0 days 01:11:06.092000           16  ...           2       False
190 0 days 01:12:54.647000           16  ...           1       False
191 0 days 01:14:14.567000           16  ...           1        True
192 0 days 01:15:34.124000           16  ...           1        True
193 0 days 01:17:25.866000           16  ...           1        True
194 0 days 01:19:40.125000           16  ...           1       False
[21 rows x 25 columns]


print(lec['LapTime'])
174                      NaT
175   0 days 00:01:17.321000
176   0 days 00:01:41.832000
177   0 days 00:01:16.795000
178   0 days 00:01:42.041000
179   0 days 00:01:32.900000
180   0 days 00:01:16.332000
181                      NaT
182                      NaT
183   0 days 00:01:15.738000
184   0 days 00:02:05.487000
185   0 days 00:01:25.527000
186   0 days 00:01:15.844000
187   0 days 00:01:49.782000
188   0 days 00:02:23.264000
189                      NaT
190   0 days 00:01:48.555000
191   0 days 00:01:19.920000
192   0 days 00:01:19.557000
193   0 days 00:01:51.742000
194   0 days 00:02:14.259000
Name: LapTime, dtype: timedelta64[ns]


lec_sorted = lec.sort_values(by='LapTime')
print(lec_sorted['LapTime'])

183   0 days 00:01:15.738000
186   0 days 00:01:15.844000
180   0 days 00:01:16.332000
177   0 days 00:01:16.795000
175   0 days 00:01:17.321000
192   0 days 00:01:19.557000
191   0 days 00:01:19.920000
185   0 days 00:01:25.527000
179   0 days 00:01:32.900000
176   0 days 00:01:41.832000
178   0 days 00:01:42.041000
190   0 days 00:01:48.555000
187   0 days 00:01:49.782000
193   0 days 00:01:51.742000
184   0 days 00:02:05.487000
194   0 days 00:02:14.259000
188   0 days 00:02:23.264000
174                      NaT
181                      NaT
182                      NaT
189                      NaT
Name: LapTime, dtype: timedelta64[ns]


second_fastest = lec_sorted.iloc[1]
print(second_fastest)

Time                  0 days 01:00:38.372000
DriverNumber                              16
LapTime               0 days 00:01:15.844000
LapNumber                                 13
Stint                                      2
PitOutTime                               NaT
PitInTime                                NaT
Sector1Time           0 days 00:00:24.359000
Sector2Time           0 days 00:00:26.269000
Sector3Time           0 days 00:00:25.216000
Sector1SessionTime    0 days 00:59:46.887000
Sector2SessionTime    0 days 01:00:13.156000
Sector3SessionTime    0 days 01:00:38.372000
SpeedI1                                233.0
SpeedI2                                258.0
SpeedFL                                282.0
SpeedST                                287.0
Compound                                SOFT
TyreLife                                 6.0
FreshTyre                               True
LapStartTime          0 days 00:59:22.528000
Team                                 Ferrari
Driver                                   LEC
TrackStatus                                1
IsAccurate                              True
Name: 186, dtype: object
```

**Comment by ricky732** [comment]
Clear! After this, could you tell me how to use a specific lap for telemetry comparison? I mean, instead of pick_fastest(), what should I write? pick_second for example?

**Comment by ricky732** [comment]
I think I've done it! Amazing!!! Just playing a bit with the code, it's great! I can select every lap now! I have throttle, speed, speed+delta, brake, gearbox and rpm. What is missing guys? What are other possible things maybe I have missed?

**Comment by FMPete** [comment]
I was sure there was a "_pick_lap()_" but I cannot seem to find it anymore. But please check https://theoehrly.github.io/Fast-F1/core.html for all info on what is available. 

On a sidenote remeber that some plots are usually read in a specific way so the line of 
_plt.gca().invert_yaxis()_ 
could come in handy.

**Comment by theOehrly** [comment]
I don't think there ever was something like '_pick_lap()_'. But as the data is a DataFrame you could just do something like 
`lap3 = laps[laps['LapNumber'] == 3]` for a specific lap number
and of course the already mentioned
`lap = laps.iloc[2]` if sort your laps by some metric and then select by index.

**Comment by harningle** [comment]
The FP1 Highlights in their youtube channel explicitly mentioned the FP1 data issue

**Comment by ricky732** [comment]
![throttle](https://user-images.githubusercontent.com/46622560/115197582-6ced8500-a0f1-11eb-8a69-f8a1747b3ef6.png)
@theOehrly , I did exactly in the second way!!! But now I noted this in the Ferrari throttle graphic... In the straights it's not all the time flat out, while the mercedes one is right. How to solve this problem???

**Comment by ricky732** [comment]
![smooth](https://user-images.githubusercontent.com/46622560/115200487-9360ef80-a0f4-11eb-8c73-69f29b604126.png)
By the way guys, I worked on a smoothing for Speed curve. What do you think about the result? Left smoothed, right not smoothed. @theOehrly told that every smooth misses details on the curve, but I don't see so many missing details...

**Comment by theOehrly** [comment]
That jitter of the Ferrari throttle very much looks like an issue with the raw data. I guess if you need to remove it you'll have to do it "manually" in some way. Maybe just apply some threshold and set all values that are greater than 98 to 100. 
It think something like this might work.

    car_data = lap.get_car_data()
    throttle = car_data['Throttle'].copy()
    throttle.loc[throttle > 98] = 100

There's nothing universal that can be done against something like that. If there's something that looks like an error with the raw data, and you want to remove it, you'll likely have to deal with it differently each time.

The smoothing doesn't look to bad. But it's still losing a bit of detail. I guess whether that's acceptable or not depends on what you want to analyze.

**Comment by ricky732** [comment]
Thank you!!! You should think doing a smoothing only for interested parts without touching entering, minimum speed, and exiting of the corners. I was trying but for me it's not so easy...
