### ISSUE TITLE
get_pos_data() inconsistent logic with get_car_data()?

### ISSUE THREAD

**Issue by surey0** [theOehrly/Fast-F1#22]
Dunno if I'm trying to do something I shouldn't; very new to this (and to Python).  Noticed official timing app seems to be getting the telemetry data once again so I tried to see if telemetry would work again...
```
import fastf1 as ff1
ff1.Cache.enable_cache('/a/local/directory/i/have')  # pointed to a local dir
race = ff1.get_session(2021, 1, 'R')
lap = race.load_laps(True,) # to get telemetry with this

ham = lap.pick_driver('HAM')
# test code
tlm = get_telemetry() 
```
I got the following error:
```
Traceback (most recent call last):

  File "<ipython-input-6-182498178710>", line 1, in <module>
    tlm = ham.get_telemetry()

  File "\site-packages\fastf1\core.py", line 1524, in get_telemetry
    pos_data = self.get_pos_data(pad=1, pad_side='both')

  File "\site-packages\fastf1\core.py", line 1573, in get_pos_data
    pos_data = self.session.pos_data[self['DriverNumber']].slice_by_lap(self, **kwargs).reset_index(drop=True)

  File "\lib\site-packages\pandas\core\generic.py", line 1785, in __hash__
    raise TypeError(

TypeError: 'Lap' objects are mutable, thus they cannot be hashed
```

I wonder if there's an issue in the `get_pos_data()` since it seems to call `['DriverNumber']` instead of the actual `drv_num`.  Compare the following lines
[from `get_pos_data`](https://github.com/theOehrly/Fast-F1/blob/712cb80a2f050bb0a1cece261d80419c88c7303f/fastf1/core.py#L1573)
[from `get_car_data`](https://github.com/theOehrly/Fast-F1/blob/712cb80a2f050bb0a1cece261d80419c88c7303f/fastf1/core.py#L1552)

**Comment by theOehrly** [comment]
Yes, you are absolutely right, that's a bug. It should be `drv_num` there. I'll have to fix that.

This problem doesn't occur for single laps, only for multiple laps. So if you can select single laps first and then call `get_telemetry` everything should be fine. 
Or you can of course copy the few lines of code involved in `get_telemetry()` and do it in your code until the next release.

**Comment by surey0** [comment]
Sorry took so long for me to close this.  have been away for a week or so.  Cheers!

**Comment by theOehrly** [comment]
Should be fixed in the latest release now
