### ISSUE TITLE
[ENH] Default cache location `~/.fastf1`

### ISSUE THREAD

**Issue by oscr** [theOehrly/Fast-F1#234]
### Proposed new feature or change:

I would like to suggest changing the cache behavior from the current warning about not using caching:

```
>>> import fastf1
>>> session = fastf1.get_session(2020, 13, 'FP1')
api         WARNING 	

NO CACHE! Api caching has not been enabled! 
	It is highly recommended to enable this feature for much faster data loading!
	Use `fastf1.Cache.enable_cache('path/to/cache/')`
```

To instead using a default caching location `~/.fastf1` or on Linux `~/.cache/fastf1`. 

I think for most users this will be more convenient, it doesn't take much space, it will save network traffic and since the data doesn't get stale there isn't any major downside to it. For advanced users who want to change the caching directory it would work the same as today. They just have to set the caching directory.

**Comment by theOehrly** [comment]
I don't agree with it not taking much space. And that's the main reason that there is no default cache directory. You easily get into the hundreds of megabytes. I just checked, and the cache directory on my machine is around 3 GB. And I don't even load the majority of sessions. I don't really like the idea of littering that amount of data somewhere without the user knowing.

**Comment by oscr** [comment]
If it's a question of informing the user, how would you feel about changing the "NO CACHE!" message to a ~"Using default cache ~/.fastf1"? Then it's very clear data is being stored. We could even add `os.path.getsize()`

I personally think this would be more convenient than setting the Cache every time you import fastf1, it saves network for the user and apis that are called. 3 GB is 0.3% of my (default equipped) laptops storage and I kind of expect a data analysis tool to store data. So I would be ok with much more.

**Comment by theOehrly** [comment]
Yes, perhaps it is OK if users are informed about the location. And the size of the cache directory really should be included. It's not immediately obvious that the data will take up as much space as it does. 
If something like this is added, it's probably worth considering adding support for setting the cache path through an environment variable as well.

I'm still not entirely convinced, although I see how this will improve usability. It's not that long ago that I myself did absolutely not have a few hundred megabytes of free space on my system drive. In my mind, this is still a lot of data to just store "somewhere". What I especially don't like is that the data cannot automatically be removed when FastF1 is uninstalled. It'll just stick around and likely be forgotten. Pip does not provide any mechanism for that.

**Comment by oscr** [comment]
At least Linux (and I assume macOS and Windows) has some options for cache data:  

* [/var/cache](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s05.html)
* [~/.cache](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

The default location could be in one of these. That would allow users to discover and recover the space. As a side note my current `~/.cache` folder is 9,5G and it looks like `pip`, `yarn` etc are storing things there. So maybe copy where `pip` stores the data would be viable?

**Comment by oscr** [comment]
More information about where pip stores data: https://stackoverflow.com/questions/34578168/where-is-pip-cache-folder

**Comment by theOehrly** [comment]
Ok, I think it is fine if we use existing os specific application cache folders.

Linux: either `/var/cache` or `$XDG_CACHE_HOME` although I'm not sure which one should be preferred.

Windows: `%LOCALAPPDATA%/Temp` should be the right place. The built-in disk cleanup utility removes unused files from there.

MacOS: `~/Library/Caches` seems to be the right place.

**Comment by theOehrly** [comment]
I don't have the capacity to get this done for the next release right away. So for now, I've pushed it back to the next major release, which will likely be no earlier than the winter break. If there is another minor release during this season, I might pull it forward to that release.

**Comment by oscr** [comment]
That sounds good to me since it's not that urgent. I might make a draft for this if I get some time over in the coming weeks. Hopefully I can make some progress and leave you with more time for other things.

**Comment by oscr** [comment]
Implemented! Therefore closing
