### ISSUE TITLE
[BUG] Deprecated functions used in documentation

### ISSUE THREAD

**Issue by oscr** [theOehrly/Fast-F1#247]
### Describe the issue:

Running the usage example here:
https://github.com/theOehrly/Fast-F1/blob/88f404474315c71e02c96f5372d5d744148440db/fastf1/livetiming/__init__.py#L40

Will give a DeprecationWarning

### Reproduce the code example:

```python
Run above.
```

### Error message:

```shell
session = fastf1.get_session(2021, 'testing', 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oscar/repo/github/fast-f1/fastf1/events.py", line 262, in get_session
    raise DeprecationWarning('Accessing test sessions through '
DeprecationWarning: Accessing test sessions through `get_session` has been deprecated!
Use `get_testing_session` instead.
```
```

**Comment by theOehrly** [comment]
Yep, there's another one somewhere, I think with a function that got deprecated with v2.3 now. I likely won't get around to fixing minor issues like this before the end of September, though.

**Comment by oscr** [comment]
No worries about time etc! I just created the issue to make it easier to find and coordinate fixing it.
