### ISSUE TITLE
[ENH] Extra telemetry/data feeds available

### ISSUE THREAD

**Issue by f1multiviewer** [theOehrly/Fast-F1#248]
### Proposed new feature or change:

While developing [MultiViewer for F1](https://beta.f1mv.com/) I've discovered a few endpoints that are currently not used, and wanted to share in case you want to implement them in your library.

- `DriverScore` the driver scores for G-forces, throttle, steering and braking (more about it here: https://www.formula1.com/en/latest/features/2015/4/race-performance-ratings-explained---aggression.html)
- `LapSeries` (maybe not as useful as this is already data that is available elsewhere)
- `PitLaneTimeCollection` Not super precise, but single-decimal precision pit stop durations

... and more

You may also be able to use `https://livetiming.formula1.com/static/2022/Index.json` instead of relying on "guessing" the path etc., and there's also `/Index.json` endpoints for all seasons (`/static/Index.json`) and for each session `/static/:season/:meeting/:session/Index.json`.

Hope this helps!

<details>
<summary>Full list of data feeds</summary>

```json
{
  "Feeds": {
    "SessionInfo": {
      "KeyFramePath": "SessionInfo.json",
      "StreamPath": "SessionInfo.jsonStream"
    },
    "ArchiveStatus": {
      "KeyFramePath": "ArchiveStatus.json",
      "StreamPath": "ArchiveStatus.jsonStream"
    },
    "TrackStatus": {
      "KeyFramePath": "TrackStatus.json",
      "StreamPath": "TrackStatus.jsonStream"
    },
    "SessionData": {
      "KeyFramePath": "SessionData.json",
      "StreamPath": "SessionData.jsonStream"
    },
    "ContentStreams": {
      "KeyFramePath": "ContentStreams.json",
      "StreamPath": "ContentStreams.jsonStream"
    },
    "ChampionshipPrediction": {
      "KeyFramePath": "ChampionshipPrediction.json",
      "StreamPath": "ChampionshipPrediction.jsonStream"
    },
    "AudioStreams": {
      "KeyFramePath": "AudioStreams.json",
      "StreamPath": "AudioStreams.jsonStream"
    },
    "DriverList": {
      "KeyFramePath": "DriverList.json",
      "StreamPath": "DriverList.jsonStream"
    },
    "TimingDataF1": {
      "KeyFramePath": "TimingDataF1.json",
      "StreamPath": "TimingDataF1.jsonStream"
    },
    "SPFeed": {
      "KeyFramePath": "SPFeed.json",
      "StreamPath": "SPFeed.jsonStream"
    },
    "LapSeries": {
      "KeyFramePath": "LapSeries.json",
      "StreamPath": "LapSeries.jsonStream"
    },
    "TimingAppData": {
      "KeyFramePath": "TimingAppData.json",
      "StreamPath": "TimingAppData.jsonStream"
    },
    "TimingData": {
      "KeyFramePath": "TimingData.json",
      "StreamPath": "TimingData.jsonStream"
    },
    "TopThree": {
      "KeyFramePath": "TopThree.json",
      "StreamPath": "TopThree.jsonStream"
    },
    "TimingStats": {
      "KeyFramePath": "TimingStats.json",
      "StreamPath": "TimingStats.jsonStream"
    },
    "ExtrapolatedClock": {
      "KeyFramePath": "ExtrapolatedClock.json",
      "StreamPath": "ExtrapolatedClock.jsonStream"
    },
    "CarData.z": {
      "KeyFramePath": "CarData.z.json",
      "StreamPath": "CarData.z.jsonStream"
    },
    "Position.z": {
      "KeyFramePath": "Position.z.json",
      "StreamPath": "Position.z.jsonStream"
    },
    "SessionStatus": {
      "KeyFramePath": "SessionStatus.json",
      "StreamPath": "SessionStatus.jsonStream"
    },
    "TyreStintSeries": {
      "KeyFramePath": "TyreStintSeries.json",
      "StreamPath": "TyreStintSeries.jsonStream"
    },
    "DriverRaceInfo": {
      "KeyFramePath": "DriverRaceInfo.json",
      "StreamPath": "DriverRaceInfo.jsonStream"
    },
    "LapCount": {
      "KeyFramePath": "LapCount.json",
      "StreamPath": "LapCount.jsonStream"
    },
    "Heartbeat": {
      "KeyFramePath": "Heartbeat.json",
      "StreamPath": "Heartbeat.jsonStream"
    },
    "WeatherData": {
      "KeyFramePath": "WeatherData.json",
      "StreamPath": "WeatherData.jsonStream"
    },
    "WeatherDataSeries": {
      "KeyFramePath": "WeatherDataSeries.json",
      "StreamPath": "WeatherDataSeries.jsonStream"
    },
    "TeamRadio": {
      "KeyFramePath": "TeamRadio.json",
      "StreamPath": "TeamRadio.jsonStream"
    },
    "TlaRcm": {
      "KeyFramePath": "TlaRcm.json",
      "StreamPath": "TlaRcm.jsonStream"
    },
    "RaceControlMessages": {
      "KeyFramePath": "RaceControlMessages.json",
      "StreamPath": "RaceControlMessages.jsonStream"
    },
    "CurrentTyres": {
      "KeyFramePath": "CurrentTyres.json",
      "StreamPath": "CurrentTyres.jsonStream"
    },
    "DriverScore": {
      "KeyFramePath": "DriverScore.json",
      "StreamPath": "DriverScore.jsonStream"
    },
    "PitLaneTimeCollection": {
      "KeyFramePath": "PitLaneTimeCollection.json",
      "StreamPath": "PitLaneTimeCollection.jsonStream"
    }
  }
}
```
</details>

**Comment by siddharth-tewari** [comment]
It's awesome to know these many more. Will help in my future applications.

**Comment by hash55** [comment]
Nice! I would say that the `PitLaneTimeCollection` is not 100% new since you can gather that data by substracting the `PitOutTime `and `PitInTime`, from `Laps`.
However, what I found really interesting is the GForces (Lateral and Longitudinal) that provide `SPfeed` and `DriverScore `endpoints. The bad thing is that it gets updated just every 15 sec...

**Comment by hash55** [comment]
oh yes you are right. So, there is no raw data of the actual G-forces?

**Comment by f1multiviewer** [comment]
> oh yes you are right. So, there is no raw data of the actual G-forces?

unfortunately, not that I've come across, but if I do, I'll share. I wish they did, because it shows up on the broadcast sometimes, and even has a directional element, too. It would be quite cool to show in MultiViewer (but also for y'all to analyse)

**Comment by theOehrly** [comment]
@f1multiviewer thank you very much for this information! This is awesome! I didn't know about these `Index.json` overview endpoints before. I wasn't quite "guessing" api paths, but somehow I missed these so far. This would have made some things so much easier. I need to take some time and look at what information there is and how I can best add this to FastF1.

**Comment by f1multiviewer** [comment]
> @f1multiviewer Could you please give an example of how to access, for instance, the Heartbeet stream?

You can use the index files to find the season/session you need, then build the URL like so:

`https://livetiming.formula1.com/static/:season/:meeting_handle/:session_handle/:topic.(json|jsonStream)`

Example:
`https://livetiming.formula1.com/static/2022/2022-07-31_Hungarian_Grand_Prix/2022-07-30_Qualifying/Heartbeat.jsonStream`

Though, this is not new, that's [already something Fast-F1 does](https://github.com/theOehrly/Fast-F1/blob/master/fastf1/api.py#L45-L77).

**Comment by TasosOperatingInBinary** [comment]
Yeah, I had searched in the code for where the requests are sent to but :meeting in the URL template of this issue confused me at the start, thanks anyways!

**Comment by eXhumer** [comment]
> You may also be able to use `https://livetiming.formula1.com/static/2022/Index.json` instead of relying on "guessing" the path etc., and there's also `/Index.json` endpoints for all seasons (`/static/Index.json`) and for each session `/static/:season/:meeting/:session/Index.json`.

I want to correct a slight bit of error here. It is not exactly true about each session having the Index.json. Index.json has been provided from 2018 US Grand Prix FP1 onwards. Any session before that (Start of the season to Japan GP Race) didn't have an Index.json with their respective paths.

* Link to Index.json for 2018 US GP FP1: https://livetiming.formula1.com/static/2018/2018-10-21_United_States_Grand_Prix/2018-10-19_Practice_1/Index.json
* Link to Index.json for 2018 Japan GP Race (404 Not Found): https://livetiming.formula1.com/static/2018/2018-10-07_Japanese_Grand_Prix/2018-10-07_Race/Index.json

**Comment by eXhumer** [comment]
Also, note that pre-season testing session information is not present Index.json, path for those still need to be "guessed".

**Comment by theOehrly** [comment]
@eXhumer thank you for that information. I guess some kind of combination of the index endpoints and the current schedule backend will be necessary to support all sessions.

**Comment by f1multiviewer** [comment]
@theOehrly I also have corner position/length (although I'm not sure how precise length is) available if this is useful. I have an API that I keep up to date, it currently has (or should have, if one is missing I'd love to hear) corner annotations for all circuits. I also have annotations for FIA marshal lights (and marshalling sectors are being added as we speak, some already have them). I've seen a previous issue https://github.com/theOehrly/Fast-F1/issues/19 but I'm not sure what the status is.

If this would be useful, lmk, I'll write some documentation (I can either send you the current data, or you can implement the API and get up-to-date information) on how to retrieve/interpret it.

**Comment by theOehrly** [comment]
@f1multiviewer That sounds very interesting and is something I'd like to add over the winter. I'd prefer using your API to get up-to-date information instead of working with an image of the data, if that's cool with you.
#19 hasn't made any further progress, altough @ukaoskid has added some more tracks to his data set. @f1multiviewer where do you get your data from? Do you create it all manually? If that's the case, maybe you can work together with @ukaoskid, as you say you're not sure how precise length is in your data. Maybe it is possible to create one fairly accurate database for this information?

**Comment by f1multiviewer** [comment]
> @f1multiviewer That sounds very interesting and is something I'd like to add over the winter. I'd prefer using your API to get up-to-date information instead of working with an image of the data, if that's cool with you. #19 hasn't made any further progress, altough @ukaoskid has added some more tracks to his data set. @f1multiviewer where do you get your data from? Do you create it all manually? If that's the case, maybe you can work together with @ukaoskid, as you say you're not sure how precise length is in your data. Maybe it is possible to create one fairly accurate database for this information?

Data is manually added by overlapping the official FIA maps with a custom map editor and matching the rotation & size. I'm sure it's correct enough for "marking" it. The length is calculated by measuring the SVG path's length, which seems to match well with distance travelled. I'd say for corner numbers, this is fine, for marshalling sectors, I'd add a big fat asterisks.

**Comment by theOehrly** [comment]
@f1multiviewer that sounds like quite a bit of manual work. It'd sure be nice to be able to use that data in FastF1 as well.

**Comment by f1multiviewer** [comment]
> @f1multiviewer that sounds like quite a bit of manual work. It'd sure be nice to be able to use that data in FastF1 as well.

Not nearly as much as some of the other stuff I've had to do to get MultiViewer where it is now haha, but I'll send over documentation later 💚

**Comment by theOehrly** [comment]
> > @f1multiviewer that sounds like quite a bit of manual work. It'd sure be nice to be able to use that data in FastF1 as well.
> 
> Not nearly as much as some of the other stuff I've had to do to get MultiViewer where it is now haha, but I'll send over documentation later 💚

Thank you. No need to hurry on your side. I will not get around to implementing that immediately. But I'd love to take a look at it, for sure.

(And I have to say, MultiViewer looks amazing! Now, if I could only get F1TV in Germany then I could even use it...)

**Comment by f1multiviewer** [comment]
> (And I have to say, MultiViewer looks amazing! Now, if I could only get F1TV in Germany then I could even use it...)

Check r/F1TV, I can't really help with it, but there's plenty of people there who have access from regions where it's unavailable.

**Comment by ukaoskid** [comment]
Hey everyone,

I did not abandon the project, it’s taking time to make it as much exact as
possible, and also I am slightly changing the dataset to allow multiple
versions of the same track (like layout changes over the time or different
versions of the same track, see Bahrein dual layout).

Any help would be appreciated. I will add a contribution file as soon as
today for better PRs

**Comment by ukaoskid** [comment]
Hey all,

@theOehrly @f1multiviewer I have added a `CONTRIBUTE.md` file if you guys want to give your contribution.

Thanks!

**Comment by f1multiviewer** [comment]
Sorry for the delay, here's a little explanation about the API, how to use it, the data and limitations:

## Basics
So to call the API for a circuit, you need the CircuitKey, you can find this for each session in `SessionInfo.Meeting.Circuit.Key`. There's already one exception here, where one session at Mugello is incorrectly miscategorised as `149`, but that's actually the circuit key for Jeddah. I've handled this in MultiViewer like so:

```ts
// NOTE: Mugello is miscategorised as 149 (which is Jeddah) in the API
const circuitKey =
  sessionInfo?.Meeting?.Circuit?.ShortName === "Mugello"
    ? "146"
    : sessionInfo?.Meeting?.Circuit?.Key?.toString(10);
```

Once you have the correct `CircuitKey`, you can call the API to get the circuit metadata like so:

```
GET /api/v1/circuits/2/2022 HTTP/1.1
Host: api.f1mv.com
```
```json5
{
  "corners": [
    {
      "angle": 98.4899241531774,
      "length": 4523.666100769043,
      "number": 1,
      "trackPosition": {
        "x": 1192.50830078125,
        "y": 4503.826171875
      }
    },
    // ...
  ],
  "marshalLights": [
    {
      "angle": 142.51867961329444,
      "length": 4.564748840332031,
      "number": 1,
      "trackPosition": {
        "x": -1754.1448974609375,
        "y": 1212.111572265625
      }
    },
    // ...
  ],
  "marshalSectors": [
    {
      "angle": 155.9148058729058,
      "length": 0,
      "number": 1,
      "trackPosition": {
        "x": -1756,
        "y": 1208
      }
    },
    // ...
  ],
  "circuitKey": 2,
  "circuitName": "Silverstone",
  "countryIocCode": "GBR",
  "countryKey": 2,
  "meetingKey": "1114",
  "rotation": 92,
  "year": 2022,
  // ... (omitted fields are not guaranteed to be available or may be removed in the future)
}
```

The `corners` array contains the corner data, which is the most important part of the API. The `marshalLights` and `marshalSectors` arrays contain the marshal data, which is used to display the marshal lights and marshal sectors on the map. The `rotation` field is the rotation of the circuit in degrees, which is used to rotate the map to the correct orientation (matching what FOM uses on the broadcast).

Corners, marshal lights and marshal sectors are all "track markers", each track marker follows the following type specification:

```ts
export interface ITrackMarker {
  /** The number of the marker */
  number: number;

  /**
   * If this marker number is referenced multiple times, the letter 
   * is used to differentiate them, such as corner 2A in Hungary.
   */
  letter?: string;

  /**
   * The coordinate of the marker on the track map, resolution is 
   * usually 10cm, but matches the resolution of the car position 
   * from the live timing telemetry.
   */
  trackPosition: DOMPoint | { x: number; y: number };

  /**
   * This is the angle in degrees, used to offset the marker's 
   * placement on a track map in a logical direction.
   */
  angle: number;

  /**
   * The approximate absolute length from the start of the track
   * to this marker, measured in SVG path length from all previous
   * track points.
   */
  length: number;
}
```

## Limitations
- **Length may be incorrect**: The length is calculated from the SVG path length, which is not always accurate. Sometimes, GPS position isn't accurate and will go forward and then backward before going forward again. The differences should be minimal, but your mileage may vary. To get the most precise length, I'd advise using the `trackPosition` value and calculating the length to the marker yourself. Given these are only meant to be used as visual markers for MultiViewer, this isn't a problem for me, but it may be for you.
- **Old track data**: I'm still working on a script to gather track data for all circuits myself. I'm currently borrowing data from another source to get the `x`, `y` data returned by the API (and some of the other data as well, but not the corner/marshal data). I'm not sure how precise this data is, but it works well for visual purposes. In the future, this data (and the object keys) may change. I'll communicate any changes here and on the Discord server, and will try to make sure there are no backwards compatible/breaking changes, those should be published under /v2 if there's a need for this.
- **API comes without warranty**: Basically the data is available free of charge, but without any warranties.
  > THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
- **User agent**: MultiViewer identifies itself when sending requests to the API. I'd appreciate if FastF1 does the same. Format can be something like: `fastf1/{version} platform/{platform}`, if you can't or don't want to send the platform, that's fine as well, you can omit it. If you expect that this API will be called frequently by a single user of FastF1 during normal use, I'd appreciate if you can add some caching system.

## Details
- I've manually mapped (using the circuit data also returned in the API, and circuit/media maps provided by the FIA, and a custom map editor) all corners, marshal lights and marshalling sectors.
- While I've paid great care to make sure the data is correct, there may be some errors. If you find any, please let me know and I'll fix them as soon as possible. I've also fixed some errors with respect to FIA maps, as for instance, in Singapore, the FIA map doesn't correctly show the marshal sectors (they are wrongly offset by 1). I'll continue to fix these inconsistencies as I find them.
- There's a minor bug in the angles for track markers, where it may show a negative number instead of a positive number. This may be fixed in the future.
- If you want, I can also provide you with the JSON files which contain the track markers. But you said before you prefer to implement the API, so that's fine with me as well.
- If you want, you can credit MultiViewer for F1 as a data source, but it's not a requirement

Happy to answer any questions if anything is unclear! And if you think there's improvements I could make, let me know as well. I'm happy to help out where I can.

Finally @ukaoskid I'd love to contribute, but I'm busier than ever. I'd be happy to provide the data that I've gathered so far, but you'd have to check/convert it yourself. Let me know if you're interested :)

**Comment by theOehrly** [comment]
@f1multiviewer wow, that is a lot of information. Thank you very much. I'll see when I'll get around to trying out your API. In any case, this will only get implemented for the next season. 

Regarding some of your notes about the interaction with the API:
- Sending a user agent `fastf1/{version}` is no problem at all. This is already done with Ergast right now. I'll see about maybe adding a platform specifier.
- FastF1 already uses caching for all API requests. Does your API server provide an HTTP cache-control header? If so, the specified max-age will be respected. That way, you would control how often the data is accessed by individual users. Else, I can manually specify how long the cache is valid.

I suppose more questions might come up when I work with the API.

And I would of course credit MultiViewer as the data source if I implement your API.

**Comment by f1multiviewer** [comment]
Hey @theOehrly! The API does expose cache-control headers, so it's good to know FastF1 respects them. I'm here in case you have any questions (or if you want, you can join the Discord server, link is on the website, if you prefer to chat)

**Comment by f1multiviewer** [comment]
I updated the domain name used for the API in the comment above, the old domain will continue working for the foreseeable future but best to use `api.multiviewer.app`

**Comment by theOehrly** [comment]
@f1multiviewer you made me aware of the season index API endpoints, so I assume you are likely making use of them?

When I use `https://livetiming.formula1.com/static/2023/Index.json` to get the schedule for the current season, all I get is information about events that have already taken place. That means, I cannot create a full event schedule for the current season from this endpoint. Am I missing something here, or does the API not provide information about future events?

Also, I'm really sorry that you took the time for creating such an extensive write-up of your API, but I still haven't got around to implementing it. Fingers crossed I'll get to it somewhere in the first half of this year.

**Comment by f1multiviewer** [comment]
Hey @theOehrly, no worries about that last part, I know how maintaining open-source projects can be, take all the time you need! 💚

Regarding the schedule for the current season, the index files are no use for that. They will contain the weekend schedule after the first session, but that's not really useful. Instead, you can use another F1 API for this:

```bash
# Get all events for a season
curl "https://api.formula1.com/v1/editorial-eventlisting/events?season=2023" \
     -H 'apikey: t3DrvCuXvjDX8nIvPpcSNTbB9kae1DPs' \
     -H 'locale: en'

# Get meeting data by meetingKey
curl "https://api.formula1.com/v1/event-tracker/meeting/1142" \
     -H 'apikey: t3DrvCuXvjDX8nIvPpcSNTbB9kae1DPs' \
     -H 'locale: en'
```

Where the first is used to retrieve basic information (including `meetingKey`) and the latter contains `sessionLinkSets.replayLinks` to get the replay paths. The API key used here is hard-coded in the iOS app.

Aside from that, I had one more question for you. Let's say I have a full URL to a session (not the livetiming.formula1.com hostname), is there any way to tell FastF1 to fetch it from there?

**Comment by theOehrly** [comment]
@f1multiviewer thanks for that information. I only knew about that API partially. I'll see what I can do with it.

> Aside from that, I had one more question for you. Let's say I have a full URL to a session (not the livetiming.formula1.com hostname), is there any way to tell FastF1 to fetch it from there?

Do you mean something like ``fastf1.get_session("2023/2023-03-19_Saudi_Arabian_Grand_Prix/2023-03-19_Race")``? I'm not sure, I really understood your question. If yes, should this work only for sessions that are listed in FastF1s event schedule anyway? Or should this work for any other (special) session that is currently not directly accessible through FastF1?

(Also sent you a DM on Reddit regarding another question)

**Comment by eXhumer** [comment]
> @f1multiviewer you made me aware of the season index API endpoints, so I assume you are likely making use of them?
> 
> When I use `https://livetiming.formula1.com/static/2023/Index.json` to get the schedule for the current season, all I get is information about events that have already taken place. That means, I cannot create a full event schedule for the current season from this endpoint. Am I missing something here, or does the API not provide information about future events?
> 
> Also, I'm really sorry that you took the time for creating such an extensive write-up of your API, but I still haven't got around to implementing it. Fingers crossed I'll get to it somewhere in the first half of this year.

Can you explain why exactly is retrieving future events be needed for Fast F1? The year Index.json provides event information for events that are currently going on and have already happened in the past. There is no session or timing data to fetch for future events until the first session for the future event is live, so not sure why it would be needed for.

**Comment by theOehrly** [comment]
> Can you explain why exactly is retrieving future events be needed for Fast F1? The year Index.json provides event information for events that are currently going on and have already happened in the past. There is no session or timing data to fetch for future events until the first session for the future event is live, so not sure why it would be needed for.

I consider the complete ``EventSchedule`` for the current seasons as a feature and not just as a tool for getting timing data for specific sessions. There are use cases where you would want to know information about upcoming events.

**Comment by eXhumer** [comment]
https://f1tv.formula1.com/2.0/R/ENG/WEB_DASH/ALL/PAGE/SEARCH/VOD/F1_TV_Pro_Annual/2?orderBy=meeting_End_Date&sortOrder=asc&filter_objectSubtype=Meeting&filter_season=2023&filter_orderByFom=Y&maxResults=100

From 2018 onwards, calendar events data from a season can be retrieved using this F1TV API.

There are other things that can be retrieved with the SEARCH/VOD endpoint, but that is out of the scope of this project.

**Comment by theOehrly** [comment]
@eXhumer from what I can tell, this API endpoint doesn't have starting times for the individual sessions. So that means that I would need to make an additional request for each event. This makes more than 20 requests to build the schedule, which is not really feasible.
The fastf1 backend is basically just doing that, aggregating the data from many requests every few hours so that FastF1 can access it with one request. I maybe should change how this data is served, i.e. not use Github 😅

**Comment by f1multiviewer** [comment]
> I guess `PitLaneTimeCollection` is removed now. Not seeing in any of the Index.json files this season

That's correct, they've ceased to emit this feed/topic.

**Comment by mithileshchellappan** [comment]
> That's correct, they've ceased to emit this feed/topic.

Is there any alternative?

**Comment by f1multiviewer** [comment]
@mithileshchellappan FYI I think it's back again, might've been removed temporarily? I don't know for sure.

**Comment by CreatoX** [comment]
Hi,

Looks like you are into the F1 API. Excuse me when I'm in the wrong place, but I have one short question.
I'm looking for a way only getting the flag status during a session. This must be live and as soon as possible.
Is there such way getting this? 

I want to program some lights to the color of the flag. Imation when there is a yellow flag all lights in my living room are also yellow :)

Looking for a while now without any success.

Hope finding a good start here. Thanks. 

Bert
The Netherlands

**Comment by f1multiviewer** [comment]
@CreatoX that's actually an integration for [MultiViewer](https://multiviewer.app), which sync your Hue lights (or even an LED panel) to the track status: https://f1mvli.jstt.me/docs/

**Comment by theOehrly** [comment]
@CreatoX I recommend you use what @f1multiviewer propose. FastF1 currently has no support for working with the data live.

**Comment by CreatoX** [comment]
Thanks for commenting @f1multiviewer @theOehrly . I will take look at MultiViewer.
Looks promising.
