### ISSUE TITLE
Loading telemetry from session problem

### ISSUE THREAD

**Issue by Ari04T** [theOehrly/Fast-F1#25]
Hello

When I try to load the laps with the `with_telemetry=True` option, I get the following error

```
gp_3_quali = ff1.get_session(2021, 3, "Q")
gp_3_quali_laps = gp_3_quali.load_laps(with_telemetry=True)

Traceback (most recent call last):

  File "<ipython-input-16-427ece08fcbb>", line 2, in <module>
    gp_3_quali_laps = gp_3_quali.load_laps(with_telemetry=True)

  File "C:\Users\User\Anaconda3\envs\py38\lib\site-packages\fastf1\core.py", line 1234, in load_laps
    self.load_telemetry()

  File "C:\Users\User\Anaconda3\envs\py38\lib\site-packages\fastf1\core.py", line 1314, in load_telemetry
    drv_car['Date'] = drv_car['Date'].round('ms')

  File "C:\Users\User\Anaconda3\envs\py38\lib\site-packages\pandas\core\series.py", line 2145, in round
    result = com.values_from_object(self).round(decimals)

TypeError: an integer is required (got type str)
```

**Comment by theOehrly** [comment]
Hi, I'm failing to reproduce this. Do you have any more information? Is there more logging output?

I think you're not using the most recent version. Please update and try again.

**Comment by Ari04T** [comment]
I'm not really sure what happened. I forced a reinstall of the package and now I am definitely using version 2.1.5. I don't get the error anymore. I don't see the telemetry however in the created dataframe. Is there a different way to access the telemetry now?

**Comment by theOehrly** [comment]
`Session.load_telemetry()` does not return any data.

Per-lap telemetry is available by selecting a lap and calling `Lap.get_car_data()` or  `Lap.get_pos_data()` (or  `Lap.get_telemetry()` if you want the merged data; equal to the 'old' telemetry)

I think you have been using a version that was older than v2.1? There where some changes made so that telemetry is no longer save in the Laps dataframe. (Allows more flexibility, higher accuracy, ...)
Maybe take a look at the current examples and the documentation in general.

**Comment by Ari04T** [comment]
Ah I wasn't aware of that. I saw the documentation but from the part "with_telemetry (bool) – Load telemetry data also. (Same as calling Session.load_telemetry() manually)" I assumed it was still possible to do it the old way.

So if I want to get the telemetry for the whole session, do you recommend just looping over so the laps of the session? Or do you think there's a better way to do it?

**Comment by theOehrly** [comment]
For telemetry of the whole session you can directly access `Session.car_data` or `Session.pos_data`. These two attributes are dictionaries which contain the full telemetry per driver.  But will also contain data from before and after the session started/ended (see:  https://theoehrly.github.io/Fast-F1/core.html#fastf1.core.Session.car_data).

You can then utilize the various methods for slicing that the (new) Telemetry class provides.

You can also call `get_car_data`/`get_pos_data`/`get_telemetry` on a dataframe* of multiple laps and you will get the combined telemetry for these laps.
(*Laps is a subclass of DataFrame)

For example:

    laps_rai = gp_3_quali_laps.pick_driver('RAI')
    rai_car_data = laps_rai.get_car_data()

Will give you the car data from Kimi for the whole session.

You can also call `get_car_data`/`get_pos_data`/`get_telemetry` on a dataframe* of multiple laps and you will get the combined telemetry for these laps.
(*Laps is a subclass of DataFrame)

**Comment by Ari04T** [comment]
Thank you very much and sorry for the dumb problem. I work mostly with R so I am much more comfortable getting the data into R and doing more processing there.

I will close this issue now. Keep up the good work.
