### ISSUE TITLE
[BUG] 2020 Styrian Grand Prix Race Laps

### ISSUE THREAD

**Issue by hoi82** [theOehrly/Fast-F1#259]
### Describe the issue:

 2020 season, as we know it, is really strange. :(
 Only laps of car number 55 (Carlos Sainz) are exist in 2020 Styrian Grand Prix Race.
 Is this also an external issue?
 Always thanks for your work. 

### Reproduce the code example:

```python
season = 2020
roundNumber = 2
sessionName = 'R'

session = fastf1.get_session(season, roundNumber, sessionName)
session.load(laps=True, telemetry=False, weather=False)
alllaps = session.laps.iterlaps();
alllaps = sorted(alllaps, key=lambda x: (float(x[1].DriverNumber), x[1].LapNumber))
```

### Error message:

```shell
core           INFO     Loading data for Styrian Grand Prix - Race [v2.2.9]
api            INFO     No cached data found for driver_info. Loading data...
api            INFO     Fetching driver list...
api            INFO     Data has been written to cache!
api            INFO     No cached data found for timing_data. Loading data...
api            INFO     Fetching timing data...
api            INFO     Parsing timing data...
api            INFO     Data has been written to cache!
api            INFO     No cached data found for timing_app_data. Loading data...
api            INFO     Fetching timing app data...
api            INFO     Data has been written to cache!
core           INFO     Processing timing data...
api            INFO     No cached data found for session_status_data. Loading data...
api            INFO     Fetching session status data...
api            INFO     Data has been written to cache!
api            INFO     No cached data found for track_status_data. Loading data...
api            INFO     Fetching track status data...
api            INFO     Data has been written to cache!
api            INFO     No cached data found for race_control_messages. Loading data...
api            INFO     Fetching race control messages...
api            INFO     Data has been written to cache!
core           INFO     Finished loading data for 1 drivers: ['55']
```

**Comment by theOehrly** [comment]
I just checked and this is kind of an external issue. Yes, there exists laps data for all driver. But the data that the API provides is in itself inconsistent, which causes some issues within FastF1. I can partially fix this for the next release, though. Supporting these two Austria events from 2020 is kind of a pain, as there is always something wrong somewhere in the data.

**Comment by hoi82** [comment]
> I just checked and this is kind of an external issue. Yes, there exists laps data for all driver. But the data that the API provides is in itself inconsistent, which causes some issues within FastF1. I can partially fix this for the next release, though. Supporting these two Austria events from 2020 is kind of a pain, as there is always something wrong somewhere in the data.

Thank you for your efforts. 2020 was such a strange year, so I think there are uncomfortable things.
I'll look for the data manually.

**Comment by theOehrly** [comment]
@hoi82 you could try to manually overwrite the property `Session.drivers` with a list of all driver numbers as strings before calling `Session.load`.
Or you can install from master directly, as I have already pushed a fix.

**Comment by hoi82** [comment]
> @hoi82 you could try to manually overwrite the property `Session.drivers` with a list of all driver numbers as strings before calling `Session.load`. Or you can install from master directly, as I have already pushed a fix.

Thanks. I'll try. :)
