### ISSUE TITLE
Weather data

### ISSUE THREAD

**Issue by TerminatorPlati** [theOehrly/Fast-F1#26]
Hi, having a look at the livetiming data I saw that data regarding the weather are also saved. Is it possible to implement a method that returns the weather conditions during the whole race for example?

**Comment by theOehrly** [comment]
Weather data is saved when recording live timing data. But it is never used after that. The recording just records every available channel, even if they're currently not used.

Adding weather info to each lap is not very difficult. Overall it is somewhat similar to adding session status data. It's not a huge effort to implement it. It's also not very difficult to do it yourself for now, if you really want to.

I will likely add it at some point as it is not a huge effort.

**Comment by theOehrly** [comment]
I've decided to add support for weather data in the latest release.
The changelog in the documentation will link you to the new parts in the documentation
