### ISSUE TITLE
[ENH] Get previous session informations directly from livetiming API

### ISSUE THREAD

**Issue by eXhumer** [theOehrly/Fast-F1#260]
### Proposed new feature or change:

It is possible to get all the session info from the following links.

https://livetiming.formula1.com/static/2018/Index.json
https://livetiming.formula1.com/static/2019/Index.json
https://livetiming.formula1.com/static/2020/Index.json
https://livetiming.formula1.com/static/2021/Index.json
https://livetiming.formula1.com/static/2022/Index.json

This can be used to dynamically fetch data instead of using https://github.com/theOehrly/f1schedule for most session (i.e. non testing). This doesn't include testing session information, so you will still need to maintain a copy of them still.

**Comment by theOehrly** [comment]
Thank you for making me aware of these. Someone else recently also opened an issue for this (#248). I'll aim to implement these for next season.

**Comment by theOehrly** [comment]
Now implemented as fallback from default and manually selectable data backend for the event schedule.
