### ISSUE TITLE
[BUG] `requirements-dev.txt` is outdated.

### ISSUE THREAD

**Issue by ndv99** [theOehrly/Fast-F1#263]
### Describe the issue:

Running `pip install -r requirements-dev.txt` does not install all required dependencies to get started on development.

Missing:
-pandas
-requests_cache
-thefuzz
-timple

### Reproduce the code example:

```python
pip install -r requirements-dev.txt
```

**Comment by theOehrly** [comment]
Can you please provide information on what error you get or what problem there is, when you try to install the requirements?
