### ISSUE TITLE
[BUG] `scripts` folder should be refactored, as Windows uses this when creating a Python virtual environment.

### ISSUE THREAD

**Issue by ndv99** [theOehrly/Fast-F1#265]
### Describe the issue:

As stated in the title, creating a Python environment in Windows using venv creates a `Scripts` directory, a directory which already exists in the file tree. We should refactor this directory to be called something else, e.g. `ff1_scripts` or `fastf1_scripts`.

**Comment by theOehrly** [comment]
I'll close this as well, after no further contrary opinions on this topic have popped up. See #261 for an explanation/discussion around this.
