### ISSUE TITLE
UnboundLocalError: local variable 'df' referenced before assignment

### ISSUE THREAD

**Issue by andybrady** [theOehrly/Fast-F1#27]
For FP1 of the 2021 Emilia Romagna Grand Prix the load_laps function in core.py errors out with a UnboundLocalError on line 1192. 

https://github.com/theOehrly/Fast-F1/blob/8da6cbb0feee71c3639fd6ef7b092ae8a7c9aa7b/fastf1/core.py#L1192

I've traced it back to the fact that no drivers are getting any data back from the timing_app_data api call. The ```useful``` data frame is empty, so when the for each driver loop occurs the length of d2 is always 0, meaning the loop ends without df ever having being initialized as a variable. 

https://github.com/theOehrly/Fast-F1/blob/8da6cbb0feee71c3639fd6ef7b092ae8a7c9aa7b/fastf1/core.py#L1168-L1190

**Comment by theOehrly** [comment]
That's a known problem specifically in that session. But it's not just the timing app data. See https://github.com/theOehrly/Fast-F1/issues/21

Quoting myself from an answer in this issue:

"Ok, so some more general info about FP1 again. The recordings from FP1 are missing everything but lap times as far as I can tell now. As there were major technical issues at the track in FP1 (TV feed not working properly, radios not working, driver tracker not working) I'll attribute the problems to this. I won't try to work around this to make whatever remains of the data usable with this package."

I won't fix this short-term. Long-term I'll have to work on making the data loading more flexible for those cases were some data is missing.
