### ISSUE TITLE
Season data

### ISSUE THREAD

**Issue by tijmen61** [theOehrly/Fast-F1#28]
Hello, first of all very nice work on fastf1. I was wondering if it is possible to get information about a season? Like the number of races, or a list with the races.

Different question: is it possible to get a session/weekend/race by date instead of year and gp name?

Kind regards, Tijmen

**Comment by theOehrly** [comment]
You can get season data from [https://ergast.com/mrd/](url). This is what fastf1 uses too, but ergast provides way more information than what is used in fastf1.
Some limited functionality to request data from ergast is implemented in `fastf1.ergast`. But this is undocumented and currently intended for internal use only.
But, in my opinion, it shouldn't be too difficult to request the data you want from ergast. Fastf1 just doesn't provide a nice implementation for it. So you'll have to do it yourself.

It is not possible to get an event by date. But you can get it by year and event number. I guess, in combination with data from ergast you could do it though.
