### ISSUE TITLE
[BUG] Stint increment in quali laps too early

### ISSUE THREAD

**Issue by japserboy** [theOehrly/Fast-F1#281]
### Describe the issue:

In quali sessions, it appears as if the stint number of a driver's laps increments one lap too early (on the in-lap instead of the out-lap). In race sessions, this is not an issue.

<img width="996" alt="image" src="https://user-images.githubusercontent.com/1831868/197844949-944d3e77-790a-4f5c-b9b4-4df2f566be01.png">

Is this a problem in the source data or tiny bug? Obviously it can easily be fixed with a workaround but I thought let's report it anyway. 

### Reproduce the code example:

```python
session = fastf1.get_session(2022, 'Singapore', 'Q')
session.load()

session.laps.pick_driver('VER')
```

**Comment by theOehrly** [comment]
First, sorry for the late response, and thank you for reporting this kind of unexpected behaviour. But, I am failing to reproduce this problem. Your code example yields the expected result when I run it. Which version of FastF1 are you using? Can you please update to the newest version if you are not on that version? Potentially, this is a problem that has been fixed recently.

**Comment by theOehrly** [comment]
@japserboy Does this work correctly for you now after ensuring that you are using the latest version? I just want to verify that this is not an issue.

**Comment by japserboy** [comment]
Hi, sorry for the late reply. Updating indeed fixed the issue!

Op do 17 nov. 2022 om 17:33 schreef Philipp Schaefer <
***@***.***>:
