### ISSUE TITLE
[ENH] Type hints

### ISSUE THREAD

**Issue by BCurbs** [theOehrly/Fast-F1#286]
### Proposed new feature or change:

When using the library, it is hard to either manually mark things as certain types, as the data classes aren't easily exposed, and the methods don't say what type they return, so ides have problems with seeing what methods are available for an object.

**Comment by theOehrly** [comment]
Yes, this is absolutely on the list of things that I'd like to get done. All new parts of FastF1 are already written with type hints. And older code should get type hints as well.

**Comment by BCurbs** [comment]
Could you take a look at draft pr #287 @theOehrly ? I think it should add a lot, though I went through quite quickly, and if I'm on the right track, I'll go through more comprehensively.

**Comment by BCurbs** [comment]
This is at least mostly complete, if it is fully satisfied by #287, this can be closed.

**Comment by theOehrly** [comment]
I'll leave it open for now as a general reminder, and there are still some places that might need improvement.

**Comment by Casper-Guo** [comment]
I can work on this. What are some parts of the library that still need type hints added?

**Comment by theOehrly** [comment]
Large parts of FastF1 have type hints now. But there are some places throughout where they are still missing. I can't narrow it down really.

**Comment by borolepratik** [comment]
although i haven't tested `mypy` with FastF1, it may help - https://stackoverflow.com/a/43187908
