### ISSUE TITLE
[BUG] Last lap not always added if driver crashed during a race

### ISSUE THREAD

**Issue by theOehrly** [theOehrly/Fast-F1#288]
### Describe the issue:

When a driver crashes during a race, a last lap with should be added to `Laps` as well, even though the driver did not pass the start/finish line at the end of that lap.
This should make it easier to get telemetry for laps that contain a crash that leads to the driver retiring immediately and not making it back into the pits.

Example: Perez in the first race of 2022

### Reproduce the code example:

```python
import datetime

import fastf1
import matplotlib.pyplot as plt


session = fastf1.get_session(2022, 1, 'R')
session.load(telemetry=True)
per = session.laps.pick_driver('PER')
last = per.iloc[-1]
last_tel = last.telemetry

crash_tel = session.car_data['11'].slice_by_time(
    last['Time'], last['Time'] + datetime.timedelta(minutes=1)
).add_distance()

plt.plot(last_tel['Distance'], last_tel['Speed'])
plt.plot(crash_tel['Distance'], crash_tel['Speed'])
plt.show()
```

### Error message:

```shell
not applicable
```

**Comment by RohanVDeshpande** [comment]
Any update on this? I was trying to look at telemetry data for Bottas's crash from the 2022 Austin GP (Lap 17), but it seems like the lap isn't added...

**Comment by theOehrly** [comment]
This will be properly supported in the next major version (v3.0), hopefully released in the next few weeks.
