### ISSUE TITLE
[CI/CLN] Unify import order and add flake8 test

### ISSUE THREAD

**Issue by theOehrly** [theOehrly/Fast-F1#291]
Imports are not necessarily well-structured at the moment. This should be fixed. PyQCA/flake8-import-order should be added to the tests/CI to ensure correct import order from then on.

**Comment by Casper-Guo** [comment]
Is this blocked or is it just no one has picked it up yet?

**Comment by theOehrly** [comment]
No one has picked it up and I pushed it away because I always deemed other stuff to be more important.

All imports should probably be absolute. I'm not even sure if this is the case right now. If not, changing it might cause issues with the documentation build.

The rules for import order should be noted in the documentation as well.
