### ISSUE TITLE
[ENH] Add a custom descriptive __repr__ and __str__ to Session

### ISSUE THREAD

**Issue by theOehrly** [theOehrly/Fast-F1#292]
### Proposed new feature or change:

Currently, the representation of `Session` is that of the same as for `object`-type:

```
<fastf1.core.Session at 0x1f72d989580>
```

This is not very descriptive. A better representation naming the event, season and similar should be added.

**Comment by Casper-Guo** [comment]
Two questions about this issue:

1, Does it make sense for Session to have a `__str__` method? Converting a Session object to str is a rare and possibly invalid way of using the class. None of the other data objects implement `__str__` method. 

2, Information directly available from the Session object itself includes the name of the session, the date of the session, and the event round number (from `self.event.gp`). The season can be parsed from `self.date` but the event name is more problematic. The only way I know how to do that is to index the event schedule of the season directly.

**Comment by theOehrly** [comment]
Re Question 1:

Take a look at the docs for the builtins `str()` and `repr()`. `str()` will fall back to returning `__repr__` if `__str__` is not defined. That is likely why it's simply not implemented by others. And I guess we don't need separate implementations either.
Also note, that `__repr__` often returns a string that can be directly used to create an object of the same type. FastF1 currently does not support that, because the mechanism to create a Session object is more complicated than that. So we won't bother with that. If FastF1's structure ever changes enough that this becomes possible, then changing the implementation of `__repr__` won't be a problem.

Re Question 2:
You should be able to directly access the event name through the event object that is accessible through `Session.event`, no?

**Comment by Casper-Guo** [comment]
I see. I was looking at the documentation (here)[https://theoehrly.github.io/Fast-F1/events.html#fastf1.events.Event] instead of (here)[https://theoehrly.github.io/Fast-F1/events.html?highlight=eventname#event-schedule-fastf1-events]. Do you think there is an opportunity to improve documentation here?

**Comment by theOehrly** [comment]
> I see. I was looking at the documentation (here)[https://theoehrly.github.io/Fast-F1/events.html#fastf1.events.Event] instead of (here)[https://theoehrly.github.io/Fast-F1/events.html?highlight=eventname#event-schedule-fastf1-events]. Do you think there is an opportunity to improve documentation here?

I'm fairly sure that there is always potential to improve the documentation.

Writing consice yet understandable documentation is surprisingly difficult if you know exactly how everything is supposed to work 😅
