### ISSUE TITLE
[BUG] British Grand Prix with wrong "IsAccurate" value for lap 3.

### ISSUE THREAD

**Issue by luancvs** [theOehrly/Fast-F1#299]
### Describe the issue:

If we filter LapNumber = 3 for the British Grand Prix event's laps data, IsAccurate column is set to true for 18 of 20 columns. It should not happen since it was a safety car lap.

### Reproduce the code example:

```python
import fastf1
session = fastf1.get_session(2022, 'British', 'R')
session.load()
session.laps.loc[session.laps['LapNumber'] == 3, "IsAccurate"]
```

**Comment by theOehrly** [comment]
Hi, can you explain why you think that this was a safety car lap? IMO, the order of events was as follows:
LAP 1 - immediate red flag, no safety car
-- long pause --
LAP 2 - second formation lap from box to grid with safety car in front; seems it doesn't count as safety car lap in the data
LAP 3 - standing start, green flag

Is this correct? In this case, the data is as correct as it can be, given the information available from the API.
