### ISSUE TITLE
[ENH] Add Offline Mode to Cache

### ISSUE THREAD

**Issue by theOehrly** [theOehrly/Fast-F1#307]
### Proposed new feature or change:

The Cache should have an option for enabling "offline mode" where only cached responses are returned.
This is useful for 
- speeding up requests that only use already cached data
- freezing the current state of requested data during development
- using FastF1 with an unstable internet connection or on a metered network

This feature depends on `requests-cache` version 1.0 (not yet released as of 27/12/22). 
See https://github.com/requests-cache/requests-cache/issues/394

**Comment by charlbbbbb** [comment]
Hi, could you confirm if this has been completed?

> This feature depends on requests-cache version 1.0 (not yet released as of 27/12/22).
See https://github.com/requests-cache/requests-cache/issues/394

Looking to contribute to fast-f1 so if this hasn't been completed, feel free to suggest other issues.

**Comment by theOehrly** [comment]
This has not been implemented yet. The release of requests-cache v1.0 is currently schedule for February 28th. It's likely easier to wait until then, although beta releases are available.

**Comment by oscr** [comment]
@charlbbbbb It looks like it's been released now: https://github.com/requests-cache/requests-cache/releases/tag/v1.0.0
