### ISSUE TITLE
FutureWarning pandas

### ISSUE THREAD

**Issue by JSEHV** [theOehrly/Fast-F1#31]
/usr/local/lib/python3.8/dist-packages/fastf1/core.py:1353: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  drv_car = Telemetry(car_data[drv].drop('Time', 1), session=self, driver=drv)
/usr/local/lib/python3.8/dist-packages/fastf1/core.py:1354: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  drv_pos = Telemetry(pos_data[drv].drop('Time', 1), session=self, driver=drv)

**Comment by theOehrly** [comment]
Thanks for the hint, I'll take care of that. Looks like there's still quite some time until this will break but the warning isn't nice to have either.

**Comment by theOehrly** [comment]
Next release is out. All future warnings and deprecation warnings should be fixed.
