### ISSUE TITLE
[BUG] 2021 Belgian race LapTime series has incorrect type

### ISSUE THREAD

**Issue by arseneyr** [theOehrly/Fast-F1#310]
### Describe the issue:

The 2021 Belgian GP race (lol) has all `NaT`s in the LapTime column. As a result, the dtype is `datetime64` instead of `timedelta64`. This causes calls to `LapTime.dt.total_seconds()` to fail. 

I'm not proficient with python or pandas, but it seems prudent to force _all_ time columns to use `timedelta64` upon creation. This should prevent any future issues of a column being incorrectly interpreted.

### Reproduce the code example:

```python
import fastf1

s = fastf1.get_session(2021, 'belgium', 'race')
s.load()
s.laps.LapTime.dt.total_seconds()
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DatetimeProperties' object has no attribute 'total_seconds'
```

**Comment by theOehrly** [comment]
Can confirm, this is a result of ``NaT`` being used by pandas as the NA-type for timedelta and datetime. When a column only contains ``NaT``, pandas then defaults to ``datetime64`` as it cannot determine the actual data type.

Some other classes (for example ``SessionResults``)  allready implement a mechanism to optionally enforce column data types on creation. So this should likely be easy to add here as well.
