### ISSUE TITLE
[ENH] fastf1.events documentation improvements

### ISSUE THREAD

**Issue by Casper-Guo** [theOehrly/Fast-F1#336]
### Proposed new feature or change:

1, Links for `EventSchedule` on other pages redirect to documentation for the [class](https://theoehrly.github.io/Fast-F1/events.html#fastf1.events.EventSchedule). There is more information about the class at the top of the page and above the linked section that might be missed. 

2, Many functions in the `Event` [class](https://theoehrly.github.io/Fast-F1/events.html#fastf1.events.Event) return `Session` objects. The `Session` tags in the documentation are not properly linked to the relevant class documentation. ([example](https://theoehrly.github.io/Fast-F1/events.html#fastf1.events.Event.get_session)). 

These redirects are inferred from the type hints on the corresponding functions. Changing those type hints from `Session` to `fastf1.core.Session` might solve this issue. Alternatively, the return type can be specified in the doc string.

**Comment by theOehrly** [comment]
I can barely find any links to the ``EventSchedule``, maybe like two, but I'll change those, good point.

I think 2) has somehow corrected itself, as far as I can tell?

**Comment by Casper-Guo** [comment]
Another nitpick that's similar to 1. The links for `Event` goes [here](https://docs.fastf1.dev/events.html#fastf1.events.Event) but there is more information about the attributes that can be accessed through `Event` objects under `Event Schedule Data` [here](https://docs.fastf1.dev/events.html#event-schedule-data). Those attributes are very useful but can be easily missed if you are only looking at the documentation for `Event`.

**Comment by theOehrly** [comment]
True, I guess there should be a reference to the more general explanation in the documentation of the ``Event`` class. And all references that don't need to refer to the class specifically should refer to the explanantion at the top.
