### ISSUE TITLE
Inconsistent Alpine Name

### ISSUE THREAD

**Issue by ahalekelly** [theOehrly/Fast-F1#34]
Only a minor issue, but the driver data in the API uses "Alpine F1 Team", the docs for `plotting.TEAM_COLORS` and `plotting.TEAM_TRANSLATE` say "Alpine F1 Team", but for me in 2.1.6 those actual dictionaries use "Alpine".

**Comment by ahalekelly** [comment]
Oh you've already fixed this, just hasn't reached the release version.

**Comment by theOehrly** [comment]
Next release is out, so it should be fixed now
