### ISSUE TITLE
[ENH] Team and driver colours per season

### ISSUE THREAD

**Issue by lmontrieux** [theOehrly/Fast-F1#340]
### Proposed new feature or change:

At the moment, the mappings between team and colour, and between driver an colour, are valid for the current season only.

Would it make sense to extend this to past seasons as well? If that's of interest I'm happy to give it a shot.

**Comment by lmontrieux** [comment]
I guess the main problem here would be colour selection. It's pretty easy to list all drivers and constructors per season, the ergast API has that. But colours? I don't know where to find that. Might have to be done manually, which would be quite the undertaking.

**Comment by lmontrieux** [comment]
Talking about colour selection. It looks like the team colour == the first driver's colour (in some cases we could debate who's the first and second driver until we're all blue in the face but let's not do that now 😄 ). However I wonder how the second driver colours are selected? Is it simply "something that looks a bit lighter", or is it a more precise process to it?

**Comment by Casper-Guo** [comment]
Similar has been proposed in #218 for your reference but the blocker is finding driver colors like yu said

**Comment by lmontrieux** [comment]
Oh yes, you are right. I missed it somehow. Closing this issue as a duplicate.
