### ISSUE TITLE
[MNT] reimplement horizontal/vertical slicing and remove __finalize__ from _constructor(_sliced)

### ISSUE THREAD

**Issue by theOehrly** [theOehrly/Fast-F1#349]
Pandas is in the progress of deprecating to allow non-class returns from `_constructor` and `_constructor_sliced` (https://github.com/pandas-dev/pandas/pull/52420).

This in turn means that FastF1 needs to change its implementations for differentiating between horizontal and vertical slicing of dataframes. 
Also, the `__finalize__` call that is done as a patch to work around the incomplete implementation in pandas needs to be removed from the constructor properties.

**Comment by jorisvandenbossche** [comment]
To be clear, there is not agreement at all that we want to do this, and as such there are no _concrete_ plans to actually deprecate this. 

The actual discussion is at https://github.com/pandas-dev/pandas/issues/51772 (the mentioned PR is a bit premature).

> This in turn means that FastF1 needs to change its implementations for differentiating between horizontal and vertical slicing of dataframes.

I am curious about this, can you point to the relevant code? (it's useful for us to better understand real-world subclassing use cases) 
Looking at for example the `Telemetry` subclass, the `_constructor` function only seems to do the extra `__finalize__` call (which is a good workaround for pandas failing to call it in some places, as you mention)

**Comment by theOehrly** [comment]
I know that there is no agreement on this yet. But I want to keep a close eye on this and therefore have opened this issue as a kind of reminder. If Pandas deprecates the callable constructor (and _metadata as well), important parts of how internal structures in FastF1 currently work will fall apart and need to be reimplemented in some way.

There are two ways in which FastF1 currently uses the callable constructor:

- `__finalize__` in the constructor as a catch-all workaround for incomplete metadata propagation (at a small performance cost).
   `__finalize__` would need to be called explicitly after every problematic operation.
- horizontal and vertical slicing of dataframes, here is an example: https://github.com/theOehrly/Fast-F1/blob/f5446afa7b2ff0860fbc4be3109485496978cd35/fastf1/core.py#L2943-L2953
  This could be implemented in `__new__` as well, I guess, but only because the column names for basically all DataFrame-like objects in FastF1 are basically constant. So the reference to `self.columns` is not necessary. But it would then fail, as soon as users add their own columns to a DataFrame (which they can do).

Deprecating `_metadata` would be more problematic than deprecating the callable costructor, but I see this one happening sooner, potentially.

**Comment by jorisvandenbossche** [comment]
Thanks for the explanation, that's super useful!

> Deprecating `_metadata` would be more problematic than deprecating the callable constructor, but I see this one happening sooner, potentially.

To be honest, I don't think this will happen any time soon. We also make use of this in GeoPandas, without easy ways around it (I am a maintainer of both pandas and GeoPandas)

For GeoPandas it is similar situation, I think: the ability to have a custom new function in `_constructor` is mostly convenient, but can be workaround somewhat (but at the same time I don't really see the benefit for pandas to actually disallow this). But `_metadata` is much more fundamental, and is a large part of what makes subclassing useful/working.
