### ISSUE TITLE
Syntax error when trying to record live session data using livetiming

### ISSUE THREAD

**Issue by theOllieS** [theOehrly/Fast-F1#37]
python -m fastf1.livetiming save saved_data.txt
              ^
SyntaxError: invalid syntax

Does anybody know what the issue is here?

**Comment by theOehrly** [comment]
I suppose this is not the full error message, or is it?

Do you have any more information, so I can figure this out? What version of fastf1 is that? I know that some people are using the live timing functionality without issues. So it's not a necessarily obvious problem maybe.
Does a simple `python --version` work?
