### ISSUE TITLE
[ENH] Add gap to a certain driver

### ISSUE THREAD

**Issue by Casper-Guo** [theOehrly/Fast-F1#371]
### Proposed new feature or change:

The telemetry module currently supports calculating the distance to the driver ahead. I wonder if it would be possible to also calculate the gap in seconds to the driver ahead.

Similarly, it is not uncommon to want to calculate the gaps to a certain driver at the end of each lap during race sessions (for example, what's the gap between Verstappen and Perez at the end of each lap?). This can also be a useful helper function, likely implemented for the `Laps` objects.

**Comment by theOehrly** [comment]
Distance to driver ahead is somewhat buggy. This needs to be fixed at some point. When doing so, it should be considered it the gap to the driver ahead can also be returned in seconds. 
It might actually be preferable to calculate the gap in seconds and convert to distance from there. But this is a rather complicated task that might require a lot of testing and experimentation. The advantage of working in seconds would be that sector times could be used as reference point to reduce integration error.

**Comment by theOehrly** [comment]
@Casper-Guo any reason why you closed this? It's very much still relevant, no?

**Comment by Casper-Guo** [comment]
The feature I had in mind is quite different from the one you described and version 3 made it redundant. That is why I closed this issue. Feel free to reopen it if you want it to serve as a reminder.

**Comment by theOehrly** [comment]
Ahh, I see. Now I understand what you actually meant when you opened this issue 😅
No, it's fine to close it. I was just confused.
