### ISSUE TITLE
[ENH] repr for the cache class or another way to output current cache

### ISSUE THREAD

**Issue by Casper-Guo** [theOehrly/Fast-F1#395]
### Proposed new feature or change:

The `fastf1.Cache` class doesn't implement a `__repr__` method. This can be used to show the cache location that is currently in use. Or there can be another way to get the current cache directory. Useful for interactive sessions.

**Comment by theOehrly** [comment]
I think both would be a nice improvement for convenience, adding ``__repr__`` and adding a function like ``get_path``.

**Comment by Casper-Guo** [comment]
Every method in the Cache class is defined with the class method @classmethod decorator so they can be called on the class rather than the instance. However, you need a metaclass to make dunder methods class methods. Apparently, there are some subtle caveats surrounding metaclass and I am not sure if you want the added abstraction.

[Reference](https://stackoverflow.com/questions/7642434/is-there-a-way-to-implement-methods-like-len-or-eq-as-classmethods)

**Comment by theOehrly** [comment]
Ahh you're right. I didn't think of that. I've worked with metaclasses previously, but I once read something along the lines of "if you think you need metaclasses in Python, 99% of the time, you should take a step back and think about what you're doing wrong". I think this is mostly true 😅 Maybe my implementation of the Cache is "wrong".

I need to think about this. Maybe the cache should be implemented differently. A (mostly) backwards compatible implementation would be something like this:

(in ``fastf1.req``)
```
class _Cache:
    ...

Cache = _Cache()
```

Now, every class method could just be a normal instance method. But there might be some other drawbacks. I need some time to consider this.
