### ISSUE TITLE
Wrong LapTime Y Axis

### ISSUE THREAD

**Issue by TerminatorPlati** [theOehrly/Fast-F1#4]
`plotting.laptime_axis(ax)`

this function misses the lapTime.

![image](https://user-images.githubusercontent.com/69049717/89132170-78bcfb00-d512-11ea-9bd8-eabf8f038802.png)

**Comment by TerminatorPlati** [comment]
I also tried with the example of the README. Same problem

**Comment by theOehrly** [comment]
This should be fixed now
