### ISSUE TITLE
[ENH] replacement to GapToLeader and IntervalToPositionAhead from fastf1.api

### ISSUE THREAD

**Issue by Nelson-Jnrnd** [theOehrly/Fast-F1#401]
### Proposed new feature or change:

Hello,

I am working on a ML project and was using the fastf1.api.timing_data function to get the time gap to leader in seconds and the time gap to car ahead.

I have seen that in the new version, this functionality has been removed. Is there any replacement for those informations currently in place ?

Best regards

**Comment by theOehrly** [comment]
At the moment, you should still be able to use that function, just like before, no? The function has only been deprecated but not been removed yet.

I'm planning some changes to the way data is loaded. The gap to the leader and gap to car ahead will be made available in a different way then. It'll still be quite a while until that happens. The deprecation is just a heads-up to the few people that directly utilize functionality from ``fastf1.api``.

**Comment by Nelson-Jnrnd** [comment]
Oh, sorry just realized it was moved to fastf1.core. Sorry for the inconvenience. 😊

Thank you for the response, love your work !

**Comment by ChangedNameTo** [comment]
Sorry to reopen this, but I'm not seeing this functionality in the fastf1.core docs after looking for quite some time now. I've attempted to replicate this buy adding all laptimes together, however in the case of the British GP missing laptimes causes this to be innacurate.

**Comment by theOehrly** [comment]
@ChangedNameTo there seems to be some confusion here. The previous comment is actually incorrect. Nothing has been changed or moved yet. Only the deprecation notice has been added.
