### ISSUE TITLE
[BUG] ``IsPersonalBest`` may be set incorrectly in Qualifying

### ISSUE THREAD

**Issue by theOehrly** [theOehrly/Fast-F1#403]
### Describe the issue:

The information about personal best lap times in the source data is reset between qualifying sessions. The current logic in the API parser resets ``IsPersonalBest`` for any lap to false if any subsequent personal best lap is slower. This is done so that deleted laps are not marked as personal best. 

In the special case where a qualifying lap in e.g. Q3 is slower than in Q2, this causes the Q2 lap to be considered 'deleted' and it is no longer marked as personal best.

This also results in ``Laps.pick_fastest`` returning the wrong lap.

Problem: At the point where personal best times currently need to be evaluated and deleted laps need to be removed, the API parser has no knowledge about Q1, Q2, Q3 and can therefore not differentiate between those.

### Reproduce the code example:

```python
import fastf1

session = fastf1.get_session(2023, "Canada", 'Q')
session.load(telemetry=False)

fastest = session.laps.pick_fastest()
# fastest should be Albon's lap for P1 in Q2 which was the overall fastest quali lap
```

### Error message:

```shell
-- not applicable --
```

**Comment by f1multiviewer** [comment]
Potentially relevant for anyone looking to fix this:

`TimingData.Lines[].BestLapTimes` contains the best lap times (and lap number) for each of the qualifying parts, which can maybe help out here.

Another thing that may be helpful is using `SessionData.Series[].Utc` to split the data per qualifying part.

**Comment by theOehrly** [comment]
@f1multiviewer thanks for the hints. 

In the end, I can't use the times from `TimingData.Lines[].BestLapTimes` because overall it contains less information than `TimingData.Lines[].BestLapTime`. I cannot detect when a personal best was deleted based on it. But it contains a counter 
the Q1, Q2, Q3 which means I can approximately split the data using only information from this one API endpoint. This is sufficient to fix this problem.
