### ISSUE TITLE
[ENH] <Discord Server>

### ISSUE THREAD

**Issue by UmiVilbig** [theOehrly/Fast-F1#408]
### Proposed new feature or change:

I think a great addition to the project would be a discord server to connect with other developers, help each other out, discuss all things F1, and to build a immersive community. I think alongside the server we can showcase projects built off of Fast-F1 and will be great growth

**Comment by theOehrly** [comment]
So, some thoughts on this idea:

- I think there are already communities where this can be discussed (i.e. GitHub Discussion, some Reddit communities?).

- A discord server requires people to have yet another account and while it is nice for discussion, it is badly searchable for previously asked topics. 

- It requires people to have yet another account.

- The server needs to be moderated, and moderating a discord server will likely be quite a bit more work than moderating GitHub here. (Which has been peaceful enough that I basically haven't needed to do anything so far).

In general, I'd like to get some more opinions on this. We could of course try it out and see how many people are interested. But someone needs to step up and do the server administration and moderation. I do want to focus more on the development itself. And if any discord server is "officially" associated with this project, it needs to adhere to the Code of Conduct of FastF1. This is not a question of "I want the Code of Conduct to be enforced", but it is plain and simple "I am required to have the code of conduct enforced (reliably!)". And that means that someone needs to take over moderation duties.
