### ISSUE TITLE
[BUG] Sprint shootout results loading broken after 3.0.2

### ISSUE THREAD

**Issue by mdsakalu** [theOehrly/Fast-F1#413]
### Describe the issue:

I haven't narrowed down the issue yet, but something has broken sprint shoot results loading after 3.0.2. It still works correctly with version 3.0.2.

### Reproduce the code example:

```python
import fastf1

event = fastf1.get_event(2023, 9)
ss = event.get_sprint_shootout()
ss.load()

print(ss.results) # all quali columns are null (should have times)
```

**Comment by theOehrly** [comment]
Caused by 2402ba0f956bf3a41b4dcc27b9f2232ce8fcfac5

I haven't yet analysed what the actual problem is. I'll try  to fix it soon.
