### ISSUE TITLE
[BUG] Season: 2023, Round: 11, FP1 30 results

### ISSUE THREAD

**Issue by cofievet** [theOehrly/Fast-F1#426]
### Describe the issue:

Hi
In the FP1 of Hungaroring Grand Prix in 2023, we have 30 results, with strange abbreviation and number
Can you check why this results appear for this session

Thanks a lot 

Corentin

### Reproduce the code example:

```python
fastf1.get_session(2023, 11, 1)
```

**Comment by theOehrly** [comment]
This is a problem with the source data for that session. F1 messed up their stuff. There is missing and incorrect timing and telemetry data and then they managed to mix in some data from Formula 3. This is why there are 30 drivers in the results. The additional 10 are F3 drivers. 
There's nothing we can reasonably do about this. The data is garbage.
