### ISSUE TITLE
[BUG] Data unavailable for Sprint Shootouts

### ISSUE THREAD

**Issue by whatTheDodd** [theOehrly/Fast-F1#435]
### Describe the issue:

I'm trying to extract data from the 2023 Belgian Sprint Shootout, but the only data I receive is from the sprint itself. Furthermore, I get error messages when I try to pin down the specific event.

### Reproduce the code example:

```python
import fastf1 as ff1
import fastf1.core
from fastf1 import plotting, utils
ff1.Cache.enable_cache('/Users/kierondodd1/PycharmProjects/Formula1/cache')

event = ff1.get_event(2023, 'Belgium')
session = event.get_sprint_shootout()
session.load()
```

### Error message:

```shell
AttributeError: 'Event' object has no attribute 'get_sprint_shootout'/Users/kierondodd1/PycharmProjects/Formula1/venv/lib/python3.11/site-packages/fastf1/events.py:676: FutureWarning: The `Weekend.name` property is deprecated and will beremoved in a future version.
Use `Event['EventName']` or `Event.EventName` instead.
  warnings.warn(
```

**Comment by theOehrly** [comment]
Please ensure you are using the latest version of FastF1. If you are using pip, you can update with ``pip install --update fastf1``. 
Please let me know, whether that resolves the issue.

**Comment by whatTheDodd** [comment]
Thank you for the suggestion but I think I have the most updated version as this was what was in my terminal:
pip install --update fastf1

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --update

Then I continue to get the same error

**Comment by theOehrly** [comment]
Sorry, I meant ``pip install --upgrade fastf1``

**Comment by whatTheDodd** [comment]
Great, all fixed
