### ISSUE TITLE
[BUG] There is no color for SHW

### ISSUE THREAD

**Issue by manpean** [theOehrly/Fast-F1#438]
### Describe the issue:

Shwartzman took part in Dutch GP FP1 and when i try to get the driver color, it fails.

It is not a major issue and i will use

try:
    driver_color[driver]=ff1.plotting.driver_color(driver)
except:
    driver_color[driver]=ff1.plotting.team_color(term.get_driver(driver).TeamName)
        

### Reproduce the code example:

```python
print(ff1.plotting.driver_color("SHW"))
```

### Error message:

```shell
fastf1\plotting.py:267 in driver_color
    raise KeyError

KeyError
```

**Comment by theOehrly** [comment]
Will be fixed once #441 is merged.
