### ISSUE TITLE
DRS Integer Values

### ISSUE THREAD

**Issue by kwaters4** [theOehrly/Fast-F1#44]
I was digging through the telemetry data and I was curious about the DRS integer values. 
I was not able to find anything in the documentation.  Here is an example from another thread it has already been plotted:

![image](https://user-images.githubusercontent.com/5183028/135763099-a3c485cb-303d-482c-8714-68b5d61ebe16.png)

Some drives have clean data sets of {0,1}, while other have a range of values from 0 to ~14.
Is there any insight to be had with the range of values or just an artifact of the data that is being pulled?

Thanks!

**Comment by theOehrly** [comment]
The reason that there is not much about it in the documentation is that I don't know. Somewhere in the documentation (module ``fastf1.api``) it says 0=disabled and 8=active which seems to be wrong actually, judging by the traces above. But it's also noted that further research is required. 
I haven't gotten around to that ever, so far. You could try to compare it to the official app and see if you find out anything. I'd be interested in the result actually. Then I could add this information to the docs.
The only thing that seems to be certain is that 0=disabled. Maybe it has something to do with DRS beeing availbale vs. being active?

**Comment by kwaters4** [comment]
I will dig into it and see if I can update some of the documentation. I found where it is documented now, as you mentioned, I will try to fill in the gaps.  Thank you!

**Comment by kwaters4** [comment]
### DRS Notes

This took a lot longer than I want to admit. I found some issues along the way that I may want to address as well. 
I will update the code and push it soon. Below are the details I have found, some of the values I was able to find remain a mystery to myself.

0 = DRS Enabled and Off 
1 = DRS Disabled
2 = DRS Enabled (Errounous?)
3 = DRS Disabled (Errounous?)
8 = DRS Enabled and Detected (Noted Sometimes)
10 = DRS Enabled and On 
12 = DRS Enabled and On 
14 = DRS Enabled and On 

### Example

Below is the raw data extracted for the lap:

Austrian Grand Prix 
Race 
2021-07-04
Lap : 45
`[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 14, 14, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 10, 10, 14, 14, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
`

Below is an example of the values plotted. The first zone is missing the detection due to it being the lap before, I am not sure about the third detection zone. 

![DRS_VER_45](https://user-images.githubusercontent.com/5183028/135942726-310a8849-4acb-4a2e-b356-8f6d8bedef9e.png)

**Comment by theOehrly** [comment]
Nice, those are some pretty good and useful results. And I'm not surprised that this took a bit of time to figure out.

Do you only want to update the documentation or do you also want to update some code?
Also, building the docs is not necessarily the most straightforward process. I'm not sure if you're intending to try that?

**Comment by theOehrly** [comment]
Sure, I'm looking forward to it. And yes, do feel free to ask for help when you encounter any issues.

**Comment by kwaters4** [comment]
#51 I sent a pull request for some basic changes for now. Let me know if there is anything else needed. I do not think it is quite yet "fixed" due to some of the distinctions and values being unknown.

**Comment by theOehrly** [comment]
I'll close this issue as the documentation updates have been merged.
