### ISSUE TITLE
[BUG] get_circuit_info() doesn't work with custom TELEMETRY_FREQUENCY

### ISSUE THREAD

**Issue by pesaventofilippo** [theOehrly/Fast-F1#455]
### Describe the issue:

`session.get_circuit_info()` throws `ValueError: All-NaN slice encountered` when the telemetry frequency is set to a value that is not `"original"`

### Reproduce the code example:

```python
import fastf1
fastf1.core.Telemetry.TELEMETRY_FREQUENCY = 10 # any integer

session = fastf1.get_session(2023, "Suzuka", "FP3")
session.load()

print(session.get_circuit_info()) # ValueError
```

### Error message:

```shell
File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastf1/core.py", line 2203, in get_circuit_info
    circuit_info.add_marker_distance(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastf1/mvapi/data.py", line 112, in add_marker_distance
    indices = np.nanargmin(e, axis=1)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in nanargmin
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/lib/nanfunctions.py", line 552, in nanargmin
    raise ValueError("All-NaN slice encountered")
ValueError: All-NaN slice encountered
```

**Comment by theOehrly** [comment]
Didn't think that anybody even uses the default resampling frequency feature 😅

Will be fixed in v3.2.0 because it requires a minor new feature so that it can be fixed.

**Comment by pesaventofilippo** [comment]
> Didn't think that anybody even uses the default resampling frequency feature 😅

Yeah, to be honest I only found one very specific use case for that for now, basically having a more precise "delta" without having to manually interpolate data.
For example, if I want to calculate the time it took someone to go from 0 to 100 km/h, but the first data point after 100km/h is 105km/h, using a faster resampling frequency means a more precise value.

Even in this case it would be better to just manually interpolate the desired data (Speed in this case), so you don't have to interpolate unnecessary data... this definitely isn't a high priority bug!

**Comment by pesaventofilippo** [comment]
Quick heads up - the same issue still remains, but only with some circuits, and results vary between sessions. I've made a simple script to test all circuits in the 2023 season, here are the results (tested with FastF1 v3.2.1):

```
import fastf1
import logging

logging.disable(logging.WARNING)
fastf1.core.Telemetry.TELEMETRY_FREQUENCY = 10 # any integer


def test(gp: int):
    session = fastf1.get_session(2023, gp, "R")
    print(f"{session.event.EventName}: ", end='')
    session.load()

    try:
        session.get_circuit_info()
        print("OK")
    except ValueError as e:
        print(e)


for i in range(1, 23):
    test(i)
```

Output:
```
Bahrain Grand Prix: All-NaN slice encountered
Saudi Arabian Grand Prix: OK
Australian Grand Prix: All-NaN slice encountered
Azerbaijan Grand Prix: All-NaN slice encountered
Miami Grand Prix: OK
Monaco Grand Prix: OK
Spanish Grand Prix: All-NaN slice encountered
Canadian Grand Prix: All-NaN slice encountered
Austrian Grand Prix: OK
British Grand Prix: All-NaN slice encountered
Hungarian Grand Prix: OK
Belgian Grand Prix: OK
Dutch Grand Prix: All-NaN slice encountered
Italian Grand Prix: All-NaN slice encountered
Singapore Grand Prix: All-NaN slice encountered
Japanese Grand Prix: OK
Qatar Grand Prix: All-NaN slice encountered
United States Grand Prix: OK
Mexico City Grand Prix: OK
São Paulo Grand Prix: All-NaN slice encountered
Las Vegas Grand Prix: All-NaN slice encountered
Abu Dhabi Grand Prix: All-NaN slice encountered
```

I'll try to look further into the cause. Removing the TELEMETRY_FREQUENCY line solves the problem for all events, but the results are NOT the same between different sessions. For example, Miami works if we use "R" as the session, but fails with "FP1". The Spanish GP instead fails with "R" but works with "FP1".

**Comment by theOehrly** [comment]
@pesaventofilippo still... interesting 🤔

Have you tested any of the offending sessions with the cache disabled? (``fastf1.Cache.set_disabled``)
I don't actually think that should have an influence here, but better it's quick to test.

**Comment by pesaventofilippo** [comment]
@theOehrly I've re-tested everything with the cache disabled, and the results are exactly the same.
FYI, I've tried using both `fastf1.Cache.set_disabled()` and the context manager `fastf1.Cache.disabled()`, and in both cases the warning "`DEFAULT CACHE ENABLED!`" was printed. Although I think this is only a logging issue, because the cache directory was not actually used and remained empty (and the requests were much slower).

**Comment by theOehrly** [comment]
I figured out the problem. There was another related bug that caused the data to be completely resampled again. Fix and release should be coming today.

The cache is enabled but not "used" then. That has to do with the order in which these things are done/checked. I agree that it's a bit confusing. But disabling the Cache is a feature that isn't (shouldn't) be used usually, except for development work. So I think it's not that important. I might fix it at some point though.
