### ISSUE TITLE
[BUG] Data for Piastri in the sprint shootout not available

### ISSUE THREAD

**Issue by pesaventofilippo** [theOehrly/Fast-F1#460]
### Describe the issue:

When loading the latest Sprint Shootout, only the data from 19 drivers is available, while Piastri seemingly has no data for the session.

### Reproduce the code example:

```python
import fastf1
session = fastf1.get_session(2023, "Qatar", "SS")
session.load()
# core INFO Finished loading data for 19 drivers: ['4', '1', '63', '55', '16', '27', '11', '14', '31', '10', '44', '77', '40', '24', '18', '23', '22', '20', '2']

print(session.laps.pick_driver("PIA")) # Empty Laps
```

**Comment by theOehrly** [comment]
Found the cause, the API response format deviates slightly from the usual. I need to slightly rewrite the parser code for the DriverList.jsonStream endpoint.
I'll try to fix it today or tomorrow and make a patch release.

**Comment by theOehrly** [comment]
Fixed and release is out
