### ISSUE TITLE
[BUG] USGP Results | Duplicate entry for TSU and LEC missing data

### ISSUE THREAD

**Issue by SmCTwelve** [theOehrly/Fast-F1#470]
### Describe the issue:

Looking at `session.results` Yuki Tsunoda has duplicate entries and is marked as Disqualified in place of Leclerc, for whom the data is `NaN`. 

I'm wondering if the error is from the livetiming API or after it's been parsed by FastF1. The data for Hamilton is correct though, so it's strange that only Tsunoda and Leclerc are being mixed up here. 

### Reproduce the code example:

```python
s = ff1.get_session(2023, 18, "R")
s.load()
s.results
```

### Error message:

```shell
core           INFO 	Loading data for United States Grand Prix - Race [v3.1.2]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	Session results contain duplicate entries for driver(s) ['22']
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '55', '11', '63', '10', '18', '22', '23', '2', '27', '77', '24', '20', '3', '14', '81', '31', '44', '16']
```

![](https://i.imgur.com/JFWY5Je.png)

**Comment by theOehrly** [comment]
This is an error in the Ergast data. Until it is fixed, you can use the following patch. 
This patch will only fix this specific problem in this specific session.

Like in the example below, add the patch right after the imports an before you load any data.

```
import fastf1

### patch ###
from fastf1.core import Session
unpatched = Session._load_drivers_results
def patched_load_results(self, *, livedata):
    unpatched(self, livedata=livedata)
    ecols = ('TeamId', 'DriverId', 'Position', 'Status', 'Points', 'ClassifiedPosition', 'Time', 'GridPosition')
    mask = (self._results['DriverNumber'] == '22') & (self._results['TeamId'] == 'ferrari')
    self._results.loc[(self._results['DriverNumber'] == '16'), ecols] = self._results.loc[mask, ecols].to_numpy()
    self._results = self._results[~mask]

Session._load_drivers_results = patched_load_results
### end of patch ###

session = fastf1.get_session(2023, 'Austin', 'R')
session.load()
print(session.results)
```

**Comment by SmCTwelve** [comment]
I had ruled out Ergast because the data was correct when I pulled directly from there. I had tested this after clearing the FastF1 cache as well.

Thanks for the patch though.

**Comment by theOehrly** [comment]
> I had ruled out Ergast because the data was correct when I pulled directly from there. I tested this after clearing the FastF1 cache as well.

The data in the JSON response is incorrect, but the data in the user-readable view on the website doesn't show that particular error because it's a reduced amount of data.
You need to look directly at the JSON response to spot it. Lecler has "number" 22 (that's Tsunodas number) and "permanentNumber" 16. Both should be equal of course.

**Comment by SmCTwelve** [comment]
Ergast has been updated to fix the issue.
