### ISSUE TITLE
Ergast ShuttingDown

### ISSUE THREAD

**Issue by danielribeiroc** [theOehrly/Fast-F1#474]
### Proposed new feature or change:

Are you familiar with any alternatives to Ergast? The reason I ask is because Ergast is scheduled to shut down later this year. Even now, the library remains inaccessible. 

Does someone have backed up all the data from latest years at least ?

**Comment by theOehrly** [comment]
We are working on that already. Currently, the plan is to continue running Ergast in some form but with new maintainers, and potentially with updated infrastructure and an improved server. See #445
