### ISSUE TITLE
install pyproject.toml-based projects

### ISSUE THREAD

**Issue by pavankay** [theOehrly/Fast-F1#479]
### Describe the issue:

Pip install fastf1 not working

### Reproduce the code example:

```python
pip install fastf1
```

### Error message:

```shell
ERROR: Could not find a version that satisfies the requirement pyprojects.toml-based (from versions: none)
```

**Comment by theOehrly** [comment]
I can't reproduce this problem, and the error message seems really odd. 

1. What operating system are you using?
2. Which version of Python are you using?
3. Please post the full output of pip, not just the final error, so I have a better chance of figuring this out.

**Comment by pavankay** [comment]
Iam using python 3.12. Iam on a windows. The full output is really big

**Comment by pavankay** [comment]
its not fitting

**Comment by Casper-Guo** [comment]
Just as a sanity check I tried on a fresh Linux environment with Python version 3.10.9 and cannot reproduce

**Comment by theOehrly** [comment]
I tested Python 3.10 and 3.12 on Windows and it's fine. Apart from that, the last release is long enough ago that it can't be a widespread issue or more people would have encountered it.

 @pavankay I know the full output is long but I don't think we are getting anywhere with the current information. 
Therefore, please post the full output here or use a service like pastebin.com and share the link here.

**Comment by pavankay** [comment]
Here is the link to the paste bin: https://pastebin.com/14RS1C9h

**Comment by Casper-Guo** [comment]
The cause is "failed building wheel for Pandas". Try the following first:

`pip install --upgrade wheel setuptools`

`pip install pandas --no-cache-dir`

You probably shouldn't be installing anything into an environment in the OneDrive directory anyways. It tends to be very slow.

**Comment by theOehrly** [comment]
@pavankay you need to do what the PIP error message suggests and download and install the build tools from the provided link.
