### ISSUE TITLE
Issue with loading data for the correct race

### ISSUE THREAD

**Issue by raghav-vish** [theOehrly/Fast-F1#48]
Loads data for Turkish GP properly when I put in 'Turkey' for the GP name, but loads data for British GP when I put in 'TURKEY' in uppercase.

**Comment by raghav-vish** [comment]
> I think it is happening because it may be case-sensitive and python language itself also is case-sensitive. It can also happen because official api does like this sometimes.

Likely an issue with the way the fuzzy matching is implemented

**Comment by theOehrly** [comment]
> 
> 
> > Yes, the fuzzy matching was case-sensitive. I'm surprised this problem didn't come up sooner already.
> 
> I'm unaware of how fuzzy matching works or is implemented but perhaps this issue could be solved by converting all inputs to a standard lower or uppercase before performing the matching?

The actual fuzzy string matching is done by a different module (thefuzz). And yes, I'll just convert the strings before passing them to this module.

**Comment by theOehrly** [comment]
Will be fixed in the next relase
