### ISSUE TITLE
[BUG] Las Vegas FP1 wrong URL

### ISSUE THREAD

**Issue by Pablomgom** [theOehrly/Fast-F1#481]
### Describe the issue:

Las Vegas URL is getting built like this:
https://livetiming.formula1.com/static/2023/2023-11-18_Las_Vegas_Grand_Prix/2023-11-17_Practice_1/SessionInfo.jsonStream
This is wrong, as the actual URL should be:
https://livetiming.formula1.com/static/2023/2023-11-18_Las_Vegas_Grand_Prix/2023-11-16_Practice_1/SessionInfo.jsonStream

### Reproduce the code example:

```python
fastf1.get_session(2023, 21, 1)
```

**Comment by Matew92** [comment]
Yes confirmed i have the same problem. Data for Vegas are not available yet!
Usually they should be available right after the session right?

**Comment by f1multiviewer** [comment]
To temporarily work around this (as it gets fixed):

```py
session = fastf1.get_session(2023, 21, 1)
session.api_path = "/static/2023/2023-11-18_Las_Vegas_Grand_Prix/2023-11-16_Practice_1/"

# ....
```

**Comment by theOehrly** [comment]
Please use the mentioned workaround for now. 

FP2 should be working without issues.

I'll try to fix it properly until FP3.

**Comment by theOehrly** [comment]
New release with a fix is out. Please update FastF1 and everything should be working.
