### ISSUE TITLE
[BUG] Driver CountryCode is not populated in the SessionResults object

### ISSUE THREAD

**Issue by borolepratik** [theOehrly/Fast-F1#493]
### Describe the issue:

Driver CountryCode is not populated in the SessionResults object for all drivers. Tested against 2023 Bahrain GP qualifying and race.

<img width="1302" alt="image" src="https://github.com/theOehrly/Fast-F1/assets/6431392/e10d9244-34e5-46c3-b32c-66927e7c362f">

### Reproduce the code example:

```python
import fastf1

event_schedule_2023 = fastf1.get_event_schedule(2023)
event_bahraingp = event_schedule_2023.get_event_by_name('Bahrain Grand Prix')
race_event = event_testing.get_race()
race_event.load(laps=True, telemetry=False, weather=False, messages=False,)
race_event.results
```

### Error message:

```shell
No error message, but instead missing data.
```

**Comment by harningle** [comment]
Can reproduce in version 3.1.6. Seems we forgot to include `CountryCode` when fixing #460:

https://github.com/theOehrly/Fast-F1/blob/89033fd3e24d111c77c20cf0838adccb3818c286/fastf1/_api.py#L1493-L1496

@theOehrly `fastf1/_api.py` in master branch doesn't fix #460. Shall I wrap up both #460 and this and create a PR to master?

**Comment by harningle** [comment]
A quick fix would be go to `_api.py`, and add ', CountryCode' to line 1495. You can find your `_api.py` by running `pip show fastf1` in terminal:

<pre>
Name: fastf1
Version: 3.1.6
Summary: Wrapper library for F1 data and telemetry API with additional data processing capabilities.
Home-page: https://github.com/theOehrly/Fast-F1
Author: Oehrly
Author-email: oehrly@mailbox.org
License: MIT
Location: <b>c:\program files\python310\lib\site-packages  <-- here</b>
</pre>

Open `c:/program files/python310/lib/site-packages/fastf1/_api.py` and change line 1495 to:
```python
    default_keys = [
        'RacingNumber', 'BroadcastName', 'FullName', 'Tla', 'Line', 'TeamName',
        'TeamColour', 'FirstName', 'LastName', 'Reference', 'HeadshotUrl', 'CountryCode'
    ]
```

**Comment by theOehrly** [comment]
@harningle Thanks for looking into this. If you want to create a PR to fix this, the best way would be to check out the maintenance-v3.1 branch, commit the fix and submit the PR from there. Then, change the base branch of the PR from master to maintenance-v3.1 in Github.

maintenance-v3.1 will be merged into master again at some point. That wasn't very clean branch management from my side. I really should only fix issues on the master branch and backport to the maintenance branch. I need to be more consistent here in the future (meaning from v3.2 onwards).
