### ISSUE TITLE
[ENH] <Acceleration data>

### ISSUE THREAD

**Issue by iskanderrr** [theOehrly/Fast-F1#507]
### Proposed new feature or change:

Calculate acceleration data for each car

**Comment by pesaventofilippo** [comment]
Chiming in to say: I don't think this is possible/doable. F1 does not provide raw acceleration data, so the only way to have it would be to derive it using the GPS position and speed.

I myself have tried for quite some time to come up with a reliable method to calculate it, but there are some challenges with this approach:
- The raw data is not granular enough for an accurate calculation based on position, both timing-wise (the update frequency is kind of low) and position-wise (the GPS resolution is only 10cm)
- FastF1's job is to provide accurate and reliable data. While you could in theory approximate the acceleration, the values would not be precise, and most importantly they would not have come from an official data source but only estimated, which kind of defeats the point.

I'd be happy to hear if someone follows up with a somewhat reliable method of computing accelerations (if you want, I have a lateral and longitudinal G graph from last year, obtained directly from an F1 team, for comparison), but as far as I know, until we can get more precise input data, the acceleration will always be largely estimated.

**Comment by theOehrly** [comment]
I agree with @pesaventofilippo, that's an excellent summary of the problem.

While it may be possible to estimate the acceleration partially, this will be very unreliable and inaccurate most of the time. I'm not saying that it's impossible to draw conclusions from acceleration data that is calculated from existing data in FastF1. But such data needs to be handled very carefully and one needs to be very aware of the limitations of the specific method used to calculate the data. Overall, there seems to be no way to provide accurate acceleration data. Therefore, it does not make sense to add this feature to FastF1.

**Comment by iskanderrr** [comment]
> I'd be happy to hear if someone follows up with a somewhat reliable method of computing accelerations (if you want, I have a lateral and longitudinal G graph from last year, obtained directly from an F1 team, for comparison), but as far as I know, until we can get more precise input data, the acceleration will always be largely estimated.
if you can send me that G graph it could really help!
I want to try few things and see how close we can get.

**Comment by pesaventofilippo** [comment]
@iskanderrr I'm not really sure if I can post it online, I'll ask the person where I got it from!
