### ISSUE TITLE
F2 data available from FastF1?

### ISSUE THREAD

**Issue by Djeeeeee** [theOehrly/Fast-F1#522]
### Proposed new feature or change:

Hello,
I think the answer is that it is not possible after having a brief look on the web.
But just in case I have missed something, do we get the same level of access for F2 (or even F3) that we get for F1 from which we could extract similar data?
Thanks

**Comment by theOehrly** [comment]
If I remember correctly, F2 at least has some live data but no archive for downloads after the session. But I haven't checked in a long time. It's not as simple as just pointing FastF1 at a different API server, in any case. It'd be a huge amount of work, and I currently have no capacity for that. And additionally, I'd have to deal with even more maintenance. It's really not feasible even if it were possible, which I'm not sure.

**Comment by fifisaac** [comment]
The FIA does release various pieces of data after the session, but nothing near what is taken from the F1 API by FastF1:
https://www.fia.com/sites/default/files/2023_01_brn_f2_r1_timing_sprintracehistorychart_v01_0.pdf
https://www.fia.com/sites/default/files/2023_01_brn_f2_r1_timing_sprintracesectoranalysis_v01_0.pdf
https://www.fia.com/sites/default/files/2023_01_brn_f2_r1_timing_sprintracepitstopsummary_v01.pdf
https://www.fia.com/sites/default/files/2023_01_brn_f2_r1_timing_sprintracemaximumspeeds_v01.pdf

Obviously out of scope for FastF1 as theOehrly said, but could be interesting as a separate project (which I might consider starting myself at some point)

**Comment by harningle** [comment]
> The FIA does release various pieces of data as PDFs after the session, but nothing near what is taken from the F1 API by FastF1: https://www.fia.com/sites/default/files/2023_01_brn_f2_r1_timing_sprintracehistorychart_v01_0.pdf https://www.fia.com/sites/default/files/2023_01_brn_f2_r1_timing_sprintracesectoranalysis_v01_0.pdf https://www.fia.com/sites/default/files/2023_01_brn_f2_r1_timing_sprintracepitstopsummary_v01.pdf https://www.fia.com/sites/default/files/2023_01_brn_f2_r1_timing_sprintracemaximumspeeds_v01.pdf
> 
> Obviously out of scope for FastF1 as theOehrly said, but could be interesting as a separate project (which I might consider starting myself at some point)

I've done something on the PDFs, and made a very incomplete notebook on extracting the table from those PDFs, just in case you want to have a look: https://github.com/harningle/fia-doc/blob/main/notebook/parse_race_lap_analysis.ipynb

**Comment by Djeeeeee** [comment]
Thanks both, that is useful!
I don't think they still publish these documents as I can't find them for Bahrain sprint/feature race unfortunately

**Comment by fifisaac** [comment]
> Thanks all, that is useful! I don't think they still publish these documents as I can't find them for Bahrain sprint/feature race unfortunately

There's also many missing from the past and loads of weird inconsistent things about them, I think building a project to analyse them would be very difficult

**Comment by Djeeeeee** [comment]
Just discovered this:

https://fiaresultsandstatistics.motorsportstats.com

Plenty of info and data for various series, F2 included.

Thanks

**Comment by fifisaac** [comment]
> Just discovered this:
> 
> https://fiaresultsandstatistics.motorsportstats.com/
> 
> Plenty of info and data for various series, F2 included.
> 
> Thanks

[And they have an API! ](https://motorsportstats.com/api/result-statistics?sessionSlug=fia-formula-2-championship_2024_jeddah_race-2&sessionFact=LapChart&size=25) Perhaps somebody could make something for F2 (or hell, any of the other series this site has) using this

**Comment by fifisaac** [comment]
Put together a [little prototype](https://github.com/fifisaac/lap-chart-plotter) using that site if anyone who was in here wants to mess about with it too. I noticed a few problems trying to figure out the API, the main one being finding what sessions a weekend has. And obviously lots of series lack detailed data, but thats understandable given how much there is on the site
