### ISSUE TITLE
[BUG] Live timing recording stops after 2 hours

### ISSUE THREAD

**Issue by pesaventofilippo** [theOehrly/Fast-F1#524]
### Describe the issue:

When recording live timing data with the `fastf1.livetiming save` command, the recording stops every time exactly after 2 hours with the message `Timeout - received no data for more than 60 seconds!`. The data stream doesn't actually stop though - as by restarting the same command you can immediately see new messages.

Maybe this could be a timeout on their server side and FastF1 should send a heartbeat of some sorts, or it should "renew" the signalr connection? I'm not too familiar with the signalr protocol :/

### Reproduce the code example:

```python
python3 -m fastf1.livetiming save livetiming.txt
```

### Error message:

```shell
# After 2 hours
WARNING: Timeout - received no data for more than 60 seconds!
WARNING: Exiting...
```

**Comment by theOehrly** [comment]
That's not a bug really, it's documented in the "Important Notes" here https://docs.fastf1.dev/livetiming.html#important-notes

Yes, that is some kind of server side disconnect. I don't know of any way to send a keep-alive message to prevent this. Therefore, the solution currently is to start overlapping recordings. The duplicate messages in the overlapping data will be automatically be dealt with when loading the data.

**Comment by pesaventofilippo** [comment]
> it's documented in the "Important Notes" here https://docs.fastf1.dev/livetiming.html#important-notes

Oops, sorry, I didn't pick that up. I guess there's nothing we could do to solve the issue then. Feel free to close this issue if you want.

**Comment by theOehrly** [comment]
Not saying that there isn't a way to implement some way to keep the connection alive. The problem is, this is kind of low priority as there are barely any sessions each year where this is relevant. Furthermore, it's a bit of a niche feature. And few sessions where this is relevant means few opportunities to test it.
