### ISSUE TITLE
[BUG] Drive number error

### ISSUE THREAD

**Issue by angeldiaz017** [theOehrly/Fast-F1#528]
### Describe the issue:

*Hi*
Im trying to download 2024 Preseason test session data, but when i use load method core.py give me the follow error:
KeyError: 'DriverNumber'
I've load de session with this sentence: 
```{python}
pre_season_session = fastf1.get_session(2024, "Pre-Season Testing", 'Practice 1')
pre_season_session.load()
```

### Reproduce the code example:

```python
pre_season_session = fastf1.get_session(2024, "Pre-Season Testing", 'Practice 1')
pre_season_session.load()
```

### Error message:

```shell
KeyError: 'DriverNumber'
```

**Comment by Casper-Guo** [comment]
You have to use [`get_testing_session`](https://docs.fastf1.dev/fastf1.html#fastf1.get_testing_session) instead

**Comment by angeldiaz017** [comment]
Oh, my bad. Thanks :D
