### ISSUE TITLE
Sergio Perez's last lap (Missing last inlap)

### ISSUE THREAD

**Issue by hash55** [theOehrly/Fast-F1#55]
Sorry I have an issue when I try to access to Checo's last lap of Q3 in Mexico( the one that he went on the grass because of Tsunoda). I think it is because he didn't complete the lap as he went into the pits after the mistake. If I'm not wrong there is a way to access to it isn't it?
Thanks

**Comment by theOehrly** [comment]
Fixed it, will be in the next release. You can install directly from master for now to test it

`pip install --upgrade --no-deps --force-reinstall git+https://github.com/theOehrly/Fast-F1.git`

or you could use the 'manual' way, similar to what's described here: #41

**Comment by hash55** [comment]
Thanks! I have done it manually and now I can see the telemetry correctly. However, is there any way to get position data of that _inlap_, instead of the car data telemetry? 
I mean, to plot the _Speed_ vs _Distance_, instead of _Speed_ vs _Time_

**Comment by theOehrly** [comment]
I think you are looking for this

https://theoehrly.github.io/Fast-F1/core.html#fastf1.core.Telemetry.add_distance

for example

`car_data_per = car_data_per.add_distance()`

**Comment by hash55** [comment]
Thanks! That's what I was looking for. However, to get the XYZ coordenates of the lap,  do I need to use  the `fastf1.api.position_data` function?

**Comment by theOehrly** [comment]
Apart from `Session.car_data` there's also `Session.pos_data` which should give you the data you want. Slicing is the same then. 
You can use `Telemetry.merge_channels` to combine the two if necessary.
