### ISSUE TITLE
[BUG] Track status Australian GP last lap

### ISSUE THREAD

**Issue by formulatimer** [theOehrly/Fast-F1#557]
### Describe the issue:

Track status in the last lap Asutralian GP is virtual safety car due to the Russel's crash. And data show '2' (yellow flag) in Carlos Sainz last lap instead of a number that contains '6' (Virtual Safety Car deployed). It also happens with others drivers

### Reproduce the code example:

```python
n
```

**Comment by theOehrly** [comment]
Thanks for spotting and reporting this.

**Comment by formulatimer** [comment]
@theOehrly the pull request #558 solve the issues

**Comment by formulatimer** [comment]
but some test fails and I do not why, maybe you can help me

**Comment by theOehrly** [comment]
referencing [c59c2dc](https://github.com/theOehrly/Fast-F1/commit/c59c2dc6b864281f8ef2312d2c7adea0016b8804) for completeness
