### ISSUE TITLE
[BUG] 2023 Austria FP1 Telemetry data is missing

### ISSUE THREAD

**Issue by ghost** [theOehrly/Fast-F1#559]
### Describe the issue:

The issue is only for the very specific FP1 session of the 2023 Austrian Grand Prix, and is correctly highlighted by the relevant warning.
core        WARNING 	Car position data is unavailable!
Is it possible to reprocess the data in FastF1's backend to resolve this problem? 

### Reproduce the code example:

```python
import fastf1
session = fastf1.get_session(2023, 'Austria', 1)
session.load()
session.pos_data['33']
```

### Error message:

```shell
...
core        WARNING 	Car position data is unavailable!
...
KeyError: '33'
```

**Comment by theOehrly** [comment]
There's nothing that can be done about that sadly. The data simply doesn't exist. There were technical issues on F1's end during that session.

See #412 as well

**Comment by leonardobocci** [comment]
Ok, clear, thanks for the reply! That's a shame they never managed to collect the data and fix it :(
