### ISSUE TITLE
[External Help] Using official timing api

### ISSUE THREAD

**Issue by siddharth-tewari** [theOehrly/Fast-F1#56]
Hello, this is not related to FastF1, sorry. I had a question that how can I use the F1's official data stream to make a type of map and leaderboard seen Racing Statistics youtube channel. It should work in real time by using loops maybe?
Or maybe even for Formula 2 and 3 if someone knows how to as I have the official source's link.

**Comment by siddharth-tewari** [comment]
Also which account is required here?
https://livetiming.formula1.com/
and how to get links of old Gp's?

**Comment by hash55** [comment]
> Hello, this is not related to FastF1, sorry. I had a question that how can I use the F1's official data stream to make a type of map and leaderboard seen Racing Statistics youtube channel. It should work in real time by using loops maybe? Or maybe even for Formula 2 and 3 if someone knows how to as I have the official source's link.

That channel get's the data from [https://f1.tfeed.net/](url). Don't know if we can scrap something from there

**Comment by siddharth-tewari** [comment]
Ok, I was wondering can we make same like tfeed for Formula 2 using this - https://ltss.fiaformula2.vom

**Comment by siddharth-tewari** [comment]
Any way also to code dynamic F1 like graphics for live F2 stream data?

**Comment by siddharth-tewari** [comment]
@theOehrly I found some new links of Formula 2 api. You may check it.

https://ltss.fiaformula2.com/streaming/negotiate

https://ltss.fiaformula2.com/streaming/start?transport=webSockets&clientProtocol=2.1&connectionToken=I0d%2FBXCuzgDVu9k3s8uCV%2FqP3qDpGty4j5Fg2Dc%2FLN3iLpOwKRcfqeOQ6tt1rHhGstnePlwrqE80a7%2BTGpz3KceI45J4Rtw8Vq%2Fd6qG5DXn%2BLgjGgZASkWiHQeoyXaaR&connectionData=%5B%7B%22name%22%3A%22streaming%22%7D%5D&_=1637591587662

**Comment by theOehrly** [comment]
Development of everything that is related to live streams is complicated, as I can only do testing while a session is taking place. There are enough issues that need to be fixed as it is already. I currently have no desire or capacity to add even more complicated problems to that. Maintaining what is already there takes up enough time already. Therefore, I will not be able to look into this at any time in the foreseeable future. As nice of a feature as it would be.

**Comment by siddharth-tewari** [comment]
@theOehrly Hello, I made a account on F1 website. How to use that account on https:livetiming.formula1.com and what do we need to enter? Any way how to use its signalr for live data.

**Comment by theOehrly** [comment]
@siddharth-tewari I don't understand what you want to know and what to achieve? Also, do you know what SignalR is?

**Comment by siddharth-tewari** [comment]
@theOehrly I am mean can I use my F1 account to login and then it will give a dashbord type of thing? For signalr I meant how can we use https://livetiming.formula1.com/signalr for live data during race like https://f1.tfeed.net

**Comment by siddharth-tewari** [comment]
Hello, I found new source for Formula E too.
https://livetiming-formula-e.alkamelsystems.com/sockjs/info?cb=x4dj4m_8a6
https://livetiming-formula-e.alkamelsystems.com/_timesync

@theOehrly Maybe you can make a dictionary for interested people who know how to develop live streams.

**Comment by theOehrly** [comment]
> @theOehrly I am mean can I use my F1 account to login and then it will give a dashbord type of thing? For signalr I meant how can we use https://livetiming.formula1.com/signalr for live data during race like https://f1.tfeed.net

No, it won't give you dashboard or something like that (as far as I know).

You can use the data from the signalr stream like f1.tfeed.net after you've written lots of code to make that happen. That means, at the moment, you can't.

> Hello, I found new source for Formula E too.
> https://livetiming-formula-e.alkamelsystems.com/sockjs/info?cb=x4dj4m_8a6
> https://livetiming-formula-e.alkamelsystems.com/_timesync
> 
> @theOehrly Maybe you can make a dictionary for interested people who know how to develop live streams.

I don't have time to look into api sources for other racing series. So no, I won't. 
Also, finding the urls is the easiest part. Someone who's interested in developing software for this will not fail on that task.

**Comment by siddharth-tewari** [comment]
Thank You, no problem
