### ISSUE TITLE
[BUG] Rainfall data is wrong sometimes

### ISSUE THREAD

**Issue by hahampis** [theOehrly/Fast-F1#561]
### Describe the issue:

Hello,

I have already seen similar issues #76 and #478 but it appears the problem still exists in some places.
Rainfall values are True in sessions where there was no rain.
I have checked with v3.3.2.

Thank you for your awesome work!

### Reproduce the code example:

```python
from fastf1 import Cache

with Cache.disabled():
    session = fastf1.get_session(2019, 'Sakhir', 'Q')
    session.load(telemetry=False, messages=False)
session.weather_data
```

### Error message:

```shell
req         WARNING 	DEFAULT CACHE ENABLED! (8.26 GB) /Users/hahampis/Library/Caches/fastf1
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.3.2]
_api           INFO 	Fetching session info data...
_api           INFO 	Fetching driver list...
_api           INFO 	Fetching session status data...
_api           INFO 	Fetching track status data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api           INFO 	Fetching timing app data...
core           INFO 	Processing timing data...
_api           INFO 	Fetching weather data...
core           INFO 	Finished loading data for 20 drivers: ['16', '5', '44', '77', '33', '20', '55', '8', '7', '4', '3', '23', '10', '11', '26', '99', '27', '18', '63', '88']
Time	AirTemp	Humidity	Pressure	Rainfall	TrackTemp	WindDirection	WindSpeed
0	0 days 00:00:29.443000	25.4	55.4	1009.9	False	30.5	349	1.8
1	0 days 00:01:29.455000	25.3	55.3	1009.9	False	30.5	13	2.4
2	0 days 00:02:29.470000	25.3	55.4	1010.0	False	30.4	49	2.0
3	0 days 00:03:29.485000	25.3	55.5	1009.9	False	30.2	44	1.5
4	0 days 00:04:29.494000	25.3	55.3	1009.9	False	30.2	59	2.0
...	...	...	...	...	...	...	...	...
73	0 days 01:13:30.460000	24.8	56.8	1010.3	False	27.8	22	1.6
74	0 days 01:14:30.473000	24.8	56.9	1010.4	False	27.8	53	2.0
75	0 days 01:15:30.529000	24.8	56.9	1010.3	True	27.8	61	1.7
76	0 days 01:16:30.639000	24.8	57.1	1010.3	True	27.8	31	1.8
77	0 days 01:17:30.513000	24.8	57.3	1010.3	False	27.6	12	1.4
78 rows × 8 columns
```

**Comment by theOehrly** [comment]
Looking at the 2019 Bahrain qualifying that you give as an example, I can see about two minutes of apparent rain in the data in FastF1 at the end of Q3. Is that what you are referring too?

If yes, this is actually correctly parsed in FastF1. The source data contains from the API says that there was rain. So this is not a bug.

I did some investigation. Finding a weather radar replay for 2019 proves to be difficult. But I read that before the weekend, there was potential rain forecast for Saturday and Sunday. The replay of the Qualifying session seems to show some darker grey(ish) clouds at the beginning of the session before it becomes dark. So maybe there were some rain clouds in the area around the circuit and the local weather radar was tricked into thinking there is rain.

**Comment by hahampis** [comment]
If the source data say there was rain, then there is not much one can do.. Thanks!
