### ISSUE TITLE
Ergast API lookup fail for Mexican Grand Prix

### ISSUE THREAD

**Issue by jerryvarghese1** [theOehrly/Fast-F1#57]
(First time submitting a bug report)

Your library has worked amazingly and as expected for the last 3 or 4 races. I have a script that processes data based on your library to turn it into a lap chart visualization. But on the latest Grand Prix, the results dictionary is formatted oddly and causes my code to break. I get ```core        WARNING 	Ergast API lookup failed. The session is very recent and not yet available or does not exist.```

Which is odd, because https://ergast.com/api/f1/2021/18/results looks to be fully filled in.

Here are some additional screenshots:
Race 17 (US Grand Prix) ```race.results```:
![image](https://user-images.githubusercontent.com/63359305/141356929-51c48097-fcdd-4fe7-ae17-a109a0d0f2f7.png)

Race 18  (Mexican Grand Prix) ```race.results```
![image](https://user-images.githubusercontent.com/63359305/141357156-1d78a0f2-2eff-4bfa-90a8-72f4356c2139.png)

The classifications in Race 18 are missing (and the subdictionary lengths are 3 instead of the full 10)
If it helps, I am specifcally trying to pull the constructor names (which are in the Mexican Grand Prix's dictionary but under a different key) and each driver's classification (which is altogether missing from the dictionary).

Thank you for any assistance you can offer!

**Comment by theOehrly** [comment]
Please update to the latest version if you haven't done so already.

Also, have you tried running your script without cache enabled? If that fixes it, run it once with `.enable_cache(force_renew=True)`

**Comment by jerryvarghese1** [comment]
I updated the library and ran it with the ```force_renew=True``` option. It is unfortunately yielding the same result.

**Comment by theOehrly** [comment]
I am failing to reproduce this or I do not understand the problem correctly.

If I run exactly these two lines of code 

```
import fastf1

race = fastf1.get_session(2021, 'Mexico', 'R')
```

I get no warnings whatsoever and the following result:

![Screenshot 2021-11-11 231537](https://user-images.githubusercontent.com/23384863/141377251-57be933a-f271-4840-b915-e4cfd3958a8f.png)

To me, after a quick look, it seems like all the data is there. Or not?
Do you get the same result? 
Can you provide a minimal example that produces the issue for you?

**Comment by jerryvarghese1** [comment]
That's interesting: it honestly might be an environment thing, so I'm going to try opening a new environment and installing it fresh to see if there's some weird conflict and if it's just on my end.
As for code, I'm using the exact code from the QuickStart examples. 
I'll upload the code after I check if it's an environments issue!

**Comment by jerryvarghese1** [comment]
I deleted everything in the cache and it works fine now. The issue is likely that if the cache is updated when ergast doesn't have full information yet, it breaks all future instances of running the code. I ran it right after the race finished last time. My simulation is up and running now. Thanks!

**Comment by theOehrly** [comment]
Great that you've solved it.
Although, this really shouldn't happen. I guess I need to be a bit less friendly to the API Server and have the cache expire in reasonably short intervals.
I'm actually surprised now that this isn't causing more problems.

**Comment by jerryvarghese1** [comment]
It happened to me again today; once again, after clearing the cache, everything worked fine. Perhaps you could implement something that clears the cache if an ergast lookup partially fails, because that is when the data does not read in properly when the script is run again.

**Comment by theOehrly** [comment]
Yes, I absolutely need to fix this. Hopefully I'll manage to do it soon.
