### ISSUE TITLE
[BUG] Incorrect name of the China session 2

### ISSUE THREAD

**Issue by formulatimer** [theOehrly/Fast-F1#570]
### Describe the issue:

China is the first sprint on 2024 calendar

The calendar that fastf1 uses to dowload the information shows:
Session1                                           Practice 1
**Session2                                      Sprint Shootout**
Session3                                               Sprint
Session4                                           Qualifying
Session5                                                 Race

wheareas on the official webpage the sessions are:
Session1                                           Practice 1
**Session2                                      Sprint Qualifying**
Session3                                               Sprint
Session4                                           Qualifying
Session5                                                 Race

The name os the session 2 is different, which may cause some errors when downloading the data

### Reproduce the code example:

```python
N
```

**Comment by theOehrly** [comment]
Ohh thanks for reporting. I already made sure that the changed session order works correctly.  Looks like I missed that they renamed the Sprint Shootout to Sprint Qualifying. 

This needs to be fixed/checked in various places including the schedule data backend. I'll see that I get it done before the weekend.

**Comment by theOehrly** [comment]
This should be fixed now. 

I noticed some minor inconsistencies already in F1's APIs regarding this name change. Let's hope there won't be any more inconsistencies once data becomes available on the weekend. Else, there might still be errors related to this.
