### ISSUE TITLE
Docs contain unsupported argument for get_event

### ISSUE THREAD

**Issue by Casper-Guo** [theOehrly/Fast-F1#576]
### Describe the issue:

There is a rendering issue in the [get_event docs entry](https://docs.fastf1.dev/fastf1.html#fastf1.get_event). The entry claims that there is a strict_search optional argument for the function when this is actually not implemented.

Although this is something we can support in the future as part of the fuzzy matching PR I’m preparing. 

### Reproduce the code example:

```python
strict_search (bool) – Match precisely the query, or default to fuzzy search. If no event is found with strict_search=True, the function will return None
```

**Comment by theOehrly** [comment]
There is a rendering issue, yes. But the documentation is correct. The signature in the docs is also auto-generated from the true signature. So while the text could be wrong, the rendered signature is very unlikely to be wrong. The argument exists and it is working.

Did you click on the "source" link next to the function in the docs? The source that is rendered there is out of date. Actually, it is from version 2.2.2 as you can see on that page. Somehow, the CI isn't properly building the docs from scratch. I noticed this a few weeks ago, but haven't got around to investigating this.

But the feature exists, and it worked as intended when I just checked.

> Although this is something we can support in the future as part of the fuzzy matching PR I’m preparing.

Agree, it would be nice if all the fuzzy endpoints support this. What's your opinion on the name ``strict_search``. I'm somehow not a fan of that name any more, although I was the one who named the argument like that.

**Comment by Casper-Guo** [comment]
I see. I didn't realize the source is out of date. If you want a new name I propose exact_match.

**Comment by theOehrly** [comment]
> I see. I didn't realize the source is out of date. If you want a new name I propose exact_match.

I think "exact_match" is better, yes. If we use that on new functions, then we should change it here as well, with proper deprecation.
