### ISSUE TITLE
Sao Paolo GP Telemetry Issue

### ISSUE THREAD

**Issue by hotlapmode** [theOehrly/Fast-F1#58]
I tried taking a look at the data as usual, 30 minutes after the end of the session like the other times, but i received an error. The program does not give me the data from FP1 in Interlagos, but from FP1 in Bahrain. 

I'm not the only one facing these issues; just wanted to reach out to the developer/s so this can be fixed, if possible

**Comment by theOehrly** [comment]
Hi, sorry for the inconvenience. For some reason, the official name of the GP is "São Paulo Grand Prix" this year and not "Brazilian Grand Prix". The online database from which I'm pulling the GP names does not have the correct name, though. Therefore, FastF1 cannot generate the correct API path for downloading the data.

Until the database has been updated (I can't do that but I have notified them) you need to use the workaround below to load any session for this weekend.
Even after the database has been updated, it'll only work without the workaround once you have deleted the file "fastf1_http_cache.sqlite" from your cache directory.

```
import fastf1

weekend = fastf1.get_session(2021, 'Brazil')
weekend.data['raceName'] = "São Paulo Grand Prix"
session = fastf1.core.Session(weekend, 'Practice 1')
session.load_laps()
```

Valid names to use for the session name for this weekend are:

'Practice 1', 'Qualifying', 'Practice 2', 'Sprint Qualifying', 'Race'

**Comment by hotlapmode** [comment]
> Hi, sorry for the inconvenience. For some reason, the official name of the GP is "São Paulo Grand Prix" this year and not "Brazilian Grand Prix". The online database from which I'm pulling the GP names does not have the correct name, though. Therefore, FastF1 cannot generate the correct API path for downloading the data.
> 
> Until the database has been updated (I can't do that but I have notified them) you need to use the workaround below to load any session for this weekend. Even after the database has been updated, it'll only work without the workaround once you have deleted the file "fastf1_http_cache.sqlite" from your cache directory.
> 
> ```
> import fastf1
> 
> weekend = fastf1.get_session(2021, 'Brazil')
> weekend.data['raceName'] = "São Paulo Grand Prix"
> session = fastf1.core.Session(weekend, 'Practice 1')
> session.load_laps()
> ```
> 
> Valid names to use for the session name for this weekend are:
> 
> 'Practice 1', 'Qualifying', 'Practice 2', 'Sprint Qualifying', 'Race'

Thank you. Have a nice evening

**Comment by theOehrly** [comment]
The database has been updated already. That was quick. The workaround is therefore not necessary any more.

If you still have issues, please delete "fastf1_http_cache.sqlite" from your cache directory and try again.

**Comment by hotlapmode** [comment]
now it's loading data from FP1 even when i insert "session = ff1.core.Session(weekend, 'Qualifying')"

**Comment by theOehrly** [comment]
That's a bit weird. It's not happening for me when I try it. May be try deleting the cache folder for this weekend and try again. But I'm not sure how this would be caused.

Also, you can just use the "normal" method again.

**Comment by SMF192** [comment]
I can't access the data for qualifying yet, I get the usual error message for when the data doesn't exist: "SessionNotAvailableError: No data for this session! Are you sure this session wasn't cancelled?" 

Is that just because the database isn't updated yet and I need to be patient?

**Comment by hotlapmode** [comment]
still not working. i don't know what it is at this point, it's not even giving me the FP1 data now it just goes blank

![Figure_12](https://user-images.githubusercontent.com/67686869/141535833-a046f5c2-8075-4ac3-97a1-536bdfcec021.png)

**Comment by theOehrly** [comment]
The database was updated already. **Please remember to delete the "fastf1_http_cache.sqlite" from your cache directory**

This code works fine for me

```
import matplotlib.pyplot as plt

import fastf1
from fastf1 import plotting

plotting.setup_mpl()
fastf1.Cache.enable_cache('tmp_cache')

session = fastf1.get_session(2021, 'Brazil', 'Q')
laps = session.load_laps(with_telemetry=True)

ham = laps.pick_driver('HAM').pick_fastest().get_car_data().add_distance()
ver = laps.pick_driver('VER').pick_fastest().get_car_data().add_distance()

plt.plot(ver['Distance'], ver['Speed'], color=plotting.team_color('RBR'))
plt.plot(ham['Distance'], ham['Speed'], color=plotting.team_color('MER'))
plt.show()
```

If it does not work for you, try to run with no cache. If that fixes it, it's a caching issue.

**Comment by SMF192** [comment]
> The database was updated already. **Please remember to delete the "fastf1_http_cache.sqlite" from your cache directory**
> 
> This code works fine for me
> 
> ```
> import matplotlib.pyplot as plt
> 
> import fastf1
> from fastf1 import plotting
> 
> plotting.setup_mpl()
> fastf1.Cache.enable_cache('tmp_cache')
> 
> session = fastf1.get_session(2021, 'Brazil', 'Q')
> laps = session.load_laps(with_telemetry=True)
> 
> ham = laps.pick_driver('HAM').pick_fastest().get_car_data().add_distance()
> ver = laps.pick_driver('VER').pick_fastest().get_car_data().add_distance()
> 
> plt.plot(ver['Distance'], ver['Speed'], color=plotting.team_color('RBR'))
> plt.plot(ham['Distance'], ham['Speed'], color=plotting.team_color('MER'))
> plt.show()
> ```
> 
> If it does not work for you, try to run with no cache. If that fixes it, it's a caching issue.

Sadly, I just get hit with "SessionNotAvailableError". I've deleted that cache file and I've tried running it with no cache too.

**Comment by theOehrly** [comment]
Can you post a minimal snippet of code that does not run for you?

**Comment by hotlapmode** [comment]
> The database was updated already. **Please remember to delete the "fastf1_http_cache.sqlite" from your cache directory**
> 
> This code works fine for me
> 
> ```
> import matplotlib.pyplot as plt
> 
> import fastf1
> from fastf1 import plotting
> 
> plotting.setup_mpl()
> fastf1.Cache.enable_cache('tmp_cache')
> 
> session = fastf1.get_session(2021, 'Brazil', 'Q')
> laps = session.load_laps(with_telemetry=True)
> 
> ham = laps.pick_driver('HAM').pick_fastest().get_car_data().add_distance()
> ver = laps.pick_driver('VER').pick_fastest().get_car_data().add_distance()
> 
> plt.plot(ver['Distance'], ver['Speed'], color=plotting.team_color('RBR'))
> plt.plot(ham['Distance'], ham['Speed'], color=plotting.team_color('MER'))
> plt.show()
> ```
> 
> If it does not work for you, try to run with no cache. If that fixes it, it's a caching issue.

still doesn't work for me. tried running without cache, eliminating "fastf1_http_cache.sqlite", and running different codes but nothing to do unfortunately

**Comment by theOehrly** [comment]
I've now tried it in a new clean python environment, and it works as expected. I don't know what it is if it's not a caching issue on your side. But it's at least two people now where it's not working.

Can you send me the full output of our script please?

**Comment by hotlapmode** [comment]
### import fastf1 as ff1
from fastf1 import plotting
from matplotlib import pyplot as plt
 
plotting.setup_mpl()
 
ff1.Cache.enable_cache(r"C:\Users\Dropbox\MyPC\Desktop\cache")
 
weekend = ff1.get_session(2021, 'Brazil')
weekend.data['raceName'] = "São Paulo Grand Prix"
session = ff1.core.Session(weekend, 'Q')
laps = session.load_laps(with_telemetry=True)
laps_ham = laps.pick_driver('HAM')
laps_ver = laps.pick_driver('VER')

fastest_ham = laps_ham.pick_fastest()
fastest_ver = laps_ver.pick_fastest()

telemetry_ham = fastest_ham.get_car_data().add_distance()
telemetry_ver = fastest_ver.get_car_data().add_distance()

fig, ax = plt.subplots()
fig.suptitle("Sao Paolo GP | Qualifying Telemetry")
ax.plot(telemetry_ham['Distance'], telemetry_ham['Speed'], label='HAM', color='cyan')
ax.plot(telemetry_ver['Distance'], telemetry_ver['Speed'], label='VER', color='blue')
ax.set(xlabel='Distance')
ax.set(ylabel='Speed')
ax.legend(loc="lower right")

plt.show()

this is the code i'm running at the moment. this is the result when i run it in python:
![Screenshot 11_12_2021 11_03_12 PM](https://user-images.githubusercontent.com/67686869/141539944-5fbaf560-fbb8-49a3-b398-cd903e2e92e0.png)

**Comment by theOehrly** [comment]
You're using FastF1 v2.1.8! You absolutely need the latest version because of the changed schedule of the sprint qualifying weekend. See the notes at the top of the readme file. You might need to delete the cache file again after updating.

I'm sorry for these inconveniences, but I just haven't had time to fix the sprint schedule problems universally. That means, the latest version is currently often required because I need to include patches for these specific weekends

**Comment by hotlapmode** [comment]
ahh that's why. thanks for your help. i'll try to install the latest version and i'll get back to you

**Comment by SMF192** [comment]
I wasn't using the latest version either, apologies for that. I'm struggling to update to v2.1.11 though. When I re-run pip install fastf1 I only get v2.1.9

**Comment by theOehrly** [comment]
> 
> 
> I wasn't using the latest version either, apologies for that. I'm struggling to update to v2.1.11 though. When I re-run pip install fastf1 I only get v2.1.9

You need to use `pip install --upgrade fastf1`

**Comment by hotlapmode** [comment]
it's all good now! thanks for the help again
