### ISSUE TITLE
[BUG] fastf1.events returning incorrect country data for some events.

### ISSUE THREAD

**Issue by MyosotisLz** [theOehrly/Fast-F1#591]
### Describe the issue:

For some particular races, fastf1.get_event() returns unexpected country names. Particularly, I've seen this with Miami GP and Emilia Romagnia GP. I'm not sure if this is a feature or a bug, but having accurate country names is crucial for the purpose I'm using it for.

### Reproduce the code example:

```python
event1=fastf1.get_event(gp=6, year=2024)
event2=fastf1.get_event(gp=7, year=2024)
print(event1['Country'])
print(event2['Country'])
```

### Error message:

```shell
Miami
Emilia-Romagna
```

**Comment by theOehrly** [comment]
That was not intentional. It's fixed now in the data backend, so it should just work for you now and return "United States" and "Italy" respectively.
