### ISSUE TITLE
'AttributeError: 'Weekend' object has no attribute 'load_laps'

### ISSUE THREAD

**Issue by pixelflowxyz** [theOehrly/Fast-F1#60]
Hi! Just found this and I'm so glad I've found it - it's what I've been after for years!

Just getting to grips with it though, and I'm having an issue getting date from FP1 earlier today.

`ff1.Cache.enable_cache('cache') 
fp1 = ff1.get_session(2021, 'Qatar', 'P1')
laps = fp1.load_laps(with_telemetry=True)`

results in:
```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/dp/q2r05qm94rzdq3xzvlncs5ww0000gn/T/ipykernel_11901/3366563616.py in <module>
      2 ff1.Cache.enable_cache('cache')
      3 fp1 = ff1.get_session(2021, 'Qatar', 'P1')
----> 4 laps = fp1.load_laps(with_telemetry=True)

AttributeError: 'Weekend' object has no attribute 'load_laps'```



Any help would be much appreciated - it's probably a mistake on my end anyway!

**Comment by theOehrly** [comment]
You nee to use 'FP1' in get_session, not 'P1'. 
As 'P1' is not a valid session, get_session returns an instance of `Weekend` and not of `Session`.
