### ISSUE TITLE
Qatar GP FP2 Telemetry Issue

### ISSUE THREAD

**Issue by bambz96** [theOehrly/Fast-F1#61]
When trying to retrieve telemetry data from the FP2 session for the Qatar GP, I get the following error: 

`Traceback (most recent call last):`
 ` File "<string>", line 1, in <module>`
  `File "c:\Users\longn\source\repos\f1-copilot\api\env\lib\site-packages\fastf1\core.py", line 1698, in get_telemetry
    drv_ahead = car_data.iloc[1:-1].add_driver_ahead() \`
  `File "c:\Users\longn\source\repos\f1-copilot\api\env\lib\site-packages\fastf1\core.py", line 825, in add_driver_ahead
    drv_ahead, dist = self.calculate_driver_ahead()`
 ` File "c:\Users\longn\source\repos\f1-copilot\api\env\lib\site-packages\fastf1\core.py", line 906, in calculate_driver_ahead
    lap_n_before = min(drv_laps['LapNumber'])`
`ValueError: min() arg is an empty sequence`

Code to recreate: 
`DIRECTORY = os.path.abspath("./fastf1cache")`
`ff1.Cache.enable_cache(DIRECTORY)  # optional but recommended`
`session = ff1.get_session(2021, 20, "FP2")`
`laps = session.load_laps(with_telemetry=True).pick_driver("HAM")`
`lap = laps.loc[laps['LapNumber'] == 19]`
`tel = lap.telemetry`

This code works fine for FP1. 

TIA!

**Comment by bambz96** [comment]
I did some digging and it appears the root cause of this issues is that car 9 (Nikita Mazepin) didn't do any laps and so `drv_laps['LapNumber']` returns an empty dataframe. Thus getting the min lap number causes an error. 

I've worked around this by making my own `get_telemetry` function that doesn't merge in the driver ahead fields (I'm not using them): 

`def get_telemetry_workaround(lap): `
`    pos_data = lap.get_pos_data(pad=1, pad_side='both')`
`    car_data = lap.get_car_data(pad=1, pad_side='both')`
`    car_data = car_data.add_distance().add_relative_distance()`
`    merged = pos_data.merge_channels(car_data)`
`    return merged.slice_by_lap(lap, interpolate_edges=True)`

**Comment by bambz96** [comment]
I've submitted a PR (#62) that I believe fixes this issue.

**Comment by theOehrly** [comment]
You are correct, this seems to be the problem.

Just as a note, you know that it is generally not recommended to use `.telemetry` if you don't need telemetry and position data merged?

**Comment by bambz96** [comment]
Thanks for the note, yeah I was being lazy before and using `.telemetry` for convenience sake.
