### ISSUE TITLE
Help with XYZ position

### ISSUE THREAD

**Issue by petercubic** [theOehrly/Fast-F1#64]
This API has been super helpful for me to start creating some 3D data visualizations. However, I am just trying to figure out a more accurate way to match up the XYZ positions to GPS coordinates or Latitude/Longitude. Do you have any details on how this position is calculated?

Thanks again.

**Comment by theOehrly** [comment]
There's not much that I know about it.
The coordinates simply seem to be cartesian coordinates. Their unit is 1/3 of a meter if I remember correctly (at least for the 2021 season).
I don't know whether the position of the origin has any special meaning or if it is chosen arbitrarily.
Therefore, I'm not sure whether you can automatically convert the coordinates to GPS positions. I fear that you'd need to manually align them with satellite images of the track.

**Comment by petercubic** [comment]
Ok, that makes a lot of sense. It seems like the origin point (0,0,0) for the data is not too far from the garages. Maybe they are referencing an antenna location as origin?

Also, I feel like I saw GPS coordinates for each track as I was going through API references, but I cannot seem to find where that was. I am curious if that GPS location might match with the "antenna" position. If you know of anything like a track GPS position that I would appreciate it.

Thanks again for the API

**Comment by theOehrly** [comment]
The only GPS coordinates that I'm aware of are in `session.weekend.data['Circuit']['Location']`. But that data is provided by Ergast, so it is unrelated to the cars' position data. Also, it looks like a rather coarse location, considering that very few decimal places are given.

Consider that those coordinates are intended for the track animation in the app. For that, there's no need for syncing them automatically to actual GPS coordinates.
I don't want to say it's impossible, that there is some information hidden somewhere that allows you to do that. But I'd say it's unlikely.

**Comment by petercubic** [comment]
Yup, you're right. It seems to just be a general GPS position.

I have some other thoughts on how to match the positions to coordinates, but its helpful to know I'm not missing something obvious.

Thanks again!
