### ISSUE TITLE
[BUG] Error converting live timing txt into operable data

### ISSUE THREAD

**Issue by ChemiF1** [theOehrly/Fast-F1#642]
### Describe the issue:

During this weekend i tried to get the data using the Live Timing info you posted on the documentation. The live data process was correct, but at the end, when i tried to use this data this error emerged

No data was avaliable there, so i don´t know what i´m doing wrong. 

### Reproduce the code example:

```python
![image](https://github.com/user-attachments/assets/dfc185ef-c641-449c-b4a4-9ddc6d591b38)
```

**Comment by ChemiF1** [comment]
I send you the image of the code, because i hadn´t on this PC

![image](https://github.com/user-attachments/assets/dfc185ef-c641-449c-b4a4-9ddc6d591b38)

Sorry if i didn´t follow the process, it´s my first reporting here, so any correction or comment will be very welcome

Thank you for such a wonderful tool you gave to people like me

**Comment by theOehrly** [comment]
``race.load(...)`` does not return anything. So you should not assign the result of that function call to ``race`` again and instead just do

```
race = fastf1.get_session(2024, "Singapur", 3)
race.load(livedata=livedata)
print(race)
```

This has nothing to do with using pre-recorded livedata. 

You can have a look at the examples and the "getting started" section in the documentation for to find some working examples:
https://docs.fastf1.dev/gen_modules/examples_gallery/index.html
https://docs.fastf1.dev/examples/index.html
