### ISSUE TITLE
[BUG] Belguim 2023 Data for Race contains Value 'True' for 'FreshTyre' column for all entries

### ISSUE THREAD

**Issue by mistryvivek** [theOehrly/Fast-F1#655]
### Describe the issue:

![image](https://github.com/user-attachments/assets/a8447ec3-7bd4-43d3-aef5-ce7a2a93880e)

### Reproduce the code example:

```python
data = f1.get_session(2023, "FORMULA 1 MSC CRUISES BELGUIM GRAND PRIX", "Race")
data.load()
testDf = data.laps
```

**Comment by mistryvivek** [comment]
Doesn't that infer that they had a fresh tyre on every single lap of the race.

Correct me if I have misunderstood

**Comment by Casper-Guo** [comment]
If you look at the data definition in the documentation:

> FreshTyre (bool): Tyre had TyreLife=0 at stint start, i.e. was a new tire

So it is expected that this feature will be consistent through each stint
