### ISSUE TITLE
[BUG] Missing rounds 0-9 in 2024 season schedule

### ISSUE THREAD

**Issue by borolepratik** [theOehrly/Fast-F1#656]
### Describe the issue:

Missing rounds 0-9 in the schedule for the 2024 season using FastF1 `v3.4.3`.
![image](https://github.com/user-attachments/assets/d23399ff-34a4-4214-b08e-75b6780cf0fb)

`ValueError: Invalid round: 2` shown when trying to load any session for round 2 in 2024.
![image](https://github.com/user-attachments/assets/216b0fb5-f952-4eff-8c22-65cfde74543d)

### Reproduce the code example:

```python
import fastf1
fastf1.get_event_schedule(2024)
```

### Error message:

```shell
No error message, but rather incomplete data (see screenshot).
```

**Comment by Casper-Guo** [comment]
That's really odd. I am unable to reproduce. Is this a persistent issue?

**Comment by theOehrly** [comment]
This can be reproduced by forcing the usage of the F1 Livetiming API as schedule backend:

```
fastf1.get_event_schedule(2024, backend='livetiming')
```

There is not really anything that I can do about the data on their schedule endpoint being incorrect. This is an artifact that remains from earlier in the year when F1 partially broke their API by doing a server migration. It is still broken and while I can work around the historic endpoints by providing a mirror, this endpoint changes constantly and would require a much more complicated solution to fix. I don't have the time for that, when there is a working backend available.

The question that we need to solve here is, why does FastF1 fall back to the alternate data source in the first place? Does it work, if you disable caching: ``fastf1.Cache.set_disabled()``?

Else, can you please set the log level to debug, using ``fastf1.set_log_level('DEBUG')`` while the Cache is disabled and post the output of that?

**Comment by borolepratik** [comment]
```python
import fastf1
fastf1.Cache.set_disabled()
fastf1.set_log_level('DEBUG')

fastf1.get_event_schedule(2024)
```

Logs:
```
logger      WARNING 	Failed to load schedule from FastF1 backend!
logger        DEBUG 	Traceback for failure in FastF1 schedule
Traceback (most recent call last):
  File "/opt/python/envs/customPyEnv311/lib/python3.11/site-packages/fastf1/logger.py", line 151, in __wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/envs/customPyEnv311/lib/python3.11/site-packages/fastf1/events.py", line 587, in _get_schedule_ff1
    json_data = json.loads(response.text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
_api           INFO 	Fetching season schedule...
```

```python
# Parameters
year = 2024
grand_prix = 2
session = 1

# Load session data
session = fastf1.get_session(year, grand_prix, session)
session.load()
```

Logs:
```
logger      WARNING 	Failed to load schedule from FastF1 backend!
logger        DEBUG 	Traceback for failure in FastF1 schedule
Traceback (most recent call last):
  File "/opt/python/envs/customPyEnv311/lib/python3.11/site-packages/fastf1/logger.py", line 151, in __wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/envs/customPyEnv311/lib/python3.11/site-packages/fastf1/events.py", line 587, in _get_schedule_ff1
    json_data = json.loads(response.text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
_api           INFO 	Fetching season schedule...
```

**Comment by theOehrly** [comment]
Ok that looks like you're getting a response from the server but it likely is some kind of error response and therefore, the content is not valid JSON.

The "API" for this is just JSON files on Github. The relevant URL here specifically is 

`https://raw.githubusercontent.com/theOehrly/f1schedule/master/schedule_2024.json`

Are you a bit familiar with the Python requests package? You can try and check what kind of response you are getting from the server. Something like

```
import requests

requests.get("https://raw.githubusercontent.com/theOehrly/f1schedule/master/schedule_2024.json")
```

And then see what kind of content and status code the response has.

**Comment by theOehrly** [comment]
Looks like Github is blocking this request from you specifically, for some reason. This isn't a widespread problem and hasn't come up before. I can only speculate what might be going on here. Are you using some kind of public VPN or proxy server? Then maybe try without that. This problem really is outside my control.

**Comment by ishim0226** [comment]
I encountered the same problem running fastf1 on aws lambda. And this does not reproduce as long as I run it on my laptop.

Then I rewrote the user-agent based on the following article and now the request succeeds.
https://github.com/dask/dask-sphinx-theme/pull/91

o request with user-agent: python-requests/2.32.3 on my laptop
x request with user-agent: python-requests/2.32.3 on lambda
o request with user-agent: ‘fastf1’ on lambda

From these it seems that the problem is due to some change on the github side and that they are rejecting some requests depending on the combination of user-agent and source (e.g. IP). And this change is from just recently. It is not known whether this is permanent or temporary.

ref: debug code
```
    import requests, json

    url = f"https://raw.githubusercontent.com/theOehrly/f1schedule/master/schedule_{year}.json"
    res = requests.get(
        url,
        headers={"User-Agent": "fastf1"},
    )
    print(f"request.headers: {res.request.headers}")
    print(f"status: {res.status_code}, reason:{res.reason}")
```

**Comment by theOehrly** [comment]
@ishim0226 thank you, that was very valuable information

@borolepratik and others that are affected, I've made a new patch release that now uses a custom user agent for these requests. Please let me know if this works for you or if there are still problems.

**Comment by borolepratik** [comment]
@theOehrly i can confirm that v3.4.4 fixes this issue on my datalore notebook. Thank you 🙌

**Comment by Casper-Guo** [comment]
@theOehrly I have updated to 3.4.4 and something quite strange just happened.

I have a data refresh job on EC2 scheduled to run with cron and it just failed with the above-mentioned error message.

I logged in to the instance and ran it manually. It worked.

I will try to reproduce this. Just want to bring it to your attention

**Comment by theOehrly** [comment]
@Casper-Guo I had kind of feared that this might not be the end of that problem. Please let me know, if you figure out anything more.

I might just move this to "proper" hosting. It's not that much work. But it's less future-proof. For example, if I stop paying for the domain for whatever reason, the data is gone. And it's a bit more maintenance.

Maybe it's got to the point where there are just too many requests made to get the schedule from Github. But to be honest, I have absolutely no idea how many requests there currently are by FastF1 users.

**Comment by Casper-Guo** [comment]
I'll see if it occurs again over the next few days. Trying to debug this on an EC2 instance will be a little annoying but if it persists I will have some time next week to properly look into it
