### ISSUE TITLE
Lap times deleted

### ISSUE THREAD

**Issue by psychemedia** [theOehrly/Fast-F1#660]
### Proposed new feature or change:

I note in the FAQ a note about not being able to identify deleted laptimes. I just spotted amongst the FIA event and timing PDFs a document that reports on the Race control messages issued during each session ([example](https://www.fia.com/events/fia-formula-one-world-championship/season-2024/qatar-grand-prix/eventtiming-information)), and these seem to include references to deleted laptimes:

<img width="889" alt="image" src="https://github.com/user-attachments/assets/1a54d553-647a-4ec8-9173-5b5d1b93b1df">

I don't know if there are any FIA document scrapers out there that publish scrapes of these documents via an API. Gen AI tools such as Claude.AI seem to be able to extract the data into a JSON object easily enough; I'm not sure if locally run models can also extract the data reliably and accuratley into a structured form.

**Comment by theOehrly** [comment]
Race control messages are available from the API and this is implemented since quite some time. The documentation is out of date here. When I pull the data, I get

```
LapNumber                LapTime  Deleted                   DeletedReason
153        1.0                    NaT    False                                
154        2.0 0 days 00:02:22.483000    False                                
155        3.0 0 days 00:02:18.215000    False                                
156        4.0 0 days 00:02:22.341000    False                                
157        5.0 0 days 00:01:32.386000     True  TRACK LIMITS AT TURN 13 LAP 5 
158        6.0 0 days 00:01:29.044000    False                                
159        7.0 0 days 00:01:28.057000    False                                
```

I'll update the docs. I had completely forgotten that this is noted there. Thanks for the hint.

**Comment by theOehrly** [comment]
For now, I'll just remove this outdated information from the documentation.

https://docs.fastf1.dev/core.html#fastf1.core.Laps mentions that ``Deleted`` and ``DeletedReason`` are available as columns of the ``Laps`` DataFrame. Like many other things, it is not easy to find.

A big overhaul of the documentation is in the works, and I need to find some way to better communicate the capabilities and limitations of FastF1 there.
