### ISSUE TITLE
[BUG] Anomalous track status codes

### ISSUE THREAD

**Issue by Carol52x** [theOehrly/Fast-F1#664]
### Describe the issue:

There seems to be a mismatch of the track status codes returned by `Session.laps.pick_track_status()` and `Session.track_status`. Or are these supposed to be different?

### Reproduce the code example:

```python
print(Session.laps.pick_track_status("123456789", how="any")['TrackStatus'])
print(Session.track_status)
```

### Error message:

```shell
0        12
1       126
2       671
3         1
4         1
       ...
1030      1
1031      1
1032      1
1033     12
1034      1



0         0 days 00:00:00      1     AllClear
1  0 days 00:57:38.172000      2       Yellow
2  0 days 00:57:43.506000      1     AllClear
3  0 days 00:58:28.274000      2       Yellow
4  0 days 00:59:06.540000      6  VSCDeployed
5  0 days 01:00:53.361000      7    VSCEnding
6  0 days 01:01:03.708000      1     AllClear
7  0 days 01:42:34.999000      2       Yellow
8  0 days 01:42:38.500000      1     AllClear
9  0 days 01:42:39.958000      2       Yellow
10 0 days 01:42:46.076000      1     AllClear
11 0 days 02:22:08.652000      2       Yellow
12 0 days 02:22:34.092000      1     AllClear
```

**Comment by theOehrly** [comment]
This looks good to me. The track status codes that are associated with each individual lap are all status codes that occurred during this lap. For example, if a lap was set partially under green and yellow flag, it will have ``12`` as track status. Status codes are simply concatenated.

I have annotated the indices from the lap to the track status messages below. Maybe this helps with understanding.
![grafik](https://github.com/user-attachments/assets/e4a1a18f-6853-49e8-bf0f-2c7c1fcf8872)
