### ISSUE TITLE
[BUG] No errors being thrown when accessing empty data from get_driver()

### ISSUE THREAD

**Issue by Carol52x** [theOehrly/Fast-F1#668]
### Describe the issue:

For the 2018 season and first 6 races of 2019 (could also happen in other seasons i believe, haven't checked though), livetiming api doesn't support keys `Reference`, `CountryCode` and `HeadshotUrl`. When accessing these from `session.get_driver()`, nothing happens because these keys exist but their values are empty. I think it's beneficial to raise an exception when these are accessed, or have a fallback source to populate these keys instead.

### Reproduce the code example:

```python
session = fastf1.get_session(2018, 21, 5)
print(session.get_driver("HAM"))
print(session.get_driver("HAM")['HeadshotUrl'])
```

### Error message:

```shell
DriverNumber                              44
BroadcastName                     L HAMILTON
Abbreviation                             HAM
DriverId                            hamilton
TeamName                            Mercedes
TeamColor                             00D2BE
TeamId                              mercedes
FirstName                              Lewis
LastName                            Hamilton
FullName                      Lewis Hamilton
HeadshotUrl
CountryCode
Position                                 1.0
ClassifiedPosition                         1
GridPosition                             1.0
Q1                                       NaT
Q2                                       NaT
Q3                                       NaT
Time                  0 days 01:39:40.382000
Status                              Finished
Points                                  25.0

*No output*
```

**Comment by theOehrly** [comment]
``.get_driver`` returns a ``DriverResult`` object (https://docs.fastf1.dev/core.html#fastf1.core.DriverResult) which is a subclass of a Pandas ``Series`` object. It is very uncommon to raise errors on data access in DataFrames or Series if the data is not populated. Therefore, I think that this would confuse people more than it would be helpful overall.

Second, while it technically is possible to intercept the data access and raise and error, doing this properly is very difficult. Pandas accesses the data internally as well when creating DataFrames and during a lot of function calls where you don't actually want that specific bit of missing data returned. It would therefore be necessary to somehow differentiated between internal access and direct user access. Doing this is a lot of work for what I think is a very small benefit. 

Overall, I am very much against raising an error here. I'll close this as won't fix. If many others chime in and prefer to raise an error here, I'll give this some more thought.
