### ISSUE TITLE
weather_data for 2021 Season is Empty

### ISSUE THREAD

**Issue by nbreen** [theOehrly/Fast-F1#68]
Not sure if I'm doing something wrong or if this is intentional but I didn't see it denoted anywhere. I am looking at the data for the 2021 season and the weather_data always returns an empty data frame `print(weekend.get_race().weather_data.size)` returns `Empty DataFrame
Columns: []
Index: [] `

**Comment by theOehrly** [comment]
Sorry, it's not obvious and not documented actually. But weather data is only loaded together with all the lap data. So you need to call `Session.load_laps` first.

**Comment by nbreen** [comment]
Oh no worries. That makes sense. Thanks!
