### ISSUE TITLE
Error when loading laps of Imola 2021 FP1 

### ISSUE THREAD

**Issue by Henning-J** [theOehrly/Fast-F1#73]
Hi,

when I try to load the laps of the FP1 of Imola 2021 I get the following error:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-7-5489bed78b93> in <module>
      4 
      5 session = ff1.get_session(2021, "Imola", "FP1")
----> 6 laps = session.load_laps(with_telemetry=False)

~/anaconda3/lib/python3.8/site-packages/fastf1/core.py in load_laps(self, with_telemetry, livedata)
   1335             df = result if 'df' not in vars() else pd.concat([df, result], sort=False)  # noqa: F821
   1336 
-> 1337         laps = df.reset_index(drop=True)  # noqa: F821
   1338         laps.rename(columns={'TotalLaps': 'TyreLife',
   1339                              'NumberOfPitStops': 'Stint',

UnboundLocalError: local variable 'df' referenced before assignment

The following block of code is a minimum example that causes the error.

import fastf1 as ff1
from fastf1 import plotting
from fastf1.core import Laps

session = ff1.get_session(2021, "Imola", "FP1")
laps = session.load_laps()

I hope someone can help me :)

**Comment by theOehrly** [comment]
There were major technical problems during FP1 in Imola. Therefore, there is actually no data available for this session. See issue #21. I've improved the error handling now though, so this is more obvious.
