### ISSUE TITLE
Error when loading laps of Austrian GP 2020 FP1

### ISSUE THREAD

**Issue by Henning-J** [theOehrly/Fast-F1#74]
Hi,

when I try to load the laps of the FP1 of the Austrian GP 2020 I get the following error:

IndexError                                Traceback (most recent call last)
<ipython-input-12-3619d2df0f6f> in <module>
      4 
      5 session = ff1.get_session(2020, "Austria", "FP1")
----> 6 laps = session.load_laps()

~/anaconda3/lib/python3.8/site-packages/fastf1/core.py in load_laps(self, with_telemetry, livedata)
   1306             if pd.isna(result['PitInTime'].iloc[-1]) and not only_one_lap:
   1307                 if not pd.isna(result['Time'].iloc[-1]):
-> 1308                     next_status = self.session_status[
   1309                         self.session_status['Time'] > result['Time'].iloc[-1]
   1310                     ].iloc[0]

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    877 
    878             maybe_callable = com.apply_if_callable(key, self.obj)
--> 879             return self._getitem_axis(maybe_callable, axis=axis)
    880 
    881     def _is_scalar_access(self, key: Tuple):

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1494 
   1495             # validate the location
-> 1496             self._validate_integer(key, axis)
   1497 
   1498             return self.obj._ixs(key, axis=axis)

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in _validate_integer(self, key, axis)
   1435         len_axis = len(self.obj._get_axis(axis))
   1436         if key >= len_axis or key < -len_axis:
-> 1437             raise IndexError("single positional indexer is out-of-bounds")
   1438 
   1439     # -------------------------------------------------------------------

IndexError: single positional indexer is out-of-bounds

The following block of code is a minimum example that causes the error.

import fastf1 as ff1
from fastf1 import plotting
from fastf1.core import Laps

session = ff1.get_session(2020, "Austria", "FP1")
laps = session.load_laps()

I hope someone can help me :)

**Comment by theOehrly** [comment]
Can confirm this is a bug in FastF1. I'm looking into it.

**Comment by Henning-J** [comment]
Thank you :)
