### ISSUE TITLE
Wrong value for RainFall in weather data

### ISSUE THREAD

**Issue by OmaMansou** [theOehrly/Fast-F1#76]
The value for Rain Fall in the weather data seems to always be set to True, even for races where there wasn't any hint of rain (Bahrain, Monza 2019...).

Thank you.

**Comment by theOehrly** [comment]
Yep, that's a bug in the api parser. Will be fixed. 
Thanks

**Comment by theOehrly** [comment]
This is now fixed in the first pre-release version of v2.2 (see https://github.com/theOehrly/Fast-F1/discussions/105)

The stable release including this bug fix will most likely be released before the first race weekend.
