### ISSUE TITLE
Generate Base String

### ISSUE THREAD

**Issue by siddharth-tewari** [theOehrly/Fast-F1#80]
@theOehrly Hello, I need to make the base string for "make_path" function. Can you help that how can it be made automatically?
<b>Code</b>
```python
import fastf1

path = fastf1.api.make_path('Italian Grand Prix', '2019-09-08', 'Race', '2019-09-08')
print(path)
```

**Comment by theOehrly** [comment]
Can you be more clear? I don't really understand what your question is.

**Comment by siddharth-tewari** [comment]
@theOehrly I have a repository <a href=https://github.com/siddharth-tewari/F1-TeamRadio>https://github.com/siddharth-tewari/F1-TeamRadio</a> and it gives out the Team Radio, Race Control Messages and Drivers List for the latest happened race. 
I need to add a functionality to access data for older races.

**Comment by theOehrly** [comment]
@siddharth-tewari  ok, but I don't see the problem or why this would be an issue with fastf1?
But, after quickly taking a lookat your code, why don't you use fastf1 to create a Session object? Then you can use ``api.fetch_page`` to dowload the 'TeamRadio.jsonStream' file for any session. The rest is on you then. This takes all the session and api path stuff off of you.

**Comment by siddharth-tewari** [comment]
Hello, can you fix this if possible?

```python
import fastf1
import fastf1 as ff1

year = input("Enter the Year: ")
race = input("Enter the Race Number/Name: ")

if type(race) == int:
    raceName = race
    
elif type(race) == float:
    raceName = race

elif type(race) == str:
    raceName = "'" + race + "'"

weekend = ff1.get_session(year, raceName)

lap = fastf1.core.Session(weekend, 'Race')
options = fastf1.api.pages= { 'race_control_messages': 'RaceControlMessages.json', 'team_radio': 'TeamRadio.jsonStream'}

link = fastf1.api.fetch_page(lap, 'team_radio')
print(link)
```
