### ISSUE TITLE
FP2 data not loading for weekends with Sprint Qualifying

### ISSUE THREAD

**Issue by raghav-vish** [theOehrly/Fast-F1#81]
As mentioned in the title, for the weekends that had the Sprint format, namely Silverstone, Monza and Interlagos, the FP2 sessions don't load and returns the SessionNotAvailable Error.

This may be due to FP2 being on Saturday rather than Friday for those weekends.

**Comment by theOehrly** [comment]
This really should work. Sprint quali weekends are patched in recent releases of FastF1. Therefore, please make sure that you are using the latest version.

**Comment by raghav-vish** [comment]
My bad, it works fine. Although my issue didn't go away when I updated to the newest version. It went away when I entered the year as an integer rather than a string, which is weird but my code works fine now.
