### ISSUE TITLE
Cannot load car data and position data anymore

### ISSUE THREAD

**Issue by TerminatorPlati** [theOehrly/Fast-F1#9]
As the title suggests, the program does not work for FP1, FP3 and Q of the Sakhir Grand Prix. The return of the data fetch is `None`

**Comment by theOehrly** [comment]
Can you verify that it doesn't work for any session of any event, not just the Sakhir Grand Prix? Make sure to not have any caching enabled when testing this.

**Comment by theOehrly** [comment]
Additionally, if you have an F1 TV subscription, could you check whether the live timing replay fully works for you in the official app? Including track map and speed, rpm, ...

**Comment by TerminatorPlati** [comment]
in the formula 1 app, only live timing works for this GP, but not telemetry and track position. For the other GPs the script works (obviously tested without cache activated). The thing that doesn't come back to me are the FP2s, in fact, although the data is missing in the app, the script works without problems.

**Comment by theOehrly** [comment]
Something is very weird here... I cannot load any session from the last five races (haven't checked further back yet). I also can not load FP2 from this weekend. I was able to load the latest race yesterday but it fails today.

It's certainly not a simple bug. The api really does not return any data.

I think either the F1 api has server issues or they have simply turned off downloading the data after a session. The second option seems a bit weird as this breaks the telemetry replay of their own app too. I guess we need to wait and see for a while. This whole thing started saturday evening (UTC) as far as I can tell. I was doing some developemnt work when position data started to fail loading. Car data was still working then but is not working anymore now.

I'll keep a very close eye on this but for now I do not have a fix. The data is simply not there as it seems.

**Comment by theOehrly** [comment]
<blockquote class="twitter-tweet" data-conversation="none" data-dnt="true"><p lang="en" dir="ltr">We are aware that some Live Timing Data is no longer available, we are working on a solution. This information in unlikely to be available until the end of the year, and on any existing replays back to 2018. Live Timing data will continue to be available during Live Sessions.</p>&mdash; The Official F1® Help Channel (@F1Help) <a href="https://twitter.com/F1Help/status/1335939396240093185?ref_src=twsrc%5Etfw">December 7, 2020</a></blockquote>

The problem has been acknowledged by the official F1 Help Channel on Twitter. It sounds like there won't be a solution this year anymore according to them. There is nothing I can do to work around this.

It looks like the data is briefly available after a session. So it may be possible to load it with caching enabled right after the session ends. Then you are able to work with the locally cached data.
