### ISSUE TITLE
[ENH] <Download Data as txt file>

### ISSUE THREAD

**Issue by siddharth-tewari** [theOehrly/Fast-F1#97]
### Proposed new feature or change:

Hello, I am having a idea for feature a feature which would download data given as input by the user.

<b>Example Code</b>
```python
import fastf1 as ff1

ff1.Cache.enable_cache('cache')
race = ff1.get_session(2021, 'Abu Dhabi GP', 'R')
data_download = race.Download('TeamRadio.jsonStream' , 'SessionData.json')
```
Then it will save data into AbuDhabiGP2021TeamRadio.json and AbuDhabiGP2021SessionData.json

**Comment by theOehrly** [comment]
I don't see a necessity to add this functionality specifically. You can use `api.fetch_page` to get the text content of these files as string.
At that point, if you really want to save teh data to a file again, you can just write the string to a file and you're done.

**Comment by siddharth-tewari** [comment]
@theOehrly Thank You. Can you provide sample code for this as I can't understand it or will check it from documents again.

**Comment by theOehrly** [comment]
``fastf1.api.fetch_page(race.api_path, 'team_radio')``

**Comment by siddharth-tewari** [comment]
@theOehrly Thank You!
